<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/01_04_shapes_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import relevant libraries
import numpy as np

In [ ]:
array0 = np.array([])

In [ ]:
# find the shape of array0
array0.shape

(0,)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])

In [ ]:
# find the shape of array1
array1.shape

(5,)

In [ ]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
# find the shape of array2
array2.shape

(3, 3)

In [ ]:
array_zeros = np.zeros((4, 5))

In [ ]:
# find the shape of array_zeros
array_zeros.shape

(4, 5)

In [ ]:
array_ones = np.ones((3, 6))

In [ ]:
# find the shape of array_ones
array_ones.shape

(3, 6)

In [ ]:
array_r0 = np.random.randint(1, 50, 25)
array_r0

array([33, 21, 30, 42, 29, 20, 32, 42, 43, 44, 26, 40, 14,  4, 23, 26, 11,
       35,  3,  3, 19, 44,  4,  9,  6])

In [ ]:
# find the shape of array_r0
array_r0.shape

(25,)

In [ ]:
# reshape array_r0
# to create a new multi-dimensional numpy array
# containing array_r0's items with 5 rows & 5 columns
array_r0.reshape((5, 5))

array([[33, 21, 30, 42, 29],
       [20, 32, 42, 43, 44],
       [26, 40, 14,  4, 23],
       [26, 11, 35,  3,  3],
       [19, 44,  4,  9,  6]])

In [ ]:
# note that array_r0 itself was not modified
array_r0

array([33, 21, 30, 42, 29, 20, 32, 42, 43, 44, 26, 40, 14,  4, 23, 26, 11,
       35,  3,  3, 19, 44,  4,  9,  6])

In [ ]:
array_r1 = np.random.randint(1, 50, 20)
array_r1

array([16, 25,  9, 43, 14, 29, 29, 19, 34, 40, 40, 36,  4, 28, 37, 34,  1,
       26,  8,  4])

In [ ]:
# find the shape of array_r1
array_r1.shape

(20,)

In [ ]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items
# with 10 rows & 2 columns
array_r1.reshape((10, 2))

array([[16, 25],
       [ 9, 43],
       [14, 29],
       [29, 19],
       [34, 40],
       [40, 36],
       [ 4, 28],
       [37, 34],
       [ 1, 26],
       [ 8,  4]])

In [ ]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items
# with 2 rows & 10 columns
array_r1.reshape((2, 10))

array([[16, 25,  9, 43, 14, 29, 29, 19, 34, 40],
       [40, 36,  4, 28, 37, 34,  1, 26,  8,  4]])

In [ ]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items
# with 4 rows & 5 columns
array_r1.reshape((4, 5))

array([[16, 25,  9, 43, 14],
       [29, 29, 19, 34, 40],
       [40, 36,  4, 28, 37],
       [34,  1, 26,  8,  4]])

In [ ]:
# reshape array_r1
# to create a new multi-dimensional numpy array containing array_r1's items
# with 5 rows & 4 columns
array_r1.reshape((5, 4))

array([[16, 25,  9, 43],
       [14, 29, 29, 19],
       [34, 40, 40, 36],
       [ 4, 28, 37, 34],
       [ 1, 26,  8,  4]])

In [ ]:
# note that array_r1 itself was not modified
array_r1

array([16, 25,  9, 43, 14, 29, 29, 19, 34, 40, 40, 36,  4, 28, 37, 34,  1,
       26,  8,  4])

In [ ]:
array_r2 = np.random.randint(1, 50, (4, 4))
array_r2

array([[ 5,  2,  3, 15],
       [25, 13, 37, 22],
       [23, 14, 39,  2],
       [43, 43, 35,  9]])

In [ ]:
# find the shape of array_r2
array_r2.shape

(4, 4)

In [ ]:
# reshape array_r2
# to create a new one-dimensional numpy array containing array_r2's items
# with length 16
array_r2.reshape(16)

array([ 5,  2,  3, 15, 25, 13, 37, 22, 23, 14, 39,  2, 43, 43, 35,  9])

In [ ]:
# note that array_r2 itself was not modified
array_r2