<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/01_07_scalar_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import relevant libraries
import numpy as np

In [2]:
# initialize arrayA as a one-dimensional numpy array
# containing the even integers between 2 and 20 inclusive
arrayA = np.arange(2, 21, 2)
arrayA

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
# add 3 to each element of arrayA, creating a new numpy array
arrayA + 3

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [4]:
# subtract 4 from each element of arrayA, creating a new numpy array
arrayA - 4

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [5]:
# multiply each element of arrayA by 5, creating a new numpy array
arrayA * 5

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
# divide each element of arrayA by 2, creating a new numpy array
arrayA / 2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
# initialize arrayB as a multi-dimensional numpy array with 2 rows and 3 columns
arrayB = np.array([[1, 2, 3], [4, 5, 6]])
arrayB

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# add 3 to each element of arrayB, creating a new numpy array
arrayB + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:
# subtract 4 from each element of arrayB, creating a new numpy array
arrayB - 4

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [10]:
# multiply each element of arrayB by 5, creating a new numpy array
arrayB * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [11]:
# divide each element of arrayB by 2, creating a new numpy array
arrayB / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])