<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/AGGREGATION_FUNCTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aggregation = Extracting ONE value from many values!

```arr = [[1, 2, 3],
       [4, 5, 6]]

# axis=None (default) - hammasi
arr.sum()  # 21

# axis=0 - VERTIKAL (↓) - har bir USTUN
arr.sum(axis=0)  # [5, 7, 9]
#  1+4=5, 2+5=7, 3+6=9

# axis=1 - HORIZONTAL (→) - har bir QATOR
arr.sum(axis=1)  # [6, 15]
#  1+2+3=6, 4+5+6=15
```

```
Data analysis:

📊 Statistics calculation
📈 Feature extraction
🔍 Data understanding

Image processing:

🎨 Brightness (mean)
🌗 Contrast (std)
📉 Histogram statistics

Machine Learning:

🧠 Feature engineering
📊 Normalization
🎯 Data preprocessing```

In [1]:
import numpy as np

#Basic Aggregations (1D)

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

Array: [10 20 30 40 50]


SUM - yig'indi

In [3]:
print("arr.sum():", arr.sum())

arr.sum(): 150


MEAN - o'rtacha


In [4]:
print("arr.mean():", arr.mean())

arr.mean(): 30.0


MIN - minimum

In [5]:
print("arr.min():", arr.min())

arr.min(): 10


MAX - maximum

In [6]:
print("arr.max():", arr.max())

arr.max(): 50


STD - standart og'ish (deviation)

In [7]:
print("arr.std():", arr.std())

arr.std(): 14.142135623730951


VAR - variance (dispersiya)

In [8]:
print("arr.var():", arr.var())

arr.var(): 200.0


MEDIAN - mediana (o'rta qiymat)

In [9]:
print("np.median(arr):", np.median(arr))

np.median(arr): 30.0


CUMSUM - cumulative sum (jamlanuvchi yig'indi)

In [10]:
print("np.cumsum(arr):", np.cumsum(arr))

np.cumsum(arr): [ 10  30  60 100 150]


PROD - product (ko'paytma)

In [11]:
print("arr.prod():", arr.prod())

arr.prod(): 12000000


#Aggregations with 2D Array


In [12]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print("Array:")
print(arr)
print("Shape:", arr.shape)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


##axis=0

AXIS=0 - VERTIKAL (↓) - har bir USTUN

In [13]:
print("arr.sum(axis=0):", arr.sum(axis=0))

arr.sum(axis=0): [15 18 21 24]


In [14]:
print("arr.mean(axis=0):", arr.mean(axis=0))

arr.mean(axis=0): [5. 6. 7. 8.]


In [15]:
print("arr.min(axis=0):", arr.min(axis=0))

arr.min(axis=0): [1 2 3 4]


In [16]:
print("arr.max(axis=0):", arr.max(axis=0))

arr.max(axis=0): [ 9 10 11 12]


In [17]:
print("arr.std(axis=0):", arr.std(axis=0))

arr.std(axis=0): [3.26598632 3.26598632 3.26598632 3.26598632]


In [18]:
print("arr.prod(axis=0):", arr.prod(axis=0))

arr.prod(axis=0): [ 45 120 231 384]


##axis=1

AXIS=1 - HORIZONTAL (→) - har bir QATOR

In [19]:
print("arr.sum(axis=1):", arr.sum(axis=1))

arr.sum(axis=1): [10 26 42]


In [20]:
print("arr.mean(axis=1):", arr.mean(axis=1))

arr.mean(axis=1): [ 2.5  6.5 10.5]


In [21]:
print("arr.min(axis=1):", arr.min(axis=1))

arr.min(axis=1): [1 5 9]


In [22]:
print("arr.max(axis=1):", arr.max(axis=1))

arr.max(axis=1): [ 4  8 12]


In [23]:
print("arr.std(axis=1):", arr.std(axis=1))

arr.std(axis=1): [1.11803399 1.11803399 1.11803399]


In [24]:
print("arr.prod(axis=1):", arr.prod(axis=1))

arr.prod(axis=1): [   24  1680 11880]


#Axis Visualization

In [25]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Array:")
print(arr)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print("="*60)
print("AXIS=0 (COLUMNS - Vertical ↓)")
print("="*60)
print()

print("Visual:")
print("     Col0  Col1  Col2")
print("     [1,   2,    3]   ← Row 0")
print("     [4,   5,    6]   ← Row 1")
print("     [7,   8,    9]   ← Row 2")
print("      ↓    ↓     ↓")
print("Sum: [12,  15,   18]  ← Column sums")
print()

result = arr.sum(axis=0)
print("arr.sum(axis=0):", result)
print("Shape:", result.shape)  # (3,)
print()

AXIS=0 (COLUMNS - Vertical ↓)

Visual:
     Col0  Col1  Col2
     [1,   2,    3]   ← Row 0
     [4,   5,    6]   ← Row 1
     [7,   8,    9]   ← Row 2
      ↓    ↓     ↓
Sum: [12,  15,   18]  ← Column sums

arr.sum(axis=0): [12 15 18]
Shape: (3,)



In [27]:
print("="*60)
print("AXIS=1 (ROWS - Horizontal →)")
print("="*60)
print()

print("Visual:")
print("     [1,  2,  3] → Sum: 6")
print("     [4,  5,  6] → Sum: 15")
print("     [7,  8,  9] → Sum: 24")
print()

result = arr.sum(axis=1)
print("arr.sum(axis=1):", result)
print("Shape:", result.shape)  # (3,)
print()

AXIS=1 (ROWS - Horizontal →)

Visual:
     [1,  2,  3] → Sum: 6
     [4,  5,  6] → Sum: 15
     [7,  8,  9] → Sum: 24

arr.sum(axis=1): [ 6 15 24]
Shape: (3,)



In [28]:
print("="*60)
print("AXIS=None (ALL - Everything)")
print("="*60)
print()

result = arr.sum()
print("arr.sum():", result)  # 45
print("Type:", type(result))  # scalar

AXIS=None (ALL - Everything)

arr.sum(): 45
Type: <class 'numpy.int64'>


#Image Statistics

In [29]:
img = np.random.randint(0, 256, size=(100, 100), dtype=np.uint8)
print("Image shape:", img.shape)

Image shape: (100, 100)


OVERALL STATISTICS

In [30]:
print(f"Mean brightness: {img.mean():.2f}")
print(f"Std (contrast): {img.std():.2f}")
print(f"Min (darkest): {img.min()}")
print(f"Max (brightest): {img.max()}")
print(f"Median brightness: {np.median(img):.2f}")

Mean brightness: 127.58
Std (contrast): 74.13
Min (darkest): 0
Max (brightest): 255
Median brightness: 128.00


PER-ROW STATISTICS (horizontal)

In [31]:
row_means = img.mean(axis=1)
print("Row means shape:", row_means.shape)
print("First 5 row means:", row_means[:5])
print(f"Darkest row: (avg):", row_means.min())
print(f"Brightest row: (avg):", row_means.max())

Row means shape: (100,)
First 5 row means: [114.7  122.97 126.23 128.34 126.19]
Darkest row: (avg): 105.09
Brightest row: (avg): 148.8


PER-COLUMN STATISTICS (vertical)

In [32]:
col_means = img.mean(axis=0)
print("Col means shape:", col_means.shape)
print("First 5 col means:", col_means[:5])
print(f"Darkest col: (avg):", col_means.min())
print(f"Brightest col: (avg):", col_means.max())

Col means shape: (100,)
First 5 col means: [133.96 140.39 123.24 124.54 131.09]
Darkest col: (avg): 114.48
Brightest col: (avg): 141.22


RGB Image (50x50x3)


In [33]:
rgb_img = np.random.randint(0, 256, (50, 50, 3), dtype=np.uint8)
print("RGB Image shape:", rgb_img.shape)

RGB Image shape: (50, 50, 3)


In [34]:
red_mean = rgb_img[:, :, 0].mean()
green_mean = rgb_img[:, :, 1].mean()
blue_mean = rgb_img[:, :, 2].mean()

print(f"Red mean: {red_mean:.2f}")
print(f"Green mean: {green_mean:.2f}")
print(f"Blue mean: {blue_mean:.2f}")

Red mean: 125.79
Green mean: 127.06
Blue mean: 126.60


Overall brightness (mean of all channels)

In [35]:
brightness = rgb_img.mean()
print(f"Overall brightness: {brightness:.2f}")


Overall brightness: 126.48
