<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/AGGREGATIONS_mini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Daily trades

In [ ]:
daily_sales = np.array([500, 650, 720, 580, 800, 690, 750])
print("Daily sales:")
print(daily_sales)

Daily sales:
[500 650 720 580 800 690 750]


Weekly total sales

In [ ]:
total = daily_sales.sum()
print("Total sales:")
print(total)

Total sales:
4690


#Student's test scores

In [ ]:
test_scores = np.array([85, 92, 78, 88, 90])

print("Test scores:")
print(test_scores)

Test scores:
[85 92 78 88 90]


Finding the average score

In [ ]:
average = test_scores.mean()
print("Average score:")
print(average)

Average score:
86.6


#3 months, 4 weeks of trading

In [ ]:
monthly = np.array([[20,    25,     22,     28],
                    [22,    27,     24,     30],
                    [21,    26,     23,     29]])
weeks = ["Week 1", "Week 2", "Week 3", "Week 4"]
print("Monthly sales:")
print(monthly)

Monthly sales:
[[20 25 22 28]
 [22 27 24 30]
 [21 26 23 29]]


In [ ]:
for week, avg in zip(weeks, monthly.mean(axis=0)):
  print(f"{week} average: {avg}")

Week 1 average: 21.0
Week 2 average: 26.0
Week 3 average: 23.0
Week 4 average: 29.0


#4 students, 3 subject grades

In [ ]:
grades = np.array([[85,   78,     92],
                   [90,   82,     88],
                   [78,   85,     95],
                   [88,   80,     90]])
students = ["Ali", "Vali", "Guli", "Diyor"]
print("Grades:")
print(grades)

Grades:
[[85 78 92]
 [90 82 88]
 [78 85 95]
 [88 80 90]]


In [ ]:
for student, avg in zip(students, grades.mean(axis=1)):
  print(f"{student} avg:{avg:.2f}")

Ali avg:85.00
Vali avg:86.67
Guli avg:86.00
Diyor avg:86.00


#5 stores, 4 products (daily sales)

In [ ]:
sales = np.array([[50,   40,    30,    35],
                  [45,   38,    28,    32],
                  [52,   42,    32,    38],
                  [48,   39,    29,    34],
                  [51,   41,    31,    36]])
products = ["Apple", "Banana", "Cherry", "Durian"]
stores = ["Store A", "Store B", "Store C", "Store D", "Store E"]
print("Sales:")
print(sales)

Sales:
[[50 40 30 35]
 [45 38 28 32]
 [52 42 32 38]
 [48 39 29 34]
 [51 41 31 36]]


Total sales of each PRODUCT

In [ ]:
total_products = sales.sum(axis=0)
for product, total in zip(products, total_products):
  print(f"{product} total: {total}")

Apple total: 246
Banana total: 200
Cherry total: 150
Durian total: 175


In [ ]:
total_stores = sales.sum(axis=1)
for store, total in zip(stores, total_stores):
  print(f"{store} total: {total}")

Store A total: 155
Store B total: 143
Store C total: 164
Store D total: 150
Store E total: 159


In [ ]:
product_max_idx = total_products.argmax()
print(f"{products[product_max_idx]}: ${total_products[product_max_idx]}")

Apple: $246


In [ ]:
store_max_idx = total_stores.argmax()
print(f"{stores[store_max_idx]}: ${total_stores[store_max_idx]}")

Store C: $164
