<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/ARRAY_RESHAPING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
reshape() - change dimensions
ravel() - convert to 1D (view)
flatten() - convert to 1D (copy)

In [ ]:
import numpy as np

#Basic Reshape! 🔄

1D array

In [ ]:
arr = np.arange(1, 13)
print("Origiginal array (1D):", arr)
print("Shape:", arr.shape)

Origiginal array (1D): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)


In [ ]:
print("Reshape (3, 4) - 3 rows, 4 columns:")
r1 = arr.reshape(3, 4)
print(r1)
print("Shape:", r1.shape)

Reshape (3, 4) - 3 rows, 4 columns:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [ ]:
print("Reshape (4, 3) - 4 rows, 3 columns:")
r2 = arr.reshape(4, 3)
print(r2)
print("Shape:", r2.shape)

Reshape (4, 3) - 4 rows, 3 columns:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)


In [ ]:
print("Reshape (2, 6) - 2 rows, 6 columns:")
r3 = arr.reshape(2, 6)
print(r3)
print("Shape:", r3.shape)

Reshape (2, 6) - 2 rows, 6 columns:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)


In [ ]:
print("Reshape (6, 2) - 6 rows, 2 columns:")
r4 = arr.reshape(6, 2)
print(r4)
print("Shape:", r4.shape)

Reshape (6, 2) - 6 rows, 2 columns:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape: (6, 2)


In [ ]:
print("Reshape (12, 1) - column vector:")
r5 = arr.reshape(12, 1)
print(r5)
print("Shape:", r5.shape)

Reshape (12, 1) - column vector:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Shape: (12, 1)


#Auto-dimension with -1! 🤖

In [ ]:
arr = np.arange(1, 13)
print("Original array:")
print(arr)
print("Shape:", arr.shape)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)


In [ ]:
print("Reshape (3, -1) - auto calculates 4:")
r1 = arr.reshape(3, -1)
print(r1)
print("Shape:", r1.shape)

Reshape (3, -1) - auto calculates 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [ ]:
print("Reshape (-1, 4) - auto calculates 3:")
r2 = arr.reshape(-1, 4)
print(r2)
print("Shape:", r2.shape)

Reshape (-1, 4) - auto calculates 3:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [ ]:
print("Reshape (-1, 1) - column vector:")
r3 = arr.reshape(-1, 1)
print(r3)
print("Shape:", r3.shape)

Reshape (-1, 1) - column vector:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Shape: (12, 1)


In [ ]:
print("Reshape (1, -1) - row vector:")
r4 = arr.reshape(1, -1)
print(r4)
print("Shape:", r4.shape)

Reshape (1, -1) - row vector:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Shape: (1, 12)


#Ravel vs Flatten! 📏

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original 2D array:")
print(arr)
print("Shape:", arr.shape)

Original 2D array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [ ]:
print("RAVEL (view):")
raveled = arr.ravel()
print(raveled)
print("Shape:", raveled.shape)

RAVEL (view):
[1 2 3 4 5 6]
Shape: (6,)


Test if it's a view

In [ ]:
print("Modify raveled[0] = 999:")
raveled[0] = 999
print("Raveled:", raveled)
print("Original arr:", arr)
print("→ Original changed! (view)")

Modify raveled[0] = 999:
Raveled: [999   2   3   4   5   6]
Original arr: [[999   2   3]
 [  4   5   6]]
→ Original changed! (view)


Reset

In [ ]:
arr[0, 0] = 1

FLATTEN - returns copy

In [ ]:
print("FLATTEN (copy):")
flattened = arr.flatten()
print(flattened)
print("Shape:", flattened.shape)

FLATTEN (copy):
[1 2 3 4 5 6]
Shape: (6,)


Test if it's a copy

In [ ]:
print("Modify flattened[0] = 999:")
flattened[0] = 999
print("Flattened:", flattened)
print("Original arr:", arr)
print("→ Original not changed! (copy)")

Modify flattened[0] = 999:
Flattened: [999   2   3   4   5   6]
Original arr: [[1 2 3]
 [4 5 6]]
→ Original not changed! (copy)


#Real Example - Image Data! 🖼️

In [ ]:
np.random.seed(42)
image = np.random.randint(0, 256, (10, 10))

In [ ]:
print("Original image (10, 10):")
print(image)
print("Shape:", image.shape)

Original image (10, 10):
[[102 179  92  14 106  71 188  20 102 121]
 [210 214  74 202  87 116  99 103 151 130]
 [149  52   1  87 235 157  37 129 191 187]
 [ 20 160 203  57  21 252 235  88  48 218]
 [ 58 254 169 255 219 187 207  14 189 189]
 [174 189  50 107  54 243  63 248 130 228]
 [ 50 134  20  72 166  17 131  88  59  13]
 [241 249   8  89  52 129  83  91 110 187]
 [198 171 252   7 174  34 205  80 163  49]
 [103 131   1 253 133  53 105   3  53 220]]
Shape: (10, 10)


Flatten for processing

In [ ]:
print("Flatten to 1D for ML model:")
flat = image.flatten()
print(f"Flattened shape: {flat.shape}")
print(f'First 10 pixels: {flat[:10]}')

Flatten to 1D for ML model:
Flattened shape: (100,)
First 10 pixels: [102 179  92  14 106  71 188  20 102 121]


Reshape back to image

In [ ]:
print("Reshape back to 2D:")
restored = flat.reshape(10, 10)
print(restored)
print("Shape:", restored.shape)

Reshape back to 2D:
[[102 179  92  14 106  71 188  20 102 121]
 [210 214  74 202  87 116  99 103 151 130]
 [149  52   1  87 235 157  37 129 191 187]
 [ 20 160 203  57  21 252 235  88  48 218]
 [ 58 254 169 255 219 187 207  14 189 189]
 [174 189  50 107  54 243  63 248 130 228]
 [ 50 134  20  72 166  17 131  88  59  13]
 [241 249   8  89  52 129  83  91 110 187]
 [198 171 252   7 174  34 205  80 163  49]
 [103 131   1 253 133  53 105   3  53 220]]
Shape: (10, 10)


Verify

In [ ]:
print("Images match:", np.array_equal(image, restored))

Images match: True


Reshape to different size (if needed)

In [ ]:
print("Reshape to 5x20:")
reshaped = flat.reshape(5, 20)
print(reshaped)
print("Shape:", reshaped.shape)

Reshape to 5x20:
[[102 179  92  14 106  71 188  20 102 121 210 214  74 202  87 116  99 103
  151 130]
 [149  52   1  87 235 157  37 129 191 187  20 160 203  57  21 252 235  88
   48 218]
 [ 58 254 169 255 219 187 207  14 189 189 174 189  50 107  54 243  63 248
  130 228]
 [ 50 134  20  72 166  17 131  88  59  13 241 249   8  89  52 129  83  91
  110 187]
 [198 171 252   7 174  34 205  80 163  49 103 131   1 253 133  53 105   3
   53 220]]
Shape: (5, 20)


In [ ]:
r = reshaped.reshape(20, 5)
print(r)

[[102 179  92  14 106]
 [ 71 188  20 102 121]
 [210 214  74 202  87]
 [116  99 103 151 130]
 [149  52   1  87 235]
 [157  37 129 191 187]
 [ 20 160 203  57  21]
 [252 235  88  48 218]
 [ 58 254 169 255 219]
 [187 207  14 189 189]
 [174 189  50 107  54]
 [243  63 248 130 228]
 [ 50 134  20  72 166]
 [ 17 131  88  59  13]
 [241 249   8  89  52]
 [129  83  91 110 187]
 [198 171 252   7 174]
 [ 34 205  80 163  49]
 [103 131   1 253 133]
 [ 53 105   3  53 220]]


#Student Grades Matrix

In [ ]:
grades = np.array([85, 90, 78, 88, 92, 84,
                   90, 88, 86, 82, 85, 80])

reshaped_for_students = grades.reshape(4, 3)
print(reshaped_for_students)
print("Shape:", reshaped_for_students.shape)

[[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]]
Shape: (4, 3)


In [ ]:
each_student_avg = reshaped_for_students.mean(axis=1)
print(each_student_avg)

[84.33333333 88.         88.         82.33333333]


In [ ]:
each_supjects_avg = reshaped_for_students.mean(axis=0)
print(each_supjects_avg)

[86.25 88.75 82.  ]


Auto-dimension Practice

In [ ]:
arr = np.arange(1, 25)

In [ ]:
r1 = arr.reshape(-1, 6)
rows = r1.shape[0]
print("Rows:", rows)

Rows: 4


In [ ]:
r2 = arr.reshape(4, -1)
columns = r2.shape[1]
print("Columns:", columns)

Columns: 6


In [ ]:
r3 = arr.reshape(-1, 1)
print(r3)
print("Shape:", r3.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
Shape: (24, 1)


#Flatten for Analysis

In [ ]:
np.random.seed(42)
weekly_temperature = np.random.randint(15, 30, (4, 7))
print("Shape:", weekly_temperature.shape)
print(weekly_temperature)

Shape: (4, 7)
[[21 18 27 29 25 22 27]
 [19 21 24 17 21 25 25]
 [22 19 18 22 22 17 20]
 [19 16 22 26 28 20 16]]


In [ ]:
flattened = weekly_temperature.flatten()
print(flattened)
print("Shape:", flattened.shape)

[21 18 27 29 25 22 27 19 21 24 17 21 25 25 22 19 18 22 22 17 20 19 16 22
 26 28 20 16]
Shape: (28,)


In [ ]:
overal_average = flattened.mean()
print(f"Average temperature: {overal_average:.1f}")

Average temperature: 21.7


In [ ]:
overal_min = flattened.min()
print(f"Minimum temperature: {overal_min}")

Minimum temperature: 16


In [ ]:
overal_max = flattened.max()
print(f"Maxsimum temperature: {overal_max}")

Maxsimum temperature: 29


In [ ]:
weekly_avg = weekly_temperature.mean(axis=1)
print(f"Weekly average temperature: {weekly_avg}")

Weekly average temperature: [24.14285714 21.71428571 20.         21.        ]


In [ ]:
dayly_avg = weekly_temperature.mean(axis=0)
print(f"Dayly average temperature: {dayly_avg}")

Dayly average temperature: [20.25 18.5  22.75 23.5  24.   21.   22.  ]
