<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/ARRAY_OPERATIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Python list vs NumPy

In [ ]:
# Python list - SEKIN (loop kerak)
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = []
for i in range(len(list1)):
  result.append(list1[i] +list2[i])
print(result)

[5, 7, 9]


Why fast?

Written in C

Parallel computing

Optimized memory access

In [ ]:
# NumPy - TEZ (loopsiz!)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


#Types of operations

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])

In [ ]:
print("arr1:", arr1)
print("arr2:", arr2)

arr1: [10 20 30 40 50]
arr2: [1 2 3 4 5]


1. Element-wise (each element separately):

ADD (+) arr1 + arr2

In [ ]:
result = arr1 + arr2
print("arr1 + arr2 =", result)

arr1 + arr2 = [11 22 33 44 55]


SUBTRACT (-)  arr1 - arr2

In [ ]:
result = arr1 - arr2
print("arr1 - arr2 =",result)

arr1 - arr2 = [ 9 18 27 36 45]


MULTIPLICATION (*)  arr1 * arr2     ELEMENT-WISE!

In [ ]:
result =arr1 * arr2
print("arr1 * arr2 =", result)

arr1 * arr2 = [ 10  40  90 160 250]


DIVISION (/)   arr1 / arr2

In [ ]:
result = arr1 / arr2
print("arr1 / arr2 =", result)

arr1 / arr2 = [10. 10. 10. 10. 10.]


WHOLE DIVISION (//)  arr1 // arr2

In [ ]:
result = arr1 // arr2
print("arr1 // arr2 =", result)

arr1 // arr2 = [10 10 10 10 10]


RESIDUE (%)  arr1 % arr2

In [ ]:
result = arr1 % arr2
print("arr1 % arr2 =", result)

arr1 % arr2 = [0 0 0 0 0]


Square (**) arr1 ** arr2

In [ ]:
result = arr1 ** arr2
print("arr1 ** arr2 =", result)

arr1 ** arr2 = [       10       400     27000   2560000 312500000]


2. Scalar (with a single number)

In [ ]:
arr = arr2

Add 10 to each element

In [ ]:
print("arr + 10 =", arr + 10)

arr + 10 = [11 12 13 14 15]


Subtract 3 from each element

In [ ]:
print("arr - 3 =", arr - 3)

arr - 3 = [-2 -1  0  1  2]


Multiply each element by 5

In [ ]:
print("arr * 5 =", arr * 5)

arr * 5 = [ 5 10 15 20 25]


Divide each element by 2

In [ ]:
print("arr / 2 =", arr / 2)

arr / 2 = [0.5 1.  1.5 2.  2.5]


Square each element

In [ ]:
print("arr ** 2 =", arr ** 2)

arr ** 2 = [ 1  4  9 16 25]


Dividing each element by 2

In [ ]:
print("arr // 2 =", arr // 2)

arr // 2 = [0 1 1 2 2]


In [ ]:
arr_100 = np.arange(100)
print("arr_100 // 3 =", arr_100 // 3)

arr_100 // 3 = [ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 10 10 11 11 11 12 12 12 13 13 13 14 14 14 15 15 15
 16 16 16 17 17 17 18 18 18 19 19 19 20 20 20 21 21 21 22 22 22 23 23 23
 24 24 24 25 25 25 26 26 26 27 27 27 28 28 28 29 29 29 30 30 30 31 31 31
 32 32 32 33]


Divide each element by 10 to get the remainder

In [ ]:
print("arr % 10 =", arr % 10)

arr % 10 = [1 2 3 4 5]


##2D Array Operations

In [ ]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("arr1:")
print(arr1)
print("arr2:")
print(arr2)

arr1:
[[1 2 3]
 [4 5 6]]
arr2:
[[10 20 30]
 [40 50 60]]


Add element-wise

In [ ]:
print("arr1 + arr2:")
print(arr1 + arr2)

arr1 + arr2:
[[11 22 33]
 [44 55 66]]


Element-wise subtraction

In [ ]:
print("arr2 - arr1:")
print(arr2 - arr1)

arr2 - arr1:
[[ 9 18 27]
 [36 45 54]]


Element-wise multiplication

In [ ]:
print("arr1 * arr2:")
print(arr1 * arr2)

arr1 * arr2:
[[ 10  40  90]
 [160 250 360]]


Element-wise division

In [ ]:
print("arr2 / arr1:")
print(arr2 / arr1)

arr2 / arr1:
[[10. 10. 10.]
 [10. 10. 10.]]


Scalar operations

In [ ]:
print("arr1 * 10:")
print(arr1 * 10)

arr1 * 10:
[[10 20 30]
 [40 50 60]]


Mixed operations

In [ ]:
result = (arr1 + arr2) * 2
print("(arr1 + arr2) * 2:")
print(result)

(arr1 + arr2) * 2:
[[ 22  44  66]
 [ 88 110 132]]


3. Universal functions (ufunc):

np.sqrt(arr)   # Ildiz

np.exp(arr)    # e^x

np.log(), np.log10() - logaritm

np.sin(), np.cos(), np.tan() - trigonometriya

np.abs() - absolut qiymat

np.round(), np.floor(), np.ceil() - yaxlitlash

In [ ]:
arr = np.array([1, 4, 9, 16, 25])

print("Array:", arr)

Array: [ 1  4  9 16 25]


Square root

In [ ]:
print("np.sqrt(arr) =", np.sqrt(arr))

np.sqrt(arr) = [1. 2. 3. 4. 5.]


EKSPONENTA (e^x)

In [ ]:
print("np.exp(arr) =", np.exp(arr))

np.exp(arr) = [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


LOGARITM

In [ ]:
print("np.log(arr) =", np.log(arr))

np.log(arr) = [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [ ]:
arr = np.array([1, 10, 100, 1000, 10000])
print("np.log10(arr) =", np.log10(arr))

np.log10(arr) = [0. 1. 2. 3. 4.]


ABSOLUTE VALUE

In [ ]:
arr = np.array([-5, -2, 0, 3, 7])
print("np.abs(arr) =", np.abs(arr))

np.abs(arr) = [5 2 0 3 7]


TRIGONOMETRY

In [ ]:
angles = np.array([0, np.pi/2, np.pi])
print("np.sin(angles) =", np.sin(angles))

np.sin(angles) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]


OVERALL

In [ ]:
arr = np.array([1.2, 2.7, 3.5, 4.9])

In [ ]:
print("np.round(arr) =", np.round(arr))

np.round(arr) = [1. 3. 4. 5.]


In [ ]:
print("np.floor(arr) =", np.floor(arr))

np.floor(arr) = [1. 2. 3. 4.]


In [ ]:
print("np.ceil(arr) =", np.ceil(arr))

np.ceil(arr) = [2. 3. 4. 5.]


4. Comparison Operations

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("arr1:", arr1)
print("arr2:", arr2)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]


COMPARISON

In [ ]:
print("arr1 > arr2:", arr1 > arr2)

arr1 > arr2: [False False False  True  True]


In [ ]:
print("arr1 < arr2:", arr1 < arr2)

arr1 < arr2: [ True  True False False False]


In [ ]:
print("arr1 == arr2:", arr1 == arr2)

arr1 == arr2: [False False  True False False]


LOGICAL OPERATIONS

In [ ]:
print("arr1 < 3:", arr1 < 3)

arr1 < 3: [ True  True False False False]


In [ ]:
print("arr2 > 2:", arr2 > 2)

arr2 > 2: [ True  True  True False False]


In [ ]:
print("(arr1 > 2) & (arr1 < 5):", (arr1 >2) & (arr1<5))

(arr1 > 2) & (arr1 < 5): [False False  True  True False]


#Real-world - Image Processing

In [ ]:
img = np.array([[100, 150, 200],
                [50, 100, 150],
                [0, 50, 100]], dtype=np.uint8)

print("Original Image:")
print(img)

Original Image:
[[100 150 200]
 [ 50 100 150]
 [  0  50 100]]


Add BRIGHTNESS

In [ ]:
brighter= img + 50  # Overflow muammosi!
print("Brighter (unsafe):")
print(brighter)

Brighter (unsafe):
[[150 200 250]
 [100 150 200]
 [ 50 100 150]]


SAFE brightness (clip)

In [ ]:
brighter_safe = np.clip(img + 50, 0, 255).astype(np.uint8)
print("Brighter (safe):")
print(brighter_safe)

Brighter (safe):
[[150 200 250]
 [100 150 200]
 [ 50 100 150]]


CONTRAST (kontrast oshirish)

In [ ]:
contrast = np.clip(img * 1.5, 0, 255).astype(np.uint8)
print("Increased Contrast:")
print(contrast)

Increased Contrast:
[[150 225 255]
 [ 75 150 225]
 [  0  75 150]]


NEGATIVE (invert)

In [ ]:
negative = 255 - img
print("Negative Image:")
print(negative)

Negative Image:
[[155 105  55]
 [205 155 105]
 [255 205 155]]


THRESHOLD (binary)

In [ ]:
treshold = (img > 100).astype(np.uint8) * 255
print("Thresholded Image:")
print(treshold)


Thresholded Image:
[[  0 255 255]
 [  0   0 255]
 [  0   0   0]]


#PRACTICE

BASIC OPERATIONS

In [ ]:
arr1 = np.array([2, 4, 6, 8, 10])
arr2 = np.array([1, 2, 3, 4, 5])

In [ ]:
result = arr1 + arr2
print("arr1 + arr2 =", result)

arr1 + arr2 = [ 3  6  9 12 15]


In [ ]:
result = arr1 * arr2
print("arr1 * arr2 =", result)

arr1 * arr2 = [ 2  8 18 32 50]


In [ ]:
result = arr1 ** 2
print("arr1 ** 2 =", result)

arr1 ** 2 = [  4  16  36  64 100]


SCALAR OPERATIONS

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
result = arr * 3
print("arr * 3 =", result)

arr * 3 = [ 30  60  90 120 150]


In [ ]:
result = arr - 5
print("arr - 5 =", result)

arr - 5 = [ 5 15 25 35 45]


In [ ]:
result = arr / 2
print("arr / 2 =", result)

arr / 2 = [ 5. 10. 15. 20. 25.]


UFUNC

In [ ]:
arr = np.array([1, 4, 9, 16, 25])

In [ ]:
result = np.sqrt(arr)
print("np.sqrt(arr) =", result)

arr ** 2) = [  1  16  81 256 625]


In [ ]:
result = arr ** 2
print("arr ** 2) =", result)

arr ** 2) = [  1  16  81 256 625]


In [ ]:
arr = np.array([-10, -5, 0, 5, 10])

In [ ]:
result = np.abs(arr)
print("np.abs(arr) =", result)

np.abs(arr) = [10  5  0  5 10]


2D OPERATIONS

In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

In [ ]:
result = mat1 + mat2
print("mat1 + mat2:")
print(result)

mat1 + mat2:
[[ 6  8]
 [10 12]]


In [ ]:
result = mat1 * 10
print("mat1 * 10:")
print(result)

mat1 * 10:
[[10 20]
 [30 40]]


IMAGE PROCESSING

In [ ]:
img = np.array([[100, 150, 200],
                [50, 100, 150]], dtype=np.uint8)

In [ ]:
brightness = np.clip(img + 30, 0, 255).astype(np.uint8)
print("Brightness:")
print(brightness)

Brightness:
[[130 180 230]
 [ 80 130 180]]


In [ ]:
negative = 255 - img
print("Negative:")
print(negative)

Negative:
[[155 105  55]
 [205 155 105]]


In [ ]:
pixel_2 = img / 2
print("Pixel 2:")
print(pixel_2.astype(np.uint8))

Pixel 2:
[[ 50  75 100]
 [ 25  50  75]]


In [ ]:
arr = np.random.randint(0, 100, size=(10, 10))

In [ ]:
result = arr[(arr * 2) > 50]
print("Result arr * 2 > 50:")
print(result)

Result arr * 2 > 50:
[67 43 93 56 56 51 31 30 91 26 42 94 29 83 70 31 47 95 65 79 70 60 93 72
 33 27 48 72 49 61 59 27 48 44 33 77 96 60 35 51 94 83 58 63 63 67 88 87
 47 62 75 62 76 90 81 30 48 39 99 58 26 41 40 79 32 82 93 69 37 94 98 54
 40 29 27 53 88]


In [ ]:
x = np.random.randint(0, np.pi*2, size = (100))
y = np.sin(x)
print(y)

[-0.7568025   0.14112001 -0.95892427 -0.95892427  0.         -0.95892427
 -0.7568025   0.90929743 -0.7568025   0.         -0.7568025   0.84147098
  0.90929743  0.84147098 -0.7568025   0.84147098 -0.95892427 -0.7568025
  0.84147098  0.90929743  0.14112001  0.          0.14112001  0.84147098
 -0.7568025   0.         -0.7568025   0.90929743  0.14112001  0.90929743
  0.         -0.95892427  0.90929743  0.14112001  0.          0.84147098
 -0.7568025  -0.95892427  0.          0.84147098  0.90929743 -0.95892427
 -0.7568025   0.         -0.7568025  -0.7568025   0.14112001  0.90929743
  0.84147098  0.84147098  0.84147098 -0.7568025   0.84147098  0.
 -0.95892427 -0.7568025   0.          0.84147098 -0.95892427  0.
 -0.95892427 -0.7568025   0.14112001  0.         -0.95892427  0.84147098
  0.84147098 -0.95892427  0.14112001  0.90929743  0.90929743  0.84147098
  0.90929743  0.          0.14112001 -0.7568025   0.14112001 -0.7568025
 -0.7568025  -0.95892427 -0.7568025  -0.7568025   0.84147098  0.
  0.

In [ ]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
print(y)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769