<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/ARRAY_SPLITTING_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.split() - general split (har qanday)
np.vsplit() - vertical split (qatorlar) ↕️
np.hsplit() - horizontal split (ustunlar) ↔️

```
SPLIT:

 Split data into train/test
 Split data into parts
 Batch processing

VSPLIT:

 Separate rows
 Student groups
 Time periods

HSPLIT:

 Separate features
 Split columns
 Input/Output separation

In [ ]:
import numpy as np

#Basic Splitting! ✂️

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)
print(f"Shape: {arr.shape}")

Original array: [1 2 3 4 5 6 7 8 9]
Shape: (9,)


In [ ]:
parts = np.split(arr, 3)
print("Split into 3 parts:")
print(parts)
for i, part in enumerate(parts, 1):
  print(f"Part {i}: {part}")

Split into 3 parts:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]


In [ ]:
indices = [2, 5, 7]
parts2 = np.split(arr, indices)
print(f"Split at indices {indices}:")
for i, part in enumerate(parts2):
  print(f"Part {i}: {part}")

Split at indices [2, 5, 7]:
Part 0: [1 2]
Part 1: [3 4 5]
Part 2: [6 7]
Part 3: [8 9]


#VSPLIT & HSPLIT! ↕️↔️

In [ ]:
data = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9,  10, 11, 12],
                 [13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]])

print("Original data:")
print(data)
print(f"Shape: {data.shape}")

Original data:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)


 VSPLIT - split into 3 parts (rows)

In [ ]:
row_parts = np.vsplit(data, 3)
print("VSplit into 3 parts:")
for i, part in enumerate(row_parts, 1):
  print(f"Part {i}:")
  print(part)
  print(f"Shape: {part.shape}")

VSplit into 3 parts:
Part 1:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Part 2:
[[ 9 10 11 12]
 [13 14 15 16]]
Shape: (2, 4)
Part 3:
[[17 18 19 20]
 [21 22 23 24]]
Shape: (2, 4)


HSPLIT - split into 2 parts (columns)

In [ ]:
col_parts = np.hsplit(data, 2)
for i, part in enumerate(col_parts, 1):
  print(f"Part {i}:")
  print(part)
  print(f'Shape: {part.shape}')

Part 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
Shape: (6, 2)
Part 2:
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]
Shape: (6, 2)


#Train/Test Split - Real ML! 🤖

In [ ]:
np.random.seed(7)
data = np.random.rand(100, 5)

print("Original dataset:")
print(f"Shape: {data.shape}")

Original dataset:
Shape: (100, 5)


In [ ]:
train, test = np.split(data, [80])

print("After 80/20 split:")
print(f"Train shape: {train.shape}")
print(f"Test shape: {test.shape}")

print(f"Train: {train.shape[0]} samples ({train.shape[0]/100 * 100:.0f}%)")
print(f"Test: {test.shape[0]} samples ({test.shape[0]/100 * 100:.0f}%)")

After 80/20 split:
Train shape: (80, 5)
Test shape: (20, 5)
Train: 80 samples (80%)
Test: 20 samples (20%)


In [ ]:
train, val, test = np.split(data, [70, 85])

print("After 70/15/15 split:")
print(f"Train shape: {train.shape}")
print(f"Validation shape: {val.shape}")
print(f"Test shape: {test.shape}")

After 70/15/15 split:
Train shape: (70, 5)
Validation shape: (15, 5)
Test shape: (15, 5)


#Student Groups! 👥

In [ ]:
students = np.array([[85, 90, 78],
                     [88, 92, 84],
                     [90, 88, 86],
                     [82, 85, 80],
                     [95, 93, 91],
                     [78, 82, 75],
                     [92, 89, 94],
                     [87, 91, 83],
                     [84, 86, 88],
                     [91, 94, 89],
                     [79, 81, 77],
                     [93, 90, 92]])

print("Class data (12 students, 3 subjects):")
print(f"Shape: {students.shape}")

Class data (12 students, 3 subjects):
Shape: (12, 3)


In [ ]:
groups = np.vsplit(students, 3)

print("Split into 3 groups:")
for i, group in enumerate(groups, 1):
  print(f"Group {i}:")
  print(group)
  print(f"Average: {group.mean(axis=1)}")
  print(f"Group average: {group.mean():.2f}")

Split into 3 groups:
Group 1:
[[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]]
Average: [84.33333333 88.         88.         82.33333333]
Group average: 85.67
Group 2:
[[95 93 91]
 [78 82 75]
 [92 89 94]
 [87 91 83]]
Average: [93.         78.33333333 91.66666667 87.        ]
Group average: 87.50
Group 3:
[[84 86 88]
 [91 94 89]
 [79 81 77]
 [93 90 92]]
Average: [86.         91.33333333 79.         91.66666667]
Group average: 87.00


#Weekly Data Split

In [ ]:
temperatures = np.array([20, 22, 25, 23, 21, 24, 26,
                18, 20, 22, 21, 19, 22, 24,
                22, 24, 27, 25, 23, 26, 28])

print("Weekly temperatures:")
print(temperatures)

Weekly temperatures:
[20 22 25 23 21 24 26 18 20 22 21 19 22 24 22 24 27 25 23 26 28]


In [ ]:
three_week = np.split(temperatures, 3)
average_list = np.array([])
for i, week in enumerate(three_week, 1):
  print(f"Week {i}:")
  print(week)
  avg = week.mean()
  print(f"Average: {avg:.2f}")
  average_list = np.append(average_list, avg)
print(f"Average of averages: {average_list}")
hottest = average_list.max()
idx_hottest = average_list.argmax()
print(f"Hottest week {idx_hottest + 1}: {hottest}")

Week 1:
[20 22 25 23 21 24 26]
Average: 23.00
Week 2:
[18 20 22 21 19 22 24]
Average: 20.86
Week 3:
[22 24 27 25 23 26 28]
Average: 25.00
Average of averages: [23.         20.85714286 25.        ]
Hottest week 3: 25.0


In [ ]:
average = three_week[0].mean()
print(average)

23.0


#Feature Separation

Student data: 6 students, 4 columns

In [ ]:
data = np.array([[1, 85, 90, 78],
        [2, 88, 92, 84],
        [3, 90, 88, 86],
        [4, 82, 85, 80],
        [5, 95, 93, 91],
        [6, 78, 82, 75]])
data_type = ['ID', 'Math', 'Physics', 'English']

print("Student data:")
print(data)
print(f"Shape: {data.shape}")

Student data:
[[ 1 85 90 78]
 [ 2 88 92 84]
 [ 3 90 88 86]
 [ 4 82 85 80]
 [ 5 95 93 91]
 [ 6 78 82 75]]
Shape: (6, 4)


In [ ]:
id, scores = np.hsplit(data, [1])
print("ID:", id.flatten())
print("Scores:", scores)

ID: [1 2 3 4 5 6]
Scores: [[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]
 [95 93 91]
 [78 82 75]]


In [ ]:
average = scores.mean()
print(f"Average for all score: {average:.2f}")

average_student = scores.mean(axis=1)
print("Average for each student:")
for i, avg in enumerate(average_student, 1):
  print(f"Student {i}: {avg:.2f}")

average_subject = scores.mean(axis=0)
print("Average for each subject:")
for i, avg in enumerate(average_subject, 1):
  print(f"{data_type[i]}: {avg:.2f}")

Average for all score: 85.67
Average for each student:
Student 1: 84.33
Student 2: 88.00
Student 3: 88.00
Student 4: 82.33
Student 5: 93.00
Student 6: 78.33
Average for each subject:
Math: 86.33
Physics: 88.33
English: 82.33


#Batch Processing

In [ ]:
element = np.arange(1, 21)
print("Original array:", element)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
batches = np.split(element, 5)
batch_sum_list = np.array([])
for i, batch in enumerate(batches, 1):
  batch_sum = batch.sum()
  batch_sum_list = np.append(batch_sum_list, batch_sum)
  print(f"Batch {i} sum:{batch_sum}")

print(f"Batch {batch_sum_list.argmax()+1} max sum: {batch_sum_list.max()}")

Batch 1 sum:10
Batch 2 sum:26
Batch 3 sum:42
Batch 4 sum:58
Batch 5 sum:74
Batch 5 max sum: 74.0
