<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/ARRAY_STACKING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.vstack() - vertical stack (add rows) ↓
np.hstack() - horizontal stack (add columns) →

```
VSTACK - vertical (rows):

Add students

Add daily data

When you need to add rows

HSTACK - horizontal (columns):

Add new column
Expand data
Add features

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#Basic Stacking!

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print("VSTACK")
print(result)

result = np.hstack((a, b))
print("HSTACK")
print(result)

VSTACK
[[1 2 3]
 [4 5 6]]
HSTACK
[1 2 3 4 5 6]


In [ ]:
c = np.array([7, 8, 9])

print("Array a:", a)
print("Array b:", b)
print("Array c:", c)

Array a: [1 2 3]
Array b: [4 5 6]
Array c: [7 8 9]


VERTICAL STACK

In [ ]:
vertical = np.vstack([a, b, c])
print("Vertical Stack:")
print(vertical)
print(f"Shape: {vertical.shape}")

Vertical Stack:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


HORIZONTAL STACK

In [ ]:
horizontal = np.hstack([a, b, c])
print("Horizontal Stack:")
print(horizontal)
print(f"Shape: {horizontal.shape}")

Horizontal Stack:
[1 2 3 4 5 6 7 8 9]
Shape: (9,)


#Student Data - Real Example! 📚

3 student grades (Math, Physics, English)

In [ ]:
student1 = np.array([85, 90, 78])
student2 = np.array([88, 92, 94])
student3 = np.array([90, 88, 86])

print("Student 1:", student1)
print("Student 2:", student2)
print("Student 3:", student3)

Student 1: [85 90 78]
Student 2: [88 92 94]
Student 3: [90 88 86]


VSTACK - combine all students

In [ ]:
class_data = np.vstack([student1, student2, student3])
print("Class Data:")
print(class_data)
print(f"Shape: {class_data.shape}")

Class Data:
[[85 90 78]
 [88 92 94]
 [90 88 86]]
Shape: (3, 3)


Now we can do operations

In [ ]:
print("Subject averages (axis=0):")
subject_avg = class_data.mean(axis=0)
subjects = ['Math', 'Physics', 'English']

for subject, avg in zip(subjects, subject_avg):
  print(f"{subject}: {avg:.1f}")

Subject averages (axis=0):
Math: 87.7
Physics: 90.0
English: 86.0


In [ ]:
print("Student averages (axis=1):")
student_avg = class_data.mean(axis=1)
students = ['Student 1', 'Student 2', 'Student 3']

for student, avg in zip(students, student_avg):
  print(f"{student}: {avg:.1f}")

Student averages (axis=1):
Student 1: 84.3
Student 2: 91.3
Student 3: 88.0


#Add New Column (hstack)! 📊

Student scores (3 students, 3 subjects)

In [ ]:
scores = np.array([[85, 90, 78],
                   [88, 92, 84],
                   [90, 88, 86]])

print("Original scores:")
print(scores)
print(f"Shape: {scores.shape}")

Original scores:
[[85 90 78]
 [88 92 84]
 [90 88 86]]
Shape: (3, 3)


In [ ]:
averages = scores.mean(axis=1).reshape(-1, 1)
print("Averages (reshaped to column):")
print(averages)
print(f"Shape: {averages.shape}")

Averages (reshaped to column):
[[84.33333333]
 [88.        ]
 [88.        ]]
Shape: (3, 1)


HSTACK - add average column

In [ ]:
scores_with_avg = np.hstack([scores, averages])

print("Scores with Averages:")
print(scores_with_avg)
print(f"Shape: {scores_with_avg.shape}")

cols = ['Math', 'Physics', 'English', 'Average']
print("Columns:", cols)

Scores with Averages:
[[85.         90.         78.         84.33333333]
 [88.         92.         84.         88.        ]
 [90.         88.         86.         88.        ]]
Shape: (3, 4)
Columns: ['Math', 'Physics', 'English', 'Average']


#Daily Data Accumulation! 📅

In [ ]:
day1 = np.array([100, 150, 120, 180])
print("Day 1 sales:", day1)

weekly_sales = day1.reshape(1, -1)
print("Weekly sales (reshaped to row):")
print(weekly_sales)
print(f"Shape: {weekly_sales.shape}")

Day 1 sales: [100 150 120 180]
Weekly sales (reshaped to row):
[[100 150 120 180]]
Shape: (1, 4)


In [ ]:
day2 = np.array([110, 145, 125, 175])
print("Day 2 sales:", day2)

weekly_sales = np.vstack([weekly_sales, day2])
print("Weekly sales (after day 2):")
print(weekly_sales)

Day 2 sales: [110 145 125 175]
Weekly sales (after day 2):
[[100 150 120 180]
 [110 145 125 175]]


In [ ]:
day3 = np.array([105, 155, 130, 185])
print("Day 3 sales:", day3)

weekly_sales = np.vstack([weekly_sales, day3])
print("Weekly sales (after day 3):")
print(weekly_sales)

Day 3 sales: [105 155 130 185]
Weekly sales (after day 3):
[[100 150 120 180]
 [110 145 125 175]
 [105 155 130 185]]


In [ ]:
print("Total per stone (axis=0):")
print(weekly_sales.sum(axis=0))

Total per stone (axis=0):
[315 450 375 540]


In [ ]:
print("Daily totals (axis=1):")
print(weekly_sales.sum(axis=1))

Daily totals (axis=1):
[550 555 575]


#Temperature Data

Weekly temperature of 3 cities (7 days)

In [ ]:
toshkent = np.array([20, 22, 25, 23, 21, 24, 26])
samarqand = np.array([18, 20, 22, 21, 19, 22, 24])
buxoro = np.array([22, 24, 27, 25, 23, 26, 28])

In [ ]:
cities_temperature = np.vstack([toshkent, samarqand, buxoro])
print("Cities Temperature:")
print(cities_temperature)
print(f'Shape: {cities_temperature.shape}')

Cities Temperature:
[[20 22 25 23 21 24 26]
 [18 20 22 21 19 22 24]
 [22 24 27 25 23 26 28]]
Shape: (3, 7)


In [ ]:
avg_daily = cities_temperature.mean(axis=0)
print("Average temperature (axis=0):")
print(avg_daily)

Average temperature (axis=0):
[20.         22.         24.66666667 23.         21.         24.
 26.        ]


In [ ]:
avg_cities = cities_temperature.mean(axis=1)
print("Average temperature (axis=1):")
print(avg_cities)

Average temperature (axis=1):
[23.         20.85714286 25.        ]


#Add ID Column

Student grade (4 students, 3 subjects)

In [ ]:
scores = np.array([[85, 90, 78],
          [88, 92, 84],
          [90, 88, 86],
          [82, 85, 80]])

id = np.array([1, 2, 3, 4]).reshape(-1, 1)

print("Original scores:")
print(scores)
print(f"Shape: {scores.shape}")
print("ID column:")
print(id)

Original scores:
[[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]]
Shape: (4, 3)
ID column:
[[1]
 [2]
 [3]
 [4]]


In [ ]:
students_scores = np.hstack((id, scores))
print("Students Scores:")
print(students_scores)

Students Scores:
[[ 1 85 90 78]
 [ 2 88 92 84]
 [ 3 90 88 86]
 [ 4 82 85 80]]


#Combine Teams

2 football team scores (5 games)

In [ ]:
team_a = np.array([2, 3, 1, 2, 3])
team_b = np.array([1, 2, 2, 3, 1])

print("Team A scores:", team_a)
print("Team B scores:", team_b)

Team A scores: [2 3 1 2 3]
Team B scores: [1 2 2 3 1]


In [ ]:
scores_team = np.vstack((team_a, team_b))
print("Scores Team:")
print(scores_team)

Scores Team:
[[2 3 1 2 3]
 [1 2 2 3 1]]


In [ ]:
all_goals = scores_team.sum(axis=0)
print("All goals (axis=0):")
print(all_goals)

All goals (axis=0):
[3 5 3 5 4]


In [ ]:
all_team_goals = scores_team.sum(axis=1)
print("All team goals (axis=1):")
print(all_team_goals)

All team goals (axis=1):
[11  9]


In [ ]:
team = np.array(['Team A', 'Team B'])
print("Teams:", team)
max_goals = all_team_goals.max()
print("Max goals:", max_goals)
axis_max_goals = np.argmax(all_team_goals)
print("Axis max goals:", axis_max_goals)
print("Winner:", team[axis_max_goals])

Teams: ['Team A' 'Team B']
Max goals: 11
Axis max goals: 0
Winner: Team A
