<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/AXIS%3D0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Axis=0

In [ ]:
import numpy as np

Total sales of each PRODUCT

In [ ]:
sales = np.array([[10, 20, 15, 25],
                  [12, 18, 17, 23],
                  [11, 22, 16, 24]])
print("Sales:")
print(sales)

Sales:
[[10 20 15 25]
 [12 18 17 23]
 [11 22 16 24]]


In [ ]:
total_per_product = sales.sum(axis=0)
print("Total sales of each PRODUCT")
print(total_per_product)

Total sales of each PRODUCT
[33 60 48 72]


#3 players, 4 games 🎮

In [ ]:
scores = np.array([[10, 15, 12, 18],
                   [12, 14, 13, 16],
                   [11, 13, 14, 17]])
print("Players scores:")
print(scores)

Players scores:
[[10 15 12 18]
 [12 14 13 16]
 [11 13 14 17]]


Average score per game (axis=0)

**Vizual:**
```
        Game1  Game2  Game3  Game4
Ali:     10     15     12     18
Vali:    12     14     13     16
Guli:    11     13     14     17
         ↓      ↓      ↓      ↓
Avg:    11.0   14.0   13.0   17.0

In [ ]:
game_avg = scores.mean(axis=0)
print("Average score per game:")
print(game_avg)

Average score per game:
[11. 14. 13. 17.]


#Weekly sales

In [ ]:
sales = np.array([[100, 120, 110, 130, 150],
                  [105, 115, 115, 125, 145],
                  [110, 125, 120, 135, 155]])
print("Weekly sales:")
print(sales)

Weekly sales:
[[100 120 110 130 150]
 [105 115 115 125 145]
 [110 125 120 135 155]]


Average daily sales (axis=0)

In [ ]:
daily_avg = sales.mean(axis=0)
days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
print("Average daily sales:")
for day, avg in zip(days, daily_avg):
  print(f"{day}: ${avg:.1f}")

Average daily sales:
Monday: $105.0
Tuesday: $120.0
Wednesday: $115.0
Thursday: $130.0
Friday: $150.0


#Class grade 📚

In [ ]:
grades = np.array([[85, 78, 92],
                   [90, 82, 88],
                   [78, 85, 95],
                   [88, 80, 90]])
print("Class grades:")
print(grades)

Class grades:
[[85 78 92]
 [90 82 88]
 [78 85 95]
 [88 80 90]]


Average grade for each subject (axis=0)

In [ ]:
subject_avg = grades.mean(axis=0)
subjects = ["Math", "Physics", "English"]

print("Average grade for each subject:")
for subject, avg in zip(subjects, subject_avg):
  print(f"{subject}: {avg:.1f}")

Average grade for each subject:
Math: 85.2
Physics: 81.2
English: 91.2


#Monthly temperature

In [ ]:
temp = np.array([[-5,    0,     8,     15],
                 [-10,   -5,    5,     12],
                 [-3,    2,     10,    18]])

print("Monthly temperatures:")
print(temp)

Monthly temperatures:
[[ -5   0   8  15]
 [-10  -5   5  12]
 [ -3   2  10  18]]


Average temperature of each MONTH (axis=0)

In [ ]:
avg_temp = temp.mean(axis=0)
months = ["January", "February", "March", "April"]
print("Average temperature of each MONTH:")
for month, avg in zip(months, avg_temp):
  print(f"{month}: {avg:.1f}")

Average temperature of each MONTH:
January: -6.0
February: -1.0
March: 7.7
April: 15.0


#Store sales

In [ ]:
sales = np.array([[50,   30,    20],
                  [45,   35,    25],
                  [55,   28,    22],
                  [48,   32,    18]])
print("Store sales:")
print(sales)

Store sales:
[[50 30 20]
 [45 35 25]
 [55 28 22]
 [48 32 18]]


Total sales of each PRODUCT (axis=0)

Total sales of each PRODUCT (axis=0)

In [ ]:
total_sales = sales.sum(axis=0)
print("Total sales of each PRODUCT:")
product = ["Tea", "Sugar", "Oil"]
for prod, total in zip(product, total_sales):
  print(f"{prod}: {total}")

Total sales of each PRODUCT:
Tea: 198
Sugar: 125
Oil: 85


Average sales of each PRODUCT (axis=0)

In [ ]:
avg_sales = sales.mean(axis=0)
market = ["Market1", "Market2", "Market3"]
print("Average sales of each PRODUCT:")
for market, avg in zip(market, avg_sales):
  print(f"{market}: {avg:.1f}")

Average sales of each PRODUCT:
Market1: 49.5
Market2: 31.2
Market3: 21.2


#Sports team

In [ ]:
points = np.array([[12,   15,    18],
                   [10,   12,    14],
                   [15,   18,    20],
                   [8,    10,    12],
                   [14,   16,    19]])
print("Sports team points:")
print(points)

Sports team points:
[[12 15 18]
 [10 12 14]
 [15 18 20]
 [ 8 10 12]
 [14 16 19]]


Total points per GAME (axis=0)

In [ ]:
total_points = points.sum(axis=0)
games = ["Game1", "Game2", "Game3"]
print("Total points per GAME:")
for game, total in zip(games, total_points):
  print(f"{game}: {total}")

Total points per GAME:
Game1: 59
Game2: 71
Game3: 83


Average points per GAME (axis=0)

In [ ]:
avg_points = points.mean(axis=0)
print("Average points per GAME:")
for game, avg in zip(games, avg_points):
  print(f"{game}: {avg:.1f}")

Average points per GAME:
Game1: 11.8
Game2: 14.2
Game3: 16.6


Which game scored the most points?

In [ ]:
max = points.max(axis=0)
print("Which game scored the most points?")
for game, max in zip(games, max):
  print(f"{game}: {max}")

Which game scored the most points?
Game1: 15
Game2: 18
Game3: 20
