<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/Axis%3D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

By ROW! →

In [ ]:
import numpy as np

#Adds each row (horizontal →)

In [ ]:
grades = np.array([[85, 90, 78, 92],
                   [88, 85, 82, 90],
                   [90, 88, 85, 95]])
print("All students grades:")
print(grades)

All students grades:
[[85 90 78 92]
 [88 85 82 90]
 [90 88 85 95]]


In [ ]:
total_per_student = grades.sum(axis=1)
students = ["Ali", "Vali", "Guli"]
for student, total in zip(students, total_per_student):
  print(f"{student}: {total}")

Ali: 345
Vali: 345
Guli: 358


## 💡 AXIS=0 vs AXIS=1
```
Array (3x4):
        U0   U1   U2   U3
    [[  10,  20,  30,  40],   ← Qator 0 → sum=100
     [  50,  60,  70,  80],   ← Qator 1 → sum=260
     [  90, 100, 110, 120]]   ← Qator 2 → sum=420
        ↓    ↓    ↓    ↓
axis=0:150  180  210  240

axis=1: [100, 260, 420]  ← Har bir qator

axis=0 → COLUMNS → VERTICAL ↓

axis=1 → ROWS → HORIZONTAL →

#Student evaluation 📚

In [ ]:
grades = np.array([[85, 90, 78, 92, 88],
                   [88, 85, 82, 90, 86],
                   [90, 88, 85, 95, 92],
                   [82, 80, 88, 85, 83]])

students = ['Ali', 'Vali', 'Guli', 'Diyor']

print("All students grades:")
print(grades)

All students grades:
[[85 90 78 92 88]
 [88 85 82 90 86]
 [90 88 85 95 92]
 [82 80 88 85 83]]


In [ ]:
student_avg = grades.mean(axis=1)

print("Student average:")
for student, avg in zip(students, student_avg):
  print(f"{student}: {avg}")

Student average:
Ali: 86.6
Vali: 86.2
Guli: 90.0
Diyor: 83.6


In [ ]:
print(f"{students[student_avg.argmax()]} has the best average with {student_avg.max()}")

Guli has the best average with 90.0


Monthly expenses 💰

In [ ]:
expenses = np.array([[500, 300, 150, 100, 80],
                     [600, 350, 200, 120, 100],
                     [450, 280, 130, 90, 70],
                     [550, 320, 180, 110, 90]])
families = ["Family 1", "Family 2", "Family 3", "Family 4"]

print("All expenses:")
print(expenses)

All expenses:
[[500 300 150 100  80]
 [600 350 200 120 100]
 [450 280 130  90  70]
 [550 320 180 110  90]]


In [ ]:
total_per_family = expenses.sum(axis=1)

print("Total expenses per family:")
for family, total in zip(families, total_per_family):
  print(f"{family}: {total}")

Total expenses per family:
Family 1: 1130
Family 2: 1370
Family 3: 1020
Family 4: 1250


In [ ]:
print(f"{families[total_per_family.argmax()]} has the most expenses with {total_per_family.max()}")
print(f"{families[total_per_family.argmin()]} has the least expenses with {total_per_family.min()}")

Family 2 has the most expenses with 1370
Family 3 has the least expenses with 1020


#Football team ⚽

In [ ]:
goals = np.array([[2,    3,     1,     2],
                  [1,    2,     2,     3],
                  [3,    1,     2,     1],
                  [1,    1,     1,     2],
                  [2,    2,     3,     2]])
players = ["Ronaldo", "Messi", "Neymar", "Mbappe", "Haaland"]

print("All players goals:")
print(goals)

All players goals:
[[2 3 1 2]
 [1 2 2 3]
 [3 1 2 1]
 [1 1 1 2]
 [2 2 3 2]]


In [ ]:
total_goals_per_player = goals.sum(axis=1)

print("Total goals per player:")
for player, total in zip(players, total_goals_per_player):
  print(f"{player}: {total}")

Total goals per player:
Ronaldo: 8
Messi: 8
Neymar: 7
Mbappe: 5
Haaland: 9


In [ ]:
top_scorer_idx = total_goals_per_player.argmax()
print(f"{players[top_scorer_idx]} has the most goals with {total_goals_per_player[top_scorer_idx]}")

Haaland has the most goals with 9


In [ ]:
avg_goals = goals.mean(axis=1)
print("Average goals per player:")
for player, avg in zip(players, avg_goals):
  print(f"{player}: {avg} goals/playing")

Average goals per player:
Ronaldo: 2.0
Messi: 2.0
Neymar: 1.75
Mbappe: 1.25
Haaland: 2.25


#Weekly working hours

In [ ]:
hours = np.array([[8,    9,    7,    8,    6],   # Aziz
                  [7,    8,    8,    9,    7],   # Botir
                  [9,    8,    8,    8,    8],   # Dilshod
                  [6,    7,    9,    7,    9]])  # Erkin

employees = ["Aziz", "Botir", "Dilshod", "Erkin"]

print("All employees hours:")
print(hours)

All employees hours:
[[8 9 7 8 6]
 [7 8 8 9 7]
 [9 8 8 8 8]
 [6 7 9 7 9]]


Total weekly hours per employee

In [ ]:
total_per_employee = hours.sum(axis=1)
for employee, total in zip(employees, total_per_employee):
  print(f"{employee}: {total} hours")

Aziz: 38 hours
Botir: 39 hours
Dilshod: 41 hours
Erkin: 38 hours


Average hours per day per employee

In [ ]:
avg_employee_per_day = hours.mean(axis=1)
for employee, avg in zip(employees, avg_employee_per_day):
  print(f"{employee}: {avg} hours/day")

Aziz: 7.6 hours/day
Botir: 7.8 hours/day
Dilshod: 8.2 hours/day
Erkin: 7.6 hours/day


In [ ]:
top_scorer_idx = total_per_employee.argmax()
print(f"{employees[top_scorer_idx]} has the most hours with {total_per_employee[top_scorer_idx]}")

Dilshod has the most hours with 41


#Store sales

In [ ]:
sales = np.array([[50,   30,    20],
                  [45,   35,    25],
                  [55,   28,    22],
                  [48,   32,    18],
                  [52,   33,    23]])
markets = ["Market 1", "Market 2", "Market 3", "Market 4", "Market 5"]

print("All markets sales:")
print(sales)

All markets sales:
[[50 30 20]
 [45 35 25]
 [55 28 22]
 [48 32 18]
 [52 33 23]]


Total sales of each STORE

In [ ]:
total_per_markets = sales.sum(axis=1)
for market, total in zip(markets, total_per_markets):
  print(f"{market}: {total}")

Market 1: 100
Market 2: 105
Market 3: 105
Market 4: 98
Market 5: 108


Average sales per STORE

In [ ]:
avg_per_markets = sales.mean(axis=1)
for market, avg in zip(markets, avg_per_markets):
  print(f"{market}: {avg:.2f}")

Market 1: 33.33
Market 2: 35.00
Market 3: 35.00
Market 4: 32.67
Market 5: 36.00


In [ ]:
top_idx = total_per_markets.argmax()
print(f"{markets[top_idx]} has the most sales with {total_per_markets[top_idx]}")

Market 5 has the most sales with 108


#Test results

In [ ]:
scores = np.array([[75,   80,    85,    90],   # Student 1
                   [85,   82,    88,    92],   # Student 2
                   [70,   75,    78,    82],   # Student 3
                   [90,   88,    92,    95],   # Student 4
                   [65,   70,    72,    75],   # Student 5
                   [88,   85,    90,    93]])  # Student 6
students = ["Student 1", "Student 2", "Student 3", "Student 4", "Student 5", "Student 6"]

print("All students scores:")
print(scores)

All students scores:
[[75 80 85 90]
 [85 82 88 92]
 [70 75 78 82]
 [90 88 92 95]
 [65 70 72 75]
 [88 85 90 93]]


Average score of each student

In [ ]:
avg_students = scores.mean(axis=1)
for student, avg in zip(students, avg_students):
  print(f"{student}: {avg:.2f}")

Student 1: 82.50
Student 2: 86.75
Student 3: 76.25
Student 4: 91.25
Student 5: 70.50
Student 6: 89.00


In [ ]:
top_idx = avg_students.argmax()
print(f"{students[top_idx]} has the best average with {avg_students[top_idx]}")

Student 4 has the best average with 91.25


In [ ]:
low_idx = avg_students.argmin()
print(f"{students[low_idx]} has the worst average with {avg_students[low_idx]}")

Student 5 has the worst average with 70.5
