<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/BOOLEAN_MASKING_ADVANCED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Multiple conditions - &, |, ~
np.logical_* - logical functions
np.isin() - membership testing
Boolean + Fancy combo - combined power
Counting Booleans - .sum() on masks

```
LOGICAL OPERATORS:

& - AND (ikkalasi ham True)
| - OR (kamida biri True)
~ - NOT (teskarisi)

In [ ]:
import numpy as np

# Multiple Conditions (&, |, ~)! 🎭

In [ ]:
scores = np.array([55, 72, 88, 45, 91, 67, 95, 52, 78, 85])
print("Student scores:")
print(scores)

Student scores:
[55 72 88 45 91 67 95 52 78 85]


 AND condition (&)

In [ ]:
print("Students with scores between 70 and 90:")
mask = (scores >= 70) & (scores <= 90)
result = scores[mask]
print(f"Mask: {mask}")
print(f"Scores:{result}")
print(f"Count: {mask.sum()}")

Students with scores between 70 and 90:
Mask: [False  True  True False False False False False  True  True]
Scores:[72 88 78 85]
Count: 4


OR condition (|)

In [ ]:
print("Students with score < 60 OR score > 90:")
mask = (scores < 60) | (scores > 90)
result = scores[mask]
print(f"Mask: {mask}")
print(f"Scores:{result}")
print(f"Count: {mask.sum()}")

Students with score < 60 OR score > 90:
Mask: [ True False False  True  True False  True  True False False]
Scores:[55 45 91 95 52]
Count: 5


NOT condition (~)

In [ ]:
print("Students who did NOT get exactly 72:")
mask = ~(scores == 72)
result = scores[mask]
print(f"Mask: {mask}")
print(f"Scores:{result}")
print(f"Count: {mask.sum()}")

Students who did NOT get exactly 72:
Mask: [ True False  True  True  True  True  True  True  True  True]
Scores:[55 88 45 91 67 95 52 78 85]
Count: 9


np.logical_ Functions! 🔧*

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print("Array:")
print(arr)

Array:
[10 20 30 40 50 60]


np.logical_and

In [ ]:
print("np.logical_and (20 < x < 50):")
mask = np.logical_and(arr > 20, arr < 50)
result = arr[mask]
print(f"Mask: {mask}")
print(f"Values:{result}")

np.logical_and (20 < x < 50):
Mask: [False False  True  True False False]
Values:[30 40]


np.logical_or

In [ ]:
print("np.logical_or (x < 25 OR > 45)")
mask = np.logical_or(arr < 25, arr > 45)
result = arr[mask]
print(f"Mask: {mask}")
print(f"Values:{result}")

np.logical_or (x < 25 OR > 45)
Mask: [ True  True False False  True  True]
Values:[10 20 50 60]


np.logical_not

In [ ]:
print("np.logical_not (x == 30):")
mask = np.logical_not(arr == 30)
result = arr[mask]
print(f"Mask: {mask}")
print(f"Values:{result}")

np.logical_not (x == 30):
Mask: [ True  True False  True  True  True]
Values:[10 20 40 50 60]


Multiple logical operations

In [ ]:
print("Complex: (x > 15 AND x < 45) OR x == 60:")
mask1 = np.logical_and(arr > 15, arr < 45)
mask2 = arr == 60
mask = np.logical_or(mask1, mask2)
result = arr[mask]
print(f"Mask1: {mask1}")
print(f"Mask2: {mask2}")
print(f"Mask: {mask}")
print(f"Values:{result}")

Complex: (x > 15 AND x < 45) OR x == 60:
Mask1: [False  True  True  True False False]
Mask2: [False False False False False  True]
Mask: [False  True  True  True False  True]
Values:[20 30 40 60]


#np.isin() - Membership! 🔍

Student IDs

In [ ]:
all_students = np.array([101, 102, 103, 104, 105, 106, 107, 108])
print("All student IDs:")
print(all_students)

All student IDs:
[101 102 103 104 105 106 107 108]


Present students

In [ ]:
present = [102, 104, 106, 108]
print(f"Present students: {present}")

Present students: [102, 104, 106, 108]


Check who is present

In [ ]:
mask = np.isin(all_students, present)
present_ids = all_students[mask]
print(f"Present mask: {mask}")
print(f"Present IDs: {present_ids}")
print(f"Present count: {mask.sum()}")

Present mask: [False  True False  True False  True False  True]
Present IDs: [102 104 106 108]
Present count: 4


Check who is absent (NOT present)

In [ ]:
absent_mask = ~np.isin(all_students, present)
absent_ids = all_students[absent_mask]
print(f"Absent mask: {absent_mask}")
print(f"Absent IDs: {absent_ids}")
print(f"Absent count: {absent_mask.sum()}")

Absent mask: [ True False  True False  True False  True False]
Absent IDs: [101 103 105 107]
Absent count: 4


#Boolean + Fancy Combo! 🚀

In [ ]:
products = np.array(['Laptop', 'Phone', 'Tablet', 'Monitor',
                     'Keyboard', 'Mouse', 'Headset'], dtype=str)
prices = np.array([1200, 800, 500, 300, 150, 50, 200])

print("Products and prices:")
for product, price in zip(products, prices):
  print(f"{product}: ${price}")

Products and prices:
Laptop: $1200
Phone: $800
Tablet: $500
Monitor: $300
Keyboard: $150
Mouse: $50
Headset: $200


Find expensive items (price > 400)

In [ ]:
expensive_mask = prices > 400
print(f"Expensive mask: {expensive_mask}")

Expensive mask: [ True  True  True False False False False]


Get indices of expensive items

In [ ]:
expensive_indices = np.where(expensive_mask)[0]
print(f"Expensive indices: {expensive_indices}")

Expensive indices: [0 1 2]


Select expensive products and prices

In [ ]:
expensive_products = products[expensive_mask]
expensive_prices = prices[expensive_mask]
print("Expensive items:")
for product, price in zip(expensive_products, expensive_prices):
  print(f"{product}: ${price}")

Expensive items:
Laptop: $1200
Phone: $800
Tablet: $500


Apply 10% discount using indices

In [ ]:
discount_prices = prices.copy()
discount_prices[expensive_indices] = discount_prices[expensive_indices] * 0.9
print("After 10% discount on expensive items:")
for product, price in zip(products, discount_prices):
  print(f"{product}: ${price:.2f}")

After 10% discount on expensive items:
Laptop: $1080.00
Phone: $720.00
Tablet: $450.00
Monitor: $300.00
Keyboard: $150.00
Mouse: $50.00
Headset: $200.00


#Grade Classification

In [ ]:
grades = np.array([45, 78, 92, 65, 88, 52, 95, 71, 84, 58])
print("Student grades:")
print(grades)

Student grades:
[45 78 92 65 88 52 95 71 84 58]


In [ ]:
mask = grades >= 90
result = grades[mask]
print(f"Mask: {mask}")
print(f"A Grades:{result}")
print(f"Count A grades: {mask.sum()}")

Mask: [False False  True False False False  True False False False]
A Grades:[92 95]
Count A grades: 2


In [ ]:
mask = (grades >= 80) & (grades < 90)
result = grades[mask]
print(f"Mask: {mask}")
print(f"B Grades:{result}")
print(f"Count B grades: {mask.sum()}")

Mask: [False False False False  True False False False  True False]
B Grades:[88 84]
Count B grades: 2


In [ ]:
mask = (grades >= 70) & (grades < 80)
result = grades[mask]
print(f"Mask: {mask}")
print(f"C Grades:{result}")
print(f"Count C grades: {mask.sum()}")

Mask: [False  True False False False False False  True False False]
C Grades:[78 71]
Count C grades: 2


In [ ]:
mask = (grades >= 60) & (grades < 70)
result = grades[mask]
print(f"Mask: {mask}")
print(f"D Grades:{result}")
print(f"Count D grades: {mask.sum()}")

Mask: [False False False  True False False False False False False]
D Grades:[65]
Count D grades: 1


In [ ]:
mask = grades < 60
result = grades[mask]
print(f"Mask: {mask}")
print(f"F Grades:{result}")
print(f"Count F grades: {mask.sum()}")

Mask: [ True False False False False  True False False False  True]
F Grades:[45 52 58]
Count F grades: 3


#Temperature Filter

In [ ]:
temperature = np.array([18, 25, 22, 30, 28, 15, 20])
print("Weekly temperatures:")
print(temperature)

Weekly temperatures:
[18 25 22 30 28 15 20]


In [ ]:
mask = (temperature >= 20) & (temperature < 28)
comfortable = temperature[mask]
print(f"Mask: {mask}")
print(f"Comfortable temperatures:{comfortable}")
print(f"Count comfortable temperature: {mask.sum()}")
print(f"Average comfortable day: {comfortable.mean():.1f}")

Mask: [False  True  True False False False  True]
Comfortable temperatures:[25 22 20]
Count comfortable temperature: 3
Average comfortable day: 22.3


In [ ]:
mask = (temperature < 20) | (temperature > 27)
uncomfortable = temperature[mask]
print(f"Mask: {mask}")
print(f"Uncomfortable temperatures:{uncomfortable}")
print(f"Count uncomfortable temperature: {mask.sum()}")

Mask: [ True False False  True  True  True False]
Uncomfortable temperatures:[18 30 28 15]
Count uncomfortable temperature: 4


#Product Inventory

In [ ]:
products = np.array(['Apple', 'Banana', 'Orange', 'Grape', 'Mango'])
stocks = np.array([50, 0, 30, 0, 20])
prices = np.array([2.5, 1.5, 3.0, 4.0, 3.5])

print("Market")
for product, price, stock in zip(products, prices, stocks):
  print(f"{product}-- Price: ${price:.2f}, Stock: {stock}")

Market
Apple-- Price: $2.50, Stock: 50
Banana-- Price: $1.50, Stock: 0
Orange-- Price: $3.00, Stock: 30
Grape-- Price: $4.00, Stock: 0
Mango-- Price: $3.50, Stock: 20


In [ ]:
stock = 0
mask = np.isin(stocks, stock)
empty_stocks = products[mask]
print(f"Mask: {mask}")
print(f"Empty stocks products:{empty_stocks}")

Mask: [False  True False  True False]
Empty stocks products:['Banana' 'Grape']


In [ ]:
mask = prices > 2.5
expensive = products[mask]
print(f"Mask: {mask}")
print(f"Expensive products:{expensive}")

Mask: [False False  True  True  True]
Expensive products:['Orange' 'Grape' 'Mango']


In [ ]:
for product, price, stock in zip(expensive, prices[mask], stocks[mask]):
  print(f"{product}-- Price: ${price:.2f}, Stock: {stock}")

Orange-- Price: $3.00, Stock: 30
Grape-- Price: $4.00, Stock: 0
Mango-- Price: $3.50, Stock: 20
