<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/BOOLEAN_INDEXING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [3]:
mask = arr > 25
print(mask)

[False False  True  True  True]


In [4]:
result = arr[mask]
print(result)

[30 40 50]


```arr = [10, 20, 30, 40, 50]
      
# Step 1: Comparison → Boolean array
arr > 25
→ [False, False, True, True, True]

# Step 2: Use as mask
arr[[False, False, True, True, True]]
      ↓     ↓     ↓     ↓     ↓
     skip  skip  take  take  take

# Step 3: Result
→ [30, 40, 50]
```

In [5]:
result = arr[arr > 25]
print(result)

[30 40 50]


#Basic Boolean Indexing

In [6]:
arr = np.array([1, 5, 3, 8, 2, 9, 4, 7, 6])
print("Original array:")
print(arr)

Original array:
[1 5 3 8 2 9 4 7 6]


In [7]:
mask = arr > 5
print("Boolean mask (arr > 5):")
print(mask)

Boolean mask (arr > 5):
[False False False  True False  True False  True  True]


In [8]:
result = arr[mask]
print("Filtered array (arr[arr > 5]):")
print(result)

Filtered array (arr[arr > 5]):
[8 9 7 6]


ONE-LINER (most common way!)

In [9]:
result_oneliner = arr[arr > 5]
print("One-liner result:")
print(result_oneliner)

One-liner result:
[8 9 7 6]


Different conditions

In [10]:
print("arr < 4:", arr[arr < 4])
print("arr == 5:", arr[arr == 5])
print("arr != 3:", arr[arr != 3])
print("arr >= 7:", arr[arr >= 7])

arr < 4: [1 3 2]
arr == 5: [5]
arr != 3: [1 5 8 2 9 4 7 6]
arr >= 7: [8 9 7]


#Multiple Conditions (AND, OR, NOT)

In [11]:
result = arr[(arr > 3) & (arr < 8)]
print("Filtered array (arr[(arr > 3) & (arr < 8)]):")
print(result)

Filtered array (arr[(arr > 3) & (arr < 8)]):
[5 4 7 6]


In [12]:
result = arr[(arr < 3) | (arr > 8)]
print("Filtered array (arr[(arr < 3) | (arr > 8)]):")
print(result)

Filtered array (arr[(arr < 3) | (arr > 8)]):
[1 2 9]


NOT (~) - Inverted

In [13]:
mask = arr > 5
result = arr[~mask]
print("Filtered array (arr[~arr > 5]):")
print(result)

Filtered array (arr[~arr > 5]):
[1 5 3 2 4]


```& = AND (not Python and!)
| = OR (not Python or!)
~ = NOT (not Python not!)
() parentheses are required for each condition! ⚠️```

In [14]:
result = arr[((arr > 3) & (arr < 8)) | (arr == 9)]
print("Filtered array (arr[((arr > 3) & (arr < 8)) | (arr == 9)]):")
print(result)

Filtered array (arr[((arr > 3) & (arr < 8)) | (arr == 9)]):
[5 9 4 7 6]


#Modifying Values

SET TO VALUE

In [15]:
arr_copy = arr.copy()
arr_copy[arr_copy > 5] = 0
print("Set > 5 to 0):")
print(arr_copy)

Set > 5 to 0):
[1 5 3 0 2 0 4 0 0]


In [16]:
arr_copy = arr.copy()
arr_copy[arr_copy < 5] += 10
print("Add 10 to < 5):")
print(arr_copy)

Add 10 to < 5):
[11  5 13  8 12  9 14  7  6]


CLIP (limit to range)

In [17]:
arr_copy = arr.copy()
arr_copy[arr_copy > 7] = 7
arr_copy[arr_copy < 3] = 3
print("Clip to [3, 7]:", arr_copy)

Clip to [3, 7]: [3 5 3 7 3 7 4 7 6]


Using np.clip (better!)

In [18]:
arr_copy = arr.copy()
arr_copy = np.clip(arr_copy, 3, 7)
print("Clip to [3, 7]:", arr_copy)

Clip to [3, 7]: [3 5 3 7 3 7 4 7 6]


#2D Boolean Indexing

In [19]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Original matrix:")
print(matrix)

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Boolean mask for 2D


In [20]:
mask = matrix > 6
print("Mask (matrix > 6):")
print(mask)

Mask (matrix > 6):
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


Result is 1D! (flattened)

In [21]:
result = matrix[mask]
print("Filtered matrix (matrix[matrix > 6]):")
print(result)

Filtered matrix (matrix[matrix > 6]):
[ 7  8  9 10 11 12]


 Modify in place

In [22]:
matrix_copy = matrix.copy()
matrix_copy[matrix_copy > 6] = 0
print("Set > 6 to 0):")
print(matrix_copy)

Set > 6 to 0):
[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


Keep 2D structure with np.where

In [23]:
result_2d = np.where(matrix > 6, matrix, 0)
print("Result using np.where:")
print(result_2d)

Result using np.where:
[[ 0  0  0  0]
 [ 0  0  7  8]
 [ 9 10 11 12]]


#Image Thresholding

In [24]:
img = np.random.randint(0, 256, size=(10, 10), dtype=np.uint8)
print("Original image:")
print(img)

Original image:
[[152  82  99  80 198 102 129  71 162 245]
 [232 138 109 233 106 196 228  88   6  15]
 [233 236 252  58   8 133 224 118 119  14]
 [141  20  68 125  68 142 243  59 187  80]
 [159 172   9  29  84 208  63 190 144  46]
 [174  80   8 172 223 141 234 236 144 255]
 [  6 191  33  85  99  34  69 209  21  95]
 [233 221 104  62 224 153 170  30 169  60]
 [195  13 254 142  50 146  68 193 170 218]
 [211 181  65 219  27 171 108  26  55  52]]


 BINARY THRESHOLD

 Pixels > 127 → 255 (white)

 Pixels <= 127 → 0 (black)

In [25]:
threshold = 127
binary = np.where(img > threshold, 255, 0).astype(np.uint8)
print("Binary image (threshold = 127):")
print(binary)

Binary image (threshold = 127):
[[255   0   0   0 255   0 255   0 255 255]
 [255 255   0 255   0 255 255   0   0   0]
 [255 255 255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255 255   0 255   0]
 [255 255   0   0   0 255   0 255 255   0]
 [255   0   0 255 255 255 255 255 255 255]
 [  0 255   0   0   0   0   0 255   0   0]
 [255 255   0   0 255 255 255   0 255   0]
 [255   0 255 255   0 255   0 255 255 255]
 [255 255   0 255   0 255   0   0   0   0]]


Boolean indexing

In [26]:
binary_bool = np.zeros_like(img)
binary_bool[img > threshold] = 255
print("Binary image (threshold = 127):")
print(binary_bool)

Binary image (threshold = 127):
[[255   0   0   0 255   0 255   0 255 255]
 [255 255   0 255   0 255 255   0   0   0]
 [255 255 255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255 255   0 255   0]
 [255 255   0   0   0 255   0 255 255   0]
 [255   0   0 255 255 255 255 255 255 255]
 [  0 255   0   0   0   0   0 255   0   0]
 [255 255   0   0 255 255 255   0 255   0]
 [255   0 255 255   0 255   0 255 255 255]
 [255 255   0 255   0 255   0   0   0   0]]


RANGE THRESHOLD (keep middle values)

In [27]:
low, high = 100, 200
range_threshold = img.copy()
range_threshold[img < low] = 0
range_threshold[img > high] = 255
print(f"Range threshold ({low}, {high}):")
print(range_threshold)

Range threshold (100, 200):
[[152   0   0   0 198 102 129   0 162 255]
 [255 138 109 255 106 196 255   0   0   0]
 [255 255 255   0   0 133 255 118 119   0]
 [141   0   0 125   0 142 255   0 187   0]
 [159 172   0   0   0 255   0 190 144   0]
 [174   0   0 172 255 141 255 255 144 255]
 [  0 191   0   0   0   0   0 255   0   0]
 [255 255 104   0 255 153 170   0 169   0]
 [195   0 255 142   0 146   0 193 170 255]
 [255 181   0 255   0 171 108   0   0   0]]


# Color Filtering (RGB)

In [28]:
img = np.random.randint(0, 256, (5, 5, 3), dtype=np.uint8)
print("Original image:")
print(img)

Original image:
[[[128  67 172]
  [138  13  54]
  [250 139  26]
  [243 253 245]
  [137 159  60]]

 [[ 72 209 158]
  [225  95  72]
  [255  44   7]
  [ 48 125 144]
  [166 180 150]]

 [[ 81 245   8]
  [248 210  52]
  [ 44 205 180]
  [216 155 210]
  [ 34  43 208]]

 [[118 118 244]
  [244 113  71]
  [ 87 200 208]
  [218  91 212]
  [ 64 146 197]]

 [[ 80 243 132]
  [ 54 232  29]
  [ 86  37 119]
  [198 177 130]
  [ 95 226  92]]]


FIND RED PIXELS

Red > 200, Green < 100, Blue < 100

In [29]:
red_mask = (img[:, :, 0] > 200 & (img[:, :, 1] < 100) & (img[:, :, 2] < 100))
print("Red mask:")
print(red_mask)

Red mask:
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [30]:
img_filtered = img.copy()
img_filtered[red_mask] = [255, 0, 0]

print("Filtered image (red pixels → pure red)")
print(f"Modified pixels: {np.sum(red_mask)}")
print(img_filtered)

Filtered image (red pixels → pure red)
Modified pixels: 25
[[[255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]]


FIND GREEN AREA

In [31]:
green_mask = img[:, :, 1] > 150
print(f"Green pixels: {green_mask.sum()}")

Green pixels: 13


EMOVE DARK PIXELS

In [32]:
dark_mask = img.mean(axis=2) < 50
img_copy = img.copy()
img_copy[dark_mask] = [0, 0, 0]
print(f"Dark pixels removed: {dark_mask.sum()}")

Dark pixels removed: 0


#Data Cleaning

Dataset with outliers

In [33]:
data = np.array([23, 25, 24, 26, 100, 22, 24, 23, -5, 25, 27])
print("Original data:")
print(data)

Original data:
[ 23  25  24  26 100  22  24  23  -5  25  27]


DETECT OUTLIERS

In [34]:
mean = data.mean()
std = data.std()
print(f"Mean: {mean:.2f}, Standard Deviation: {std:.2f}")

Mean: 28.55, Standard Deviation: 24.14


Outliers: > 2 standard deviations from mean


In [35]:
outlier_mask = np.abs(data - mean) > std
print("Outlier mask:")
print(outlier_mask)

Outlier mask:
[False False False False  True False False False  True False False]


In [36]:
print("Outliers:")
print(data[outlier_mask])

Outliers:
[100  -5]


REMOVE OUTLIERS

In [37]:
clean_data = data[~outlier_mask]
print("Cleaned data:")
print(clean_data)

Cleaned data:
[23 25 24 26 22 24 23 25 27]


In [38]:
data_replaced = data.copy()
data_replaced[outlier_mask] = mean
print("Outliers replaced with mean:")
print(data_replaced)

Outliers replaced with mean:
[23 25 24 26 28 22 24 23 28 25 27]


#Data Cleaning

Dataset with outliers

In [39]:
data = np.array([23, 25, 24, 26, 100, 22, 24, 23, -5, 25, 27])
print("Original data:")
print(data)

Original data:
[ 23  25  24  26 100  22  24  23  -5  25  27]


DETECT OUTLIERS

In [40]:
mean = data.mean()
std = data.std()
print(f"Mean: {mean:.2f}, Standard Deviation: {std:.2f}")

Mean: 28.55, Standard Deviation: 24.14


Outliers: > 2 standard deviations from mean


In [41]:
outlier_mask = np.abs(data - mean) > 2 * std
print("Outlier mask:")
print(outlier_mask)

Outlier mask:
[False False False False  True False False False False False False]


In [42]:
print("Outliers:")
print(data[outlier_mask])

Outliers:
[100]


REMOVE OUTLIERS

In [43]:
clean_data = data[~outlier_mask]
print("Cleaned data:")
print(clean_data)

Cleaned data:
[23 25 24 26 22 24 23 -5 25 27]


In [44]:
data_replaced = data.copy()
data_replaced[outlier_mask] = mean
print("Outliers replaced with mean:")
print(data_replaced)

Outliers replaced with mean:
[23 25 24 26 28 22 24 23 -5 25 27]


#Data Cleaning

Dataset with outliers

In [45]:
data = np.array([23, 25, 24, 26, 100, 22, 24, 23, -5, 25, 27])
print("Original data:")
print(data)

Original data:
[ 23  25  24  26 100  22  24  23  -5  25  27]


DETECT OUTLIERS

In [46]:
mean = data.mean()
std = data.std()
print(f"Mean: {mean:.2f}, Standard Deviation: {std:.2f}")

Mean: 28.55, Standard Deviation: 24.14


Outliers: > 2 standard deviations from mean


In [47]:
outlier_mask = np.abs(data - mean) > 2 * std
print("Outlier mask:")
print(outlier_mask)

Outlier mask:
[False False False False  True False False False False False False]


In [48]:
print("Outliers:")
print(data[outlier_mask])

Outliers:
[100]


REMOVE OUTLIERS

In [49]:
clean_data = data[~outlier_mask]
print("Cleaned data:")
print(clean_data)

Cleaned data:
[23 25 24 26 22 24 23 -5 25 27]


In [50]:
data_replaced = data.copy()
data_replaced[outlier_mask] = mean
print("Outliers replaced with mean:")
print(data_replaced)

Outliers replaced with mean:
[23 25 24 26 28 22 24 23 -5 25 27]


#np.where() - COnditional Slelection

In [51]:
print(arr)

[1 5 3 8 2 9 4 7 6]


In [52]:
result = np.where(arr > 5, "BIG", "SMALL")
print("np.where(arr > 5, 'BIG', 'SMALL):")
print(result)

np.where(arr > 5, 'BIG', 'SMALL):
['SMALL' 'SMALL' 'SMALL' 'BIG' 'SMALL' 'BIG' 'SMALL' 'BIG' 'BIG']


With numbers

In [53]:
result = np.where(arr > 5, arr, 0)
print("np.where(arr > 5, arr, 0):")
print(result)

np.where(arr > 5, arr, 0):
[0 0 0 8 0 9 0 7 6]


In [54]:
result = np.where(arr < 3, 'SMALL', np.where(arr < 7, 'MEDIUM', 'LARGE'))
print("np.where(arr < 3, 'SMALL', np.where(arr < 7, 'MEDIUM', 'LARGE')):")
print(result)

np.where(arr < 3, 'SMALL', np.where(arr < 7, 'MEDIUM', 'LARGE')):
['SMALL' 'MEDIUM' 'MEDIUM' 'LARGE' 'SMALL' 'LARGE' 'MEDIUM' 'LARGE'
 'MEDIUM']


np.where for indices

In [55]:
index = np.where(arr > 5)
print("np.where(arr > 5) - indices:")
print(index)

np.where(arr > 5) - indices:
(array([3, 5, 7, 8]),)


In [56]:
print("Values at indices:")
print(arr[index])

Values at indices:
[8 9 7 6]


#Practice

##BASIC BOOLEAN INDEXING

In [57]:
arr = np.array([12, 5, 8, 15, 3, 20, 7, 18, 2, 10])
print("Array:")
print(arr)

Array:
[12  5  8 15  3 20  7 18  2 10]


In [58]:
result = arr[arr > 10]
print("Values > 10:")
print(result)

Values > 10:
[12 15 20 18]


In [59]:
result = arr[arr < 6]
print("Values < 6")
print(result)

Values < 6
[5 3 2]


In [60]:
result = arr[arr == 15]
print("Values == 15")

Values == 15


##MULTIPLE CONDITIONS


In [61]:
result = arr[(arr > 5) & (arr < 15)]
print("Values > 5 and < 15:")
print(result)

Values > 5 and < 15:
[12  8  7 10]


In [62]:
result = arr[(arr < 5) | (arr > 15)]
print("Values > 5 or > 15:")
print(result)

Values > 5 or > 15:
[ 3 20 18  2]


In [63]:
result = arr[~(arr > 10)]
print("Values <= 10:")
print(result)

Values <= 10:
[ 5  8  3  7  2 10]


##MODIFYING VALUES

In [64]:
arr_copy = arr.copy()
arr_copy[arr > 15] = 0
print("Set > 15 to 0:")
print(arr_copy)

Set > 15 to 0:
[12  5  8 15  3  0  7  0  2 10]


In [65]:
arr_copy = arr.copy()
arr_copy[arr < 5] += 100
print("Add 100 to < 5:")
print(arr_copy)

Add 100 to < 5:
[ 12   5   8  15 103  20   7  18 102  10]


In [66]:
result = np.clip(arr, 5, 15)
print("Clip to [5, 15]:")
print(result)

Clip to [5, 15]:
[12  5  8 15  5 15  7 15  5 10]


In [67]:
arr_copy = arr.copy()
arr_copy[arr_copy > 15] = 15
arr_copy[arr_copy < 5] = 5
print("Array clipped to [5, 15]:")
print(arr_copy)

Array clipped to [5, 15]:
[12  5  8 15  5 15  7 15  5 10]


##2D ARRAY

In [68]:
matrix = np.array([[10, 20, 30],
                   [5, 15, 25],
                   [12, 8, 28]])

In [69]:
result = matrix[matrix > 15]
print("Result of matrix > 15:")
print(result)

Result of matrix > 15:
[20 30 25 28]


In [70]:
matrix_copy = matrix.copy()
matrix_copy[matrix_copy < 10] = 0
print("Matrix with values < 10 set to 0:")
print(matrix_copy)

Matrix with values < 10 set to 0:
[[10 20 30]
 [ 0 15 25]
 [12  0 28]]


##IMAGE THRESHOLDING

In [71]:
img = np.random.randint(0, 256, (20, 20), dtype=np.uint8)
print("Original image:")
print(img)

Original image:
[[131 177  59 208  58 121 124 209 161  91 235 161  13 102  33 233  71 116
  178 166]
 [ 25 156  67 208 125  19  62 140  62  43  28 155  83 170 202 214 211 157
  190 223]
 [ 15 246 219   8 139 227 120  42  56 189 246 161 145 244 163 108  98 173
  117 161]
 [ 97  90 101 241  35  90 137 247 144 224  31 220  82 180 132  58   7 138
   27 167]
 [ 90 225  67 119 179 121 185  96 149 233 120 244 121  77  53 165  60 251
  143 222]
 [243 233 242 116 232  43 129  67 157 224 172 206 219 102  18  23 195 114
  244  55]
 [109  17  45 105 210  75 250 192 244  82 247 231 230 166 131 255  45 133
   72 236]
 [ 66  34  75 196 101 191  92  16 218 182  43 124  62 127  88  25  86  28
  127 170]
 [150 161 240 252  86 223  77  98 204 144 138 175  17 115 173 237 227  39
  189 139]
 [113 211  13 178  52  16 144 229 217  99  19 112 203  94 239  93 106 114
  231 125]
 [132 247 227 222  91 254  47 138 235  47 132  29 228  72  93 155  27  22
  246 204]
 [116 236 250 102 113 211 204 255 253 177 180  83

In [72]:
threshold_img = img.copy()
threshold_img[threshold_img < 128] = 0
threshold_img[threshold_img >= 128] = 255
print("Binary image (threshold = 128):")
print(threshold_img)

Binary image (threshold = 128):
[[255 255   0 255   0   0   0 255 255   0 255 255   0   0   0 255   0   0
  255 255]
 [  0 255   0 255   0   0   0 255   0   0   0 255   0 255 255 255 255 255
  255 255]
 [  0 255 255   0 255 255   0   0   0 255 255 255 255 255 255   0   0 255
    0 255]
 [  0   0   0 255   0   0 255 255 255 255   0 255   0 255 255   0   0 255
    0 255]
 [  0 255   0   0 255   0 255   0 255 255   0 255   0   0   0 255   0 255
  255 255]
 [255 255 255   0 255   0 255   0 255 255 255 255 255   0   0   0 255   0
  255   0]
 [  0   0   0   0 255   0 255 255 255   0 255 255 255 255 255 255   0 255
    0 255]
 [  0   0   0 255   0 255   0   0 255 255   0   0   0   0   0   0   0   0
    0 255]
 [255 255 255 255   0 255   0   0 255 255 255 255   0   0 255 255 255   0
  255 255]
 [  0 255   0 255   0   0 255 255 255   0   0   0 255   0 255   0   0   0
  255   0]
 [255 255 255 255   0 255   0 255 255   0 255   0 255   0   0 255   0   0
  255 255]
 [  0 255 255   0   0 255 255 255

In [73]:
threshold_img = np.where(img < 127, 0, 255)
print("Binary image (threshold = 127):")
print(threshold_img)

Binary image (threshold = 127):
[[255 255   0 255   0   0   0 255 255   0 255 255   0   0   0 255   0   0
  255 255]
 [  0 255   0 255   0   0   0 255   0   0   0 255   0 255 255 255 255 255
  255 255]
 [  0 255 255   0 255 255   0   0   0 255 255 255 255 255 255   0   0 255
    0 255]
 [  0   0   0 255   0   0 255 255 255 255   0 255   0 255 255   0   0 255
    0 255]
 [  0 255   0   0 255   0 255   0 255 255   0 255   0   0   0 255   0 255
  255 255]
 [255 255 255   0 255   0 255   0 255 255 255 255 255   0   0   0 255   0
  255   0]
 [  0   0   0   0 255   0 255 255 255   0 255 255 255 255 255 255   0 255
    0 255]
 [  0   0   0 255   0 255   0   0 255 255   0   0   0 255   0   0   0   0
  255 255]
 [255 255 255 255   0 255   0   0 255 255 255 255   0   0 255 255 255   0
  255 255]
 [  0 255   0 255   0   0 255 255 255   0   0   0 255   0 255   0   0   0
  255   0]
 [255 255 255 255   0 255   0 255 255   0 255   0 255   0   0 255   0   0
  255 255]
 [  0 255 255   0   0 255 255 255

In [74]:
threshold_img = img.copy()
threshold_img[threshold_img < 100] = 0
threshold_img[threshold_img > 200] = 0
print("Range threshold (100, 200):")
print(threshold_img)

Range threshold (100, 200):
[[131 177   0   0   0 121 124   0 161   0   0 161   0 102   0   0   0 116
  178 166]
 [  0 156   0   0 125   0   0 140   0   0   0 155   0 170   0   0   0 157
  190   0]
 [  0   0   0   0 139   0 120   0   0 189   0 161 145   0 163 108   0 173
  117 161]
 [  0   0 101   0   0   0 137   0 144   0   0   0   0 180 132   0   0 138
    0 167]
 [  0   0   0 119 179 121 185   0 149   0 120   0 121   0   0 165   0   0
  143   0]
 [  0   0   0 116   0   0 129   0 157   0 172   0   0 102   0   0 195 114
    0   0]
 [109   0   0 105   0   0   0 192   0   0   0   0   0 166 131   0   0 133
    0   0]
 [  0   0   0 196 101 191   0   0   0 182   0 124   0 127   0   0   0   0
  127 170]
 [150 161   0   0   0   0   0   0   0 144 138 175   0 115 173   0   0   0
  189 139]
 [113   0   0 178   0   0 144   0   0   0   0 112   0   0   0   0 106 114
    0 125]
 [132   0   0   0   0   0   0 138   0   0 132   0   0   0   0 155   0   0
    0   0]
 [116   0   0 102 113   0   0   0   0

In [75]:
threshold_img = np.where(img < 100, 0, np.where(img > 200, 0, img))
print("Range threshold (100, 200):")
print(threshold_img)

Range threshold (100, 200):
[[131 177   0   0   0 121 124   0 161   0   0 161   0 102   0   0   0 116
  178 166]
 [  0 156   0   0 125   0   0 140   0   0   0 155   0 170   0   0   0 157
  190   0]
 [  0   0   0   0 139   0 120   0   0 189   0 161 145   0 163 108   0 173
  117 161]
 [  0   0 101   0   0   0 137   0 144   0   0   0   0 180 132   0   0 138
    0 167]
 [  0   0   0 119 179 121 185   0 149   0 120   0 121   0   0 165   0   0
  143   0]
 [  0   0   0 116   0   0 129   0 157   0 172   0   0 102   0   0 195 114
    0   0]
 [109   0   0 105   0   0   0 192   0   0   0   0   0 166 131   0   0 133
    0   0]
 [  0   0   0 196 101 191   0   0   0 182   0 124   0 127   0   0   0   0
  127 170]
 [150 161   0   0   0   0   0   0   0 144 138 175   0 115 173   0   0   0
  189 139]
 [113   0   0 178   0   0 144   0   0   0   0 112   0   0   0   0 106 114
    0 125]
 [132   0   0   0   0   0   0 138   0   0 132   0   0   0   0 155   0   0
    0   0]
 [116   0   0 102 113   0   0   0   0

##COLOR FILTERING

In [76]:
rgb_img = np.random.randint(0, 256, (10, 10, 3), dtype=np.uint8)
print("Original RGB image:")
print(rgb_img)

Original RGB image:
[[[142  26  17]
  [183 251 216]
  [250  32 108]
  [ 19  53 137]
  [187 243 244]
  [155   3 153]
  [228 241 242]
  [101  43 225]
  [137 196  57]
  [ 39  51 133]]

 [[ 11  66 238]
  [150 248  52]
  [105 174  33]
  [163 240  22]
  [ 78 213 139]
  [200 120 141]
  [255 120 147]
  [128 247 115]
  [ 85 206 138]
  [ 10  12 173]]

 [[170 223  93]
  [228 238 235]
  [246 206 130]
  [186  16 182]
  [157 163 237]
  [115 251 184]
  [155  26  78]
  [ 61 102 195]
  [ 85  87  81]
  [ 13  93  23]]

 [[140 119  62]
  [192 150  17]
  [  7 240 173]
  [133 232  43]
  [235  73 175]
  [139  58 206]
  [ 43 215 156]
  [244  11 246]
  [195 170 194]
  [108 115  37]]

 [[242 110  61]
  [244  14 255]
  [223  58 135]
  [148  27  15]
  [144  15  57]
  [231  70 222]
  [235 198 218]
  [184  43  23]
  [153  85  69]
  [161  61  95]]

 [[255   7 155]
  [153 169 167]
  [ 74 195  10]
  [ 92  17 134]
  [232  12  99]
  [121  89 251]
  [107 120 219]
  [ 14 133  35]
  [209 107  58]
  [209 244  28]]

 [[ 85 1

In [77]:
red_mask = rgb_img[:, :, 0] > 200
print("Red mask:")
print(red_mask)

Red mask:
[[False False  True False False False  True False False False]
 [False False False False False False  True False False False]
 [False  True  True False False False False False False False]
 [False False False False  True False False  True False False]
 [ True  True  True False False  True  True False False False]
 [ True False False False  True False False False  True  True]
 [False False False False False False False False  True False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True False  True False False  True False False False]]


In [78]:
dark_mask = rgb_img.mean(axis=2) < 30
img_copy = rgb_img.copy()
img_copy[dark_mask] = [0, 0, 0]
print("Dark pixels removed:")
print(dark_mask.sum())

Dark pixels removed:
0


##NP.WHERE

In [79]:
arr = np.array([1, 5, 3, 8, 2, 9, 4, 7, 6])
print("Array:")
print(arr)

Array:
[1 5 3 8 2 9 4 7 6]


In [80]:
result = np.where(arr > 5, "HIGH", "LOW")
print("np.where(arr > 5, 'HIGH', 'LOW'):")
print(result)

np.where(arr > 5, 'HIGH', 'LOW'):
['LOW' 'LOW' 'LOW' 'HIGH' 'LOW' 'HIGH' 'LOW' 'HIGH' 'HIGH']


In [81]:
result= np.where(arr > 5, arr * 2, arr)
print("np.where(arr > 5, arr * 2, arr):")
print(result)

np.where(arr > 5, arr * 2, arr):
[ 1  5  3 16  2 18  4 14 12]


##BONUS

Outlier detection

 Find values > mean + 2*std OR < mean - 2*std


In [82]:
data = np.array([10, 12, 11, 100, 13, 12, -5, 11, 12, 13])
mean = data.mean()
std = data.std()
outliers = data[(data > mean + 2 * std) | (data < mean -2 * std)]
print("Outliers:")
print(outliers)

Outliers:
[100]


Chess move validation

 Given 8x8 board, find valid knight moves from position (3, 3)

 Knight moves: ±2 horizontal & ±1 vertical, or ±1 horizontal & ±2 vertical

In [83]:
# 8x8 shaxmat taxtasi
board = np.zeros((8, 8), dtype=int)
start_pos = (3, 3)  # Knight pozitsiyasi
start_row, start_col = start_pos

print(f"Knight position: {start_pos}")
print()
print("="*60)
print("METHOD 2: Boolean Indexing")
print("="*60)
print()

# Create coordinate grids
rows = np.arange(8).reshape(8, 1)  # (8, 1)
cols = np.arange(8).reshape(1, 8)  # (1, 8)

# Broadcasting to create (8, 8) grids
row_grid, col_grid = np.meshgrid(np.arange(8), np.arange(8), indexing='ij')

print("Row grid:")
print(row_grid)
print()
print("Col grid:")
print(col_grid)
print()

# Calculate differences from start position
row_diff = np.abs(row_grid - start_row)
col_diff = np.abs(col_grid - start_col)

print(f"Row differences from {start_row}:")
print(row_diff)
print()
print(f"Col differences from {start_col}:")
print(col_diff)
print()

# Knight move condition:
# (row_diff == 2 AND col_diff == 1) OR (row_diff == 1 AND col_diff == 2)
knight_mask = ((row_diff == 2) & (col_diff == 1)) | ((row_diff == 1) & (col_diff == 2))

print("Knight move mask:")
print(knight_mask.astype(int))
print()

# Exclude starting position
knight_mask[start_row, start_col] = False

# Get valid positions
valid_positions = np.argwhere(knight_mask)
print(f"Valid moves: {len(valid_positions)}")
print(valid_positions)
print()

Knight position: (3, 3)

METHOD 2: Boolean Indexing

Row grid:
[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7]]

Col grid:
[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]

Row differences from 3:
[[3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]]

Col differences from 3:
[[3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]
 [3 2 1 0 1 2 3 4]]

Knight move mask:
[[0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Valid moves: 8
[[1 2]
 [1 4]
 [2 1]
 [2 5]
 [4 1]
 [4 5]
 [5 2]
 [5 4]]

