<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/BROADCASTING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python list - DOESN'T WORK! ❌

In [ ]:
list1 = [[1, 2, 3], [4, 5, 6]]
list2 = [10, 20, 30]
result = list1 + list2
print(result)

[[1, 2, 3], [4, 5, 6], 10, 20, 30]


NumPy

In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


If the shapes are not equal, 1's are added to the front of the smaller shape:
```
(3,)     →  (1, 3)
(4, 3)   →  (4, 3)  # Allaqachon to'liq
```


In each dimension:
- The shapes must be equal, OR
- One must be 1

```
✅ VALID:
(2, 3) + (1, 3)  # 2≠1 but 1 can stretch, 3=3 ✅
(4, 1) + (1, 5)  # 4≠1 but 1 can stretch, 1≠5 but 1 can stretch ✅
(3, 4, 5) + (1, 4, 5)  ✅

❌ INVALID:
(2, 3) + (2, 4)  # 3≠4 and neither is 1 ❌
(3, 5) + (4, 5)  # 3≠4 and neither is 1 ❌
```


Visualization:
```
CASE 1: Row vector + Matrix
arr = [[1, 2, 3],    row = [10, 20, 30]
       [4, 5, 6]]
       
Broadcasting:
[10, 20, 30]  ─┐
[10, 20, 30]  ─┘ Stretched to each row!

Result:
[[11, 22, 33],
 [14, 25, 36]]

```

#Basic Broadcasting - Scalar

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Array:")
print(arr)
print("Shape:", arr.shape)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)


calar broadcasting

NumPy internally:

 10 → (1,) → (1, 1) → (3, 3) broadcasted!

In [ ]:
result = arr + 11
print("arr + 11:")
print(result)

Result:
[[12 13 14]
 [15 16 17]
 [18 19 20]]


In [ ]:
result = arr * 2
print("arr * 2")
print(result)

arr * 2
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#1D Array + 2D Array (Row)

In [ ]:
row = np.array([10, 20, 30])
print("Row:")
print(row)
print("Shape:", row.shape)

Row:
[10 20 30]
Shape: (3,)


Broadcasting!

In [ ]:
result = arr + row
print("arr + row:")
print(result)

arr + row:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
print("How it works:")
print("(3, 3) + (3,)")
print("(3, 3) + (1, 3)  ← 1 added to left")
print("(3, 3) + (3, 3)  ← 1 stretched to 3")

How it works:
(3, 3) + (3,)
(3, 3) + (1, 3)  ← 1 added to left
(3, 3) + (3, 3)  ← 1 stretched to 3


Manual visualization

In [ ]:
print("Broadcasting process:")
print("Row [10, 20, 30] becomes:")
print("[[10, 20, 30],")
print(" [10, 20, 30],")
print(" [10, 20, 30]]")

Broadcasting process:
Row [10, 20, 30] becomes:
[[10, 20, 30],
 [10, 20, 30],
 [10, 20, 30]]


# 1D Array + 2D Array (Column)

In [ ]:
col = np.array([10, 20, 30])
col_reshaped = col.reshape(3, 1)
print("Column:")
print(col_reshaped)
print("Shape:", col_reshaped.shape)

Column:
[[10]
 [20]
 [30]]
Shape: (3, 1)


Broadcasting!

In [ ]:
result = arr + col_reshaped
print("arr + col:")
print(result)

arr + col:
[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [ ]:
print("How it works:")
print("(3, 3) + (3, 1)")
print("(3, 3) + (3, 3)  ← 1 stretched to 3")

How it works:
(3, 3) + (3, 1)
(3, 3) + (3, 3)  ← 1 stretched to 3


Alternative: [:, np.newaxis]

In [ ]:
col_newaxis = col[:, np.newaxis]
print("Column (newaxis):")
print(col_newaxis)
print("Shape:", col_newaxis.shape)

Column (newaxis):
[[10]
 [20]
 [30]]
Shape: (3, 1)


In [ ]:
result = arr + col_newaxis
print("arr + col (newaxis):")
print(result)

arr + col (newaxis):
[[11 12 13]
 [24 25 26]
 [37 38 39]]


#Broadcasting Shapes Examples

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[10, 20, 30, 40]])

In [ ]:
result = a + b
print("Result:")
print(result)

Result:
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [ ]:
print(f"a shape:{a.shape}, b shape:{b.shape}")
print("Result shape:",{result.shape})

a shape:(3, 1), b shape:(1, 4)
Result shape: {(2, 3, 4)}


Example 2: (4, 1, 3) + (1, 5, 3)

In [ ]:
c = np.ones((4, 1, 3))
d = np.ones((1, 5, 3))

In [ ]:
result = c + d
print("Result:")
print(result)

Result:
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
print(f"c shape:{c.shape}, d shape:{d.shape}")
print("Result shape:",{result.shape})

c shape:(4, 1, 3), d shape:(1, 5, 3)
Result shape: {(2, 3, 4)}


Example 3: (2, 3, 4) + (3, 4)

In [ ]:
e = np.ones((2, 3, 4))
f = np.ones((3, 4))

In [ ]:
result = e + f
print("Result:")
print(result)

Result:
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [ ]:
print(f"e shape:{e.shape}, f shape:{f.shape}")
print("Result shape:",{result.shape})

e shape:(2, 3, 4), f shape:(3, 4)
Result shape: {(2, 3, 4)}


In [ ]:
try:
  g = np.ones((3, 4))
  h = np.ones((5, 4))
  result = g + h
except ValueError as e:
  print(e)

operands could not be broadcast together with shapes (3,4) (5,4) 


# Real-world - Image Processing

In [ ]:
img = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
print("Image shape:", img.shape)

Image shape: (100, 100, 3)


Add same value to all pixels (brightness)

In [ ]:
brightness = 50
brighter = np.clip(img + brightness, 0, 255).astype(np.uint8)
print("Brighter image shape:", brighter.shape)

Brighter image shape: (100, 100, 3)


Different adjustment per channel

 Red +30, Green +20, Blue +10

In [ ]:
channel_adjust = np.array([30, 20, 10])
adjusted = np.clip(img + channel_adjust, 0, 255).astype(np.uint8)
print("Adjusted image shape:", adjusted.shape)

Adjusted image shape: (100, 100, 3)


In [ ]:
print("Broadcasting:")
print("(100, 100, 3) + (3,)")
print("(100, 100, 3) + (1, 1, 3)")
print("(100, 100, 3) + (100, 100, 3)")

Broadcasting:
(100, 100, 3) + (3,)
(100, 100, 3) + (1, 1, 3)
(100, 100, 3) + (100, 100, 3)


Different adjustment per row (gradient)

In [ ]:
row_adjust = np.linspace(0, 50, 100).reshape(100, 1, 1)
gradient = np.clip(img + row_adjust, 0, 255).astype(np.uint8)
print("Gradient image shape:", gradient.shape)

Gradient image shape: (100, 100, 3)


Sample values

In [ ]:
print("Sample gradient values:")
print(f"Top (row 0): {row_adjust[0, 0, 0]:.1f}")
print(f"Middle (row 50): {row_adjust[50, 0, 0]:.1f}")
print(f"Bottom (row 99): {row_adjust[99, 0, 0]}")

Sample gradient values:
Top (row 0): 0.0
Middle (row 50): 25.3
Bottom (row 99): 50.0


Normalization (Data Science)

In [ ]:
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0],
                 [10.0, 11.0, 12.0],
                 [13.0, 14.0, 15.0]])

print("Original data:")
print(data)
print("Shape:", data.shape)

Original data:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
Shape: (5, 3)


NORMALIZATION: (x - mean) / std

Per-feature (per-column)

Mean per column

In [ ]:
mean = data.mean(axis=0)
print("Mean per feature:", mean)

Mean per feature: [7. 8. 9.]


Std per column

In [ ]:
std = data.std(axis=0)
print("Std per feature:", std)

Std per feature: [4.24264069 4.24264069 4.24264069]


In [ ]:
normalized = (data - mean) / std
print("Normalized data:")
print(normalized)

Normalized data:
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


Verify: mean ≈ 0, std ≈ 1

In [ ]:
print("Normalized mean:", normalized.mean(axis=0))

Normalized mean: [-4.4408921e-17 -4.4408921e-17 -4.4408921e-17]


In [ ]:
print("Normalized std:", normalized.std(axis=0))

Normalized std: [1. 1. 1.]


In [ ]:
print("Broadcasting breakdown:")
print(f"data shape : {data.shape}")
print(f"mean shape: {mean.shape}")
print(f"std shape : {std.shape}")
print("(5, 3) - (3,) → (5, 3) - (1, 3) → (5, 3)")

Broadcasting breakdown:
data shape : (5, 3)
mean shape: (3,)
std shape : (3,)
(5, 3) - (3,) → (5, 3) - (1, 3) → (5, 3)


#Distance Matrix

Points in 2D space

In [ ]:
points = np.array([[1, 2],
                   [4, 6],
                   [7, 8],
                   [2, 3]])
print("Points:")
print(points)

Points:
[[1 2]
 [4 6]
 [7 8]
 [2 3]]


Calculate pairwise distances

Using broadcasting!

 Reshape for broadcasting

In [ ]:
a = points[:, np.newaxis, :]
b = points[np.newaxis, :, :]

print("a shape:", a.shape)
print("b shape:", b.shape)

a shape: (4, 1, 2)
b shape: (1, 4, 2)


Difference

In [ ]:
diff = a -b
print("Difference:")
print(diff)

Difference:
[[[ 0  0]
  [-3 -4]
  [-6 -6]
  [-1 -1]]

 [[ 3  4]
  [ 0  0]
  [-3 -2]
  [ 2  3]]

 [[ 6  6]
  [ 3  2]
  [ 0  0]
  [ 5  5]]

 [[ 1  1]
  [-2 -3]
  [-5 -5]
  [ 0  0]]]


In [ ]:
distances = np.sqrt((diff ** 2).sum(axis=2))
print("Distances:")
print(distances)

Distances:
[[0.         5.         8.48528137 1.41421356]
 [5.         0.         3.60555128 3.60555128]
 [8.48528137 3.60555128 0.         7.07106781]
 [1.41421356 3.60555128 7.07106781 0.        ]]


In [ ]:
print("Interpretation:")
print("distances[i, j] = distance between points[i] and points[j]")
print(f"Point 0 to Point 1: {distances[0, 1]:.2f}")
print(f"Point 0 to Point 2: {distances[0, 2]:.2f}")
print(f"Point 1 to Point 2: {distances[1, 2]:.2f}")

Interpretation:
distances[i, j] = distance between points[i] and points[j]
Point 0 to Point 1: 5.00
Point 0 to Point 2: 8.49
Point 1 to Point 2: 3.61


#PRICTICE

##BASIC BROADCASTING

In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("Matrix:")
print(matrix)
print("Shape:", matrix.shape)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


Add 100 to each element

In [ ]:
result = matrix + 100
print("Result:")
print(result)

Multiply each element by 5

In [ ]:
result = matrix * 5
print("Result:")
print(result)

##ROW BROADCASTING


In [ ]:
row = np.array([1, 2, 3, 4])
print("row shape:", row.shape)

row shape: (4,)


matrix + row

In [ ]:
result = matrix + row
print("Result:")
print(result)

Result:
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


matrix * row

In [ ]:
result = matrix * row
print("Result:")
print(result)

Result:
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]


##COLUMN BROADCASTING


In [ ]:
col = np.array([10, 20, 30])
print("Sape col:", col.shape)

Sape col: (3,)


reshape col to (3, 1)

In [ ]:
col_newaxis = col[:, np.newaxis]
print("Shape col_neaxis:", col_newaxis.shape)

Shape col_neaxis: (3, 1)


In [ ]:
col_reshape = col.reshape(3,1)
print("Shape col_resape:", col_reshape.shape)

Shape col_resape: (3, 1)


matrix + col_reshaped

In [ ]:
result = matrix + col_reshape
print("Result:")
print(result)

Result:
[[11 12 13 14]
 [25 26 27 28]
 [39 40 41 42]]


##IMAGE PROCESSING

In [ ]:
img = np.random.randint(0, 256, (50, 50, 3), dtype=np.uint8)
print("Image shape:", img.shape)

Image shape: (50, 50, 3)


Add 50 to each pixel

In [ ]:
brighter = 50
brighter_img = np.clip(img + brighter, 0, 255).astype(np.uint8)
print("Brighter image shape:", brighter_img.shape)

Brighter image shape: (50, 50, 3)


Red +40, Green +20, Blue +0

In [ ]:
channel_adj = np.array([40,20,0])
adjust = np.clip(img + channel_adj, 0, 255).astype(np.uint8)
print("Adjusted image shape:", adjust.shape)

Adjusted image shape: (50, 50, 3)


##NORMALIZATION

In [ ]:
data = np.random.rand(10, 4)
print("Data:")
print(data)

Data:
[[0.05583038 0.60245964 0.27160621 0.70060374]
 [0.89116244 0.59722089 0.33760966 0.24629057]
 [0.96502954 0.56555824 0.58191712 0.47118327]
 [0.70296217 0.16537525 0.08038899 0.64472295]
 [0.24217169 0.89456013 0.79156269 0.68289267]
 [0.40838598 0.77883985 0.24008052 0.91053386]
 [0.83784851 0.65880112 0.12907043 0.15801896]
 [0.32553015 0.34851703 0.98302726 0.54166346]
 [0.72204217 0.25479673 0.76565586 0.26593969]
 [0.62852883 0.28100761 0.30480963 0.38200916]]


 Mean per feature (axis=0)

In [ ]:
mean = data.mean(axis=0)
print("mean axis 0:", mean)

mean axis 0: [0.57794919 0.51471365 0.44857284 0.50038583]


Std per feature

In [ ]:
std = data.std(axis=0)
print("std axis 0:", std)

std axis 0: [0.28848784 0.22885216 0.29445101 0.22710454]


Normalize: (data - mean) / std

In [ ]:
normalize = (data - mean) / std
print("Normalized data:")
print(normalize)

Normalized data:
[[-1.80984683  0.38341778 -0.60100533  0.8816112 ]
 [ 1.08570694  0.36052636 -0.37684768 -1.11884713]
 [ 1.34175619  0.22217221  0.45285729 -0.12858645]
 [ 0.43333884 -1.52648064 -1.25040782  0.63555367]
 [-1.16392251  1.65978979  1.16484522  0.80362479]
 [-0.58776551  1.1541346  -0.70807134  1.80598782]
 [ 0.90090216  0.62960941 -1.08507833 -1.50752988]
 [-0.87497286 -0.72621827  1.81508778  0.18175609]
 [ 0.49947681 -1.13574157  1.07686172 -1.032327  ]
 [ 0.17532678 -1.02120966 -0.48824151 -0.52124311]]


Verify - normalized mean ≈ 0, std ≈ 1

In [ ]:
print("Normalize mean:", normalize.mean(axis=0))

Normalize mean: [ 5.55111512e-18  3.55271368e-16 -2.77555756e-17  4.55191440e-16]


In [ ]:
print("Normalize std:", normalize.std(axis=0))

Normalize std: [1. 1. 1. 1.]


##SHAPE CHECKING

In [ ]:
try:
  a = np.ones((3,4))
  b = np.ones((4))
  result = a + b
  print(result)
except ValueError as e:
  print(e)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [ ]:
try:
  c = np.ones((3, 4))
  d = np.ones((3, 1))
  result = c + d
  print(result)
except ValueError as e:
  print(e)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [ ]:
try:
  e = np.ones((2, 3))
  f = np.ones((2, 4))
  result = e + f
  print(result)
except ValueError as e:
  print(e)

operands could not be broadcast together with shapes (2,3) (2,4) 


Create checkerboard pattern (8x8) using broadcasting

HINT: row indices + column indices, then % 2

In [ ]:
checpoint = np.zeros((8, 8), dtype=int)
checpoint[1::2, ::2] = 1
checpoint[::2, 1::2] = 1
print(checpoint)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
rows = np.arange(8).reshape(8,1)
print("Rows:")
print(rows)

Rows:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [ ]:
cols = np.arange(8)
print("Cols:")
print(cols)

Cols:
[0 1 2 3 4 5 6 7]


In [ ]:
sum_grid = rows + cols
print("Sum grid:")
print(sum_grid)

Sum grid:
[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]


In [ ]:
checkerboard = sum_grid % 2
print("Checkerboard:")
print(checkerboard)

Checkerboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Gradient image (100x100)

Horizontal gradient: 0 (left) → 255 (right)


In [ ]:
vertical_gradient = np.linspace(0, 255, 100).reshape(100, 1)
vertical_gradient = np.repeat(vertical_gradient, 100, axis=1).astype(np.uint8)
print("Vertical gradient:")
print(vertical_gradient)

Vertical gradient:
[[  0   0   0 ...   0   0   0]
 [  2   2   2 ...   2   2   2]
 [  5   5   5 ...   5   5   5]
 ...
 [249 249 249 ... 249 249 249]
 [252 252 252 ... 252 252 252]
 [255 255 255 ... 255 255 255]]


In [ ]:
print(f"Top (row 0): {vertical_gradient[0, 0]}")
print(f"Middle (row 50): {vertical_gradient[50, 0]}")
print(f"Bottom (row 99): {vertical_gradient[99, 0]}")

Top (row 0): 0
Middle (row 50): 128
Bottom (row 99): 255


2D GRADIENT (diagonal)

In [ ]:
h_grad = np.linspace(0, 255, 100).reshape(100, 1)
v_grad = np.linspace(0, 255, 100).reshape(1, 100)
dioganal_gradient = ((h_grad + v_grad) / 2).astype(np.uint8)
print("Diagonal gradient:")
print(dioganal_gradient)

Diagonal gradient:
[[  0   1   2 ... 124 126 127]
 [  1   2   3 ... 126 127 128]
 [  2   3   5 ... 127 128 130]
 ...
 [124 126 127 ... 249 251 252]
 [126 127 128 ... 251 252 253]
 [127 128 130 ... 252 253 255]]


In [ ]:
print(f"Top (row 0): {dioganal_gradient[0, 0]}")
print(f"Middle (row 50): {dioganal_gradient[50, 0]}")
print(f"Bottom (row 99): {dioganal_gradient[99, 0]}")

Top (row 0): 0
Middle (row 50): 64
Bottom (row 99): 127
