<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/BROADCASTING_RULES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Scalar broadcasting - skalyar bilan
1D to 2D - qator bilan
Column broadcasting - ustun bilan
Complex broadcasting - murakkab shartlar

```
Trailing dimensions must match or be 1

  (3, 4) + (4,) ✅ Works
  (3, 4) + (3,) ❌ Error


Missing dimensions treated as 1

  (4,) → (1, 4)
  (3, 1) broadcasts with (4,)


Arrays stretched along size 1 dimensions

  (3, 1) + (1, 4) → both become (3, 4)

In [ ]:
import numpy as np

#Basic Broadcasting! 📡

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original array (2x3):")
print(arr)
print(f"Shape: {arr.shape}")

Original array (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


SCALAR BROADCASTING

In [ ]:
print("Add scalar 10:")
result = arr + 10
print(result)

Add scalar 10:
[[11 12 13]
 [14 15 16]]


 Multiply by scalar

In [ ]:
print("Multiply by 2:")
result = arr * 2
print(result)

Multiply by 2:
[[ 2  4  6]
 [ 8 10 12]]


#1D Array Broadcasting! 📏





In [ ]:
row = np.array([10, 20, 30])
print("1D array (row):")
print(row)
print(f"Shape: {row.shape}")

1D array (row):
[10 20 30]
Shape: (3,)


Add row to each row of 2D array

In [ ]:
result = arr + row
print("arr + row:")
print(result)

arr + row:
[[11 22 33]
 [14 25 36]]


How broadcasting works

In [ ]:
print("Broadcasting visualization:")
print("arr:    [[1, 2, 3],")
print("         [4, 5, 6]]")
print("row:    [10, 20, 30]  ← stretched to each row")

Broadcasting visualization:
arr:    [[1, 2, 3],
         [4, 5, 6]]
row:    [10, 20, 30]  ← stretched to each row


#Column Broadcasting! 📊

In [ ]:
col = np.array([[10],
                [20]])
print("Column array:")
print(col)
print(f"Shape: {col.shape}")

Column array:
[[10]
 [20]]
Shape: (2, 1)


Add column to each column of 2D array

In [ ]:
result = arr + col
print("arr + col:")
print(result)

arr + col:
[[11 12 13]
 [24 25 26]]


How broadcasting work

In [ ]:
print("Broadcasting visualization:")
print("arr: [[1, 2, 3],    col: [[10],  ← stretched")
print("      [4, 5, 6]]          [20]]  ← to 3 cols")
print()

Broadcasting visualization:
arr: [[1, 2, 3],    col: [[10],  ← stretched
      [4, 5, 6]]          [20]]  ← to 3 cols



#Real Example - Normalization! 🎯

Student scores (3 students, 4 subjects)

In [ ]:
scores = np.array([[85, 90, 78, 92],
                   [88, 85, 82, 95],
                   [79, 88, 90, 87]])

print("Student scores (3 students, 4 subjects):")
print(scores)

Student scores (3 students, 4 subjects):
[[85 90 78 92]
 [88 85 82 95]
 [79 88 90 87]]


Calculate mean for each subject (column-wise)

In [ ]:
mean = scores.mean(axis=0)
print("Mean for each subject:")
print(mean)
print(f"Sahpe: {mean.shape}")

Mean for each subject:
[84.         87.66666667 83.33333333 91.33333333]
Sahpe: (4,)


Calculate std for each subject

In [ ]:
std = scores.std(axis=0)
print("Std for each subject:")
print(std)
print(f"Shape: {std.shape}")

Std for each subject:
[3.74165739 2.05480467 4.98887652 3.29983165]
Shape: (4,)


NORMALIZE using broadcasting

(scores - mean) broadcasts: (3,4) - (4,) → (3,4)


(result / std) broadcasts: (3,4) / (4,) → (3,4)


In [ ]:
normalized = (scores - mean) / std
print("Normalized scores (z-score):")
print(normalized)

Normalized scores (z-score):
[[ 0.26726124  1.13554995 -1.06904497  0.20203051]
 [ 1.06904497 -1.29777137 -0.26726124  1.1111678 ]
 [-1.33630621  0.16222142  1.33630621 -1.31319831]]


Mean should be ~0, std should be ~1

In [ ]:
print("Varification:")
print(f"New mean per subject: {normalized.mean(axis=0)}")
print(f"New std per subject: {normalized.std(axis=0)}")

Varification:
New mean per subject: [ 0.00000000e+00 -2.29446092e-15  9.62193288e-16  1.40628250e-15]
New std per subject: [1. 1. 1. 1.]


#Temperature Adjustment

Weekly temps for 3 cities (3 cities, 7 days)

In [ ]:
temps = np.array([[20, 22, 25, 23, 21, 24, 26],
                  [18, 20, 22, 21, 19, 22, 24],
                  [22, 24, 27, 25, 23, 26, 28]])

print("Weekly temps (3 cities, 7 days):")
print(temps)

Weekly temps (3 cities, 7 days):
[[20 22 25 23 21 24 26]
 [18 20 22 21 19 22 24]
 [22 24 27 25 23 26 28]]


In [ ]:
each_city_adjustment = np.array([+2, 0, -1]).reshape(3, 1)
print("Each city adjustment:")
print(each_city_adjustment)

Each city adjustment:
[[ 2]
 [ 0]
 [-1]]


In [ ]:
adjust = temps + each_city_adjustment
print("Adjusted temps:")
print(adjust)

Adjusted temps:
[[22 24 27 25 23 26 28]
 [18 20 22 21 19 22 24]
 [21 23 26 24 22 25 27]]


#Sales Discount

Product prices (4 products, 3 stores)

In [ ]:
prices = np.array([[100, 120, 110],
                  [200, 180, 190],
                  [50, 60, 55],
                  [150, 140, 160]])
print("Product prices (4 products, 3 stores):")
print(prices)

Product prices (4 products, 3 stores):
[[100 120 110]
 [200 180 190]
 [ 50  60  55]
 [150 140 160]]


In [ ]:
discount = np.array([0.9, 0.95, 0.85])
print("Discount for each store (10%, 5%, 15% off):")
print(discount)

Discount for each store (10%, 5%, 15% off):
[0.9  0.95 0.85]


In [ ]:
apply = prices * discount
print("Discounted prices:")
print(apply)

Discounted prices:
[[ 90.   114.    93.5 ]
 [180.   171.   161.5 ]
 [ 45.    57.    46.75]
 [135.   133.   136.  ]]


#Matrix Operations

Matrix A (3x4)


In [ ]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print("Matrix A (3x4):")
print(A)

Matrix A (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row = np.array([1, 2, 3, 4])
print("Row:")
print(row)

Row:
[1 2 3 4]


In [ ]:
col = np.array([[10],
                [20],
                [30]])
print("Col:")
print(col)

Col:
[[10]
 [20]
 [30]]


In [ ]:
broadcast_row = A + row
print("Broadcast row to all rows:")
print(broadcast_row)

Broadcast row to all rows:
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [ ]:
broadcast_col = A + col
print("Broadcast col to all cols:")
print(broadcast_col)

Broadcast col to all cols:
[[11 12 13 14]
 [25 26 27 28]
 [39 40 41 42]]


In [ ]:
print("A Shape:", A.shape)
print("Row Shape:", row.shape)
print("Col Shape:", col.shape)
print("Broadcast row Shape:", broadcast_row.shape)
print("Broadcast col Shape:", broadcast_col.shape)

A Shape: (3, 4)
Row Shape: (4,)
Col Shape: (3, 1)
Broadcast row Shape: (3, 4)
Broadcast col Shape: (3, 4)
