<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/FANCY_INDEXING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Integer array indexing - array of indices
Multi-dimensional fancy - 2D selection
np.where() - find indices by condition

```
FANCY INDEXING:

Non-sequential selection
Specific elements kerak
Dynamic index lists
Advanced data extraction

REGULAR indexing:

Single element
Slicing (sequential)
Simple access

In [ ]:
import numpy as np

#Basic Fancy Indexing! 🎯

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:")
print(arr)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]


Select specific indices

In [ ]:
indices = [0, 3, 5, 9]
selected = arr[indices]
print("Selected elements:")
print(selected)

Selected elements:
[ 10  40  60 100]


Select in any order

In [ ]:
reverse_indices = [9, 5, 3, 0]
reverse_selected = arr[reverse_indices]
print("Selected elements in reverse order:")
print(reverse_selected)

Selected elements in reverse order:
[100  60  40  10]


In [ ]:
repeat_indeices = [1, 1, 2, 2, 2]
repeat_selected = arr[repeat_indeices]
print("Selected elements in reverse order:")
print(repeat_selected)

Selected elements in reverse order:
[20 20 30 30 30]


#2D Fancy Indexing! 📐

In [ ]:
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print("Original data:")
print(data)

Original data:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Select diagonal elements

In [ ]:
rows = [0, 1, 2, 3]
cols = [0, 1, 2, 3]
diagonal = data[rows, cols]
print("Diagonal elements:")
print(diagonal)

Diagonal elements:
[ 1  6 11 16]


Select specific elements

In [ ]:
rows = [0, 2, 3]
cols = [1, 3, 0]
selected = data[rows, cols]
print("Selected elements:")
print(selected)

Selected elements:
[ 2 12 13]


Select entire rows

In [ ]:
row_indices = [0, 3]
selected_rows = data[row_indices]
print(f"Rows:\n{row_indices}:")
print(selected_rows)

Rows:
[0, 3]:
[[ 1  2  3  4]
 [13 14 15 16]]


#np.where() - Find Indices! 🔍

In [ ]:
scores = np.array([85, 92, 78, 95, 88, 76, 90, 82])
print("Student scores:")
print(scores)

Student scores:
[85 92 78 95 88 76 90 82]


In [ ]:
high_scores = np.where(scores >= 90)
print("Indices of students with high scores:")
print(high_scores)
print(high_scores[0])

Indices of students with high scores:
(array([1, 3, 6]),)
[1 3 6]


In [ ]:
print("Students with high scores:")
print(scores[high_scores])

Students with high scores:
[92 95 90]


In [ ]:
failing = np.where(scores < 80)
print("Indices of students failing:")
print(failing[0])
print("Students failing:")
print(scores[failing])

Indices of students failing:
[2 5]
Students failing:
[78 76]


In [ ]:
good_scores = np.where((scores >= 85) & (scores <= 90))
print("Indices of students with good scores:")
print(good_scores[0])
print("Students with good scores:")
print(scores[good_scores])

Indices of students with good scores:
[0 4 6]
Students with good scores:
[85 88 90]


#Modify with Fancy Indexing! ✏️

In [ ]:
prices = np.array([100, 150, 200, 250, 300])
print("Original prices:")
print(prices)

Original prices:
[100 150 200 250 300]


Apply discount to specific items

In [ ]:
discount_indices = [1, 3]
print(f"Applying 20% discount to indices: {discount_indices}")
prices[discount_indices] = prices[discount_indices] * 0.8
print("After prices:")
print(prices)

Applying 20% discount to indices: [1, 3]
After prices:
[100 120 200 200 300]


Set specific values to zero

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("\nOriginal array:")


Original array:


In [ ]:
zero_indices = [1, 3]
print(f"Setting indices: {zero_indices} to zero")
arr[zero_indices] = 0
print("After setting to zero:")
print(arr)

Setting indices: [1, 3] to zero
After setting to zero:
[10  0 30  0 50]


#Select Top Students

In [ ]:
scores  = np.array([75, 88, 92, 68, 95, 82, 90, 78, 85, 91])
top_scores_indices = np.where(scores >= 90)
print("Indices of top scores:")
print(top_scores_indices)

Indices of top scores:
(array([2, 4, 6, 9]),)


In [ ]:
top_scores = scores[top_scores_indices]
print("Top scores:")
print(top_scores)

Top scores:
[92 95 90 91]


In [ ]:
print("Count of top scores:")
print(len(top_scores))

Count of top scores:
4


In [ ]:
print("Average top scores:")
print(top_scores.mean())

Average top scores:
92.0


#Extract Specific Data

In [ ]:
np.random.seed(42)
data = np.random.randint(10, 30, (5, 7))
print("Original data:")
print(data)

Original data:
[[16 29 24 20 17 16 28]
 [20 20 13 17 12 11 21]
 [15 11 10 21 21 26 19]
 [25 24 24 28 21 29 12]
 [14 28 16 18 16 27 13]]


In [ ]:
specific_day_index = [0, 2, 4]
specific_day = data[:, specific_day_index]
print("Specific day data:")
print(specific_day)

Specific day data:
[[16 24 17]
 [20 13 12]
 [15 10 21]
 [25 24 21]
 [14 16 16]]


In [ ]:
avg_specific_day = specific_day.mean(axis=0)
print("Average of specific day data:")
print(avg_specific_day)

Average of specific day data:
[18.  17.4 17.4]


#Conditional Modification

In [ ]:
original_prices = np.array([50, 120, 80, 200, 45, 150, 90, 180])
prices = original_prices.copy()
print("Original prices:")
print(prices)

Original prices:
[ 50 120  80 200  45 150  90 180]


In [ ]:
indices = np.where(prices > 100)
prices[indices] = prices[indices] * 0.9
print("After discount:")
print(prices)

After discount:
[ 50 108  80 180  45 135  90 162]


In [ ]:
discount_amount = original_prices - prices
print("Discount amount:")
print(discount_amount)

Discount amount:
[ 0 12  0 20  0 15  0 18]
