<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/FILE_I_O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.save() - save in binary format (.npy)
np.load() - load from binary format
np.savetxt() - save in text format (.csv, .txt)
np.loadtxt() - load from text format

```
Binary vs Text:
BINARY (.npy):

✅ Fast
✅ Exact precision
✅ Small file (compressed)
❌ NumPy only

TEXT (.csv, .txt):

✅ Human readable
✅ Universal (Excel, etc.)
✅ Easy to debug
❌ Large file, slower

In [1]:
import numpy as np

#Basic Binary Save/Load! 💾

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:")
print(arr)

Original array:
[10 20 30 40 50]


SAVE to binary file

In [3]:
np.save("my_data.npy", arr)
print("Saved to 'my_data.npy'")

Saved to 'my_data.npy'


LOAD from binary file

In [4]:
loaded = np.load("my_data.npy")
print("Loaded array:")
print(loaded)

Loaded array:
[10 20 30 40 50]


Verify they're the same

In [5]:
print("Array match:", np.array_equal(arr, loaded))

Array match: True


#Text Save/Load (CSV)! 📄

In [6]:
data = np.array([[85, 90, 78],
                 [88, 92, 84],
                 [90, 88, 86],
                 [82, 85, 80]])

print("Student grades:")
print(data)
print(f"Shape: {data.shape}")

Student grades:
[[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]]
Shape: (4, 3)


In [7]:
np.savetxt('grades.csv', data, delimiter=',', fmt='%d')
print("Saved to 'grades.csv'")

Saved to 'grades.csv'


In [8]:
loaded = np.loadtxt('grades.csv', delimiter=',')
print("Loaded grades:")
print(loaded)
print(f"Shape: {loaded.shape}")

Loaded grades:
[[85. 90. 78.]
 [88. 92. 84.]
 [90. 88. 86.]
 [82. 85. 80.]]
Shape: (4, 3)


Verify

In [9]:
print("Data match:", np.array_equal(data, loaded))

Data match: True


#Save Multiple Arrays! 📦

In [11]:
student_ids = np.array([1, 2, 3, 4])
math_scores = np.array([85, 88, 90, 82])
phsics_scores = np.array([90, 92, 88, 85])

print("Student IDs:", student_ids)
print("Math Scores:", math_scores)
print("Physics Scores:", phsics_scores)

Student IDs: [1 2 3 4]
Math Scores: [85 88 90 82]
Physics Scores: [90 92 88 85]


SAVE multiple arrays

In [13]:
np.savez('student_data.npz', ids = student_ids, math = math_scores, physics = phsics_scores)
print("Saved to 'student_data.npz'")

Saved to 'student_data.npz'


LOAD multiple arrays

In [14]:
data = np.load('student_data.npz')
print("Loaded data keys:", list(data.keys()))

Loaded data keys: ['ids', 'math', 'physics']


In [15]:
print("Loaded IDs:", data['ids'])
print("Loaded Math:", data['math'])
print("Loaded Physics:", data['physics'])

Loaded IDs: [1 2 3 4]
Loaded Math: [85 88 90 82]
Loaded Physics: [90 92 88 85]


Access and analyze


In [16]:
print("Math average:", data['math'].mean())
print("Physics average:", data['physics'].mean())

Math average: 86.25
Physics average: 88.75


#Real Example - Temperature Log! 🌡️

In [17]:
print("Collecting temperature data...")
np.random.seed(7)
temperatures = np.random.uniform(15, 30, 7)

print("Weekly temperatures (°C):")
for day, temp in enumerate(temperatures, start=1):
  print(f"Day {day}: {temp:.1f}°C")

Weekly temperatures (°C):
Day 1: 16.1°C
Day 2: 26.7°C
Day 3: 21.6°C
Day 4: 25.9°C
Day 5: 29.7°C
Day 6: 23.1°C
Day 7: 22.5°C


SAVE to file

In [18]:
filename = 'temperature_log.txt'
np.savetxt(filename, temperatures, fmt='%.2f', header='Temperature Log (Celsius)')
print(f"Temperature data saved to '{filename}'")

Temperature data saved to 'temperature_log.txt'


Later... LOAD and analyze

In [19]:
print("Loading temperature data...")
loaded_temps = np.loadtxt(filename)
print(f"Loaded {len(loaded_temps)} temperature readings.")

Loading temperature data...
Loaded 7 temperature readings.


In [20]:
print("Statistics:")
print(f"Average: {loaded_temps.mean():.2f}°C")
print(f"Maximum: {loaded_temps.max():.2f}°C")
print(f"Minimum: {loaded_temps.min():.2f}°C")
print(f"Standard Deviation: {loaded_temps.std():.2f}°C")

Statistics:
Average: 23.65°C
Maximum: 29.67°C
Minimum: 16.14°C
Standard Deviation: 4.01°C


#Save Student Scores

In [24]:
scores = np.array([[85, 90, 78],
                   [88, 92, 84],
                   [90, 88, 86],
                   [82, 85, 80],
                   [95, 93, 91]])

print("Student scores:")
print(scores)
print(f"Shape: {scores.shape}")

Student scores:
[[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]
 [95 93 91]]
Shape: (5, 3)


In [22]:
np.save("student_scores.npy", scores)
print("Saved successfully")

Saved successfully


In [23]:
loaded_scores = np.load("student_scores.npy")
print("Loaded scores:")
print(loaded_scores)

Loaded scores:
[[85 90 78]
 [88 92 84]
 [90 88 86]
 [82 85 80]
 [95 93 91]]


In [25]:
print("Equal shape:", np.array_equal(scores.shape, loaded_scores.shape))

Equal shape: True


In [26]:
avg_overal = loaded.mean()
print("Average overal:", avg_overal)

Average overal: 85.66666666666667


#CSV Export/Import

In [31]:
np.random.seed(42)
sales = np.random.randint(100, 200, (7, 4))
np.savetxt("weekly_sales.csv",sales, delimiter=',')
loaded_scv = np.loadtxt("weekly_sales.csv", delimiter=',')

In [32]:
daily_sum = loaded_scv.sum(axis=1)
print("Daily sales sum:")
print(daily_sum)

Daily sales sum:
[628. 648. 734. 498. 554. 543. 585.]


In [33]:
shops_sum = loaded_scv.sum(axis=0)
print("Shops sales sum:")
print(shops_sum)

Shops sales sum:
[ 942. 1113. 1049. 1086.]


Multiple Arrays Save

In [35]:
names = np.array(['Ali', 'Vali', 'Guli', 'Diyor'], dtype=str)
ages = np.array([20, 21, 19, 22])
grades = np.array([85.5, 88.0, 92.5, 87.0])

np.savez("students.npz", names=names, ages=ages, grades=grades)
loaded_z = np.load("students.npz")

print("Names:", loaded_z['names'])
print("Ages:", loaded_z['ages'])
print("Grades:", loaded_z['grades'])

Names: ['Ali' 'Vali' 'Guli' 'Diyor']
Ages: [20 21 19 22]
Grades: [85.5 88.  92.5 87. ]


In [36]:
avg_age = loaded_z['ages'].mean()
print("Average age:", avg_age)
avg_score = loaded_z['grades'].mean()
print("Average score:", avg_score)

Average age: 20.5
Average score: 88.25
