<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/FILE_I_O_ADVANCED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.savez() - ko'p arraylarni saqlash
np.load() - ko'p arraylarni yuklash
np.savez_compressed() - siqilgan format
tofile() / fromfile() - binary format
np.memmap() - katta fayllar uchun

```
NPZ format:

  Stores multiple arrays
  Dictionary-like access
  Compressed option available
  NumPy native format

BINARY format:

  Fastest I/O
  Smallest files
  No metadata (need to know dtype/shape)

In [ ]:
import numpy as np
import os

#np.savez() - Multiple Arrays! 📦

In [ ]:
student_ids = np.array([101, 102, 103, 104, 105])
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 82],
                   [88, 92, 90],
                   [95, 93, 96]])
subjects = np.array(['Math', 'Physics', 'English'], dtype='U10')

print("Student IDs:", student_ids)
print("Scores:")
print(scores)
print("Subjects:", subjects)

Student IDs: [101 102 103 104 105]
Scores:
[[85 90 78]
 [92 88 95]
 [78 85 82]
 [88 92 90]
 [95 93 96]]
Subjects: ['Math' 'Physics' 'English']


SAVE all together

In [ ]:
np.savez("student_data.npz",
         ids=student_ids,
         scores=scores,
         subjects=subjects)
print("Saved to 'student_data.npz'")

Saved to 'student_data.npz'


LOAD all

In [ ]:
print("Loading data ...")
data = np.load("student_data.npz")
print("Available keys:", list(data.keys()))

Loading data ...
Available keys: ['ids', 'scores', 'subjects']


Access by key

In [ ]:
loaded_ids = data['ids']
loaded_scores = data['scores']
loaded_subjects = data['subjects']

print("Loaded Student IDs:", loaded_ids)
print("Loaded Scores:")
print(loaded_scores)
print("Loaded Subjects:", loaded_subjects)

Loaded Student IDs: [101 102 103 104 105]
Loaded Scores:
[[85 90 78]
 [92 88 95]
 [78 85 82]
 [88 92 90]
 [95 93 96]]
Loaded Subjects: ['Math' 'Physics' 'English']


Verify

In [ ]:
print("IDs match:", np.array_equal(student_ids, loaded_ids))
print("Scores match:", np.array_equal(scores, loaded_scores))
print("Subjects match:", np.array_equal(subjects, loaded_subjects))

IDs match: True
Scores match: True
Subjects match: True


Close file

In [ ]:
data.close()

#Compressed Format! 🗜️

In [ ]:
large_data = np.random.rand(1000, 1000)
print(f"Large array shape: {large_data.shape}")

Large array shape: (1000, 1000)


SAVE uncompressed

In [ ]:
np.savez("large_uncompressed.npz", data=large_data)
size_uncompressed = os.path.getsize("large_uncompressed.npz")
print(f"Size of uncompressed file: {size_uncompressed / 1024:.2f} KB")
print("Saved to 'large_uncompressed.npz'")

Size of uncompressed file: 7812.76 KB
Saved to 'large_uncompressed.npz'


SAVE compressed

In [ ]:
np.savez_compressed('large_compressed.npz', data=large_data)
size_compressed = os.path.getsize('large_compressed.npz')
print(f"Size of compressed file: {size_compressed / 1024:.2f} KB")

Size of compressed file: 7367.59 KB


Compression ratio

In [ ]:
ratio = size_uncompressed / size_compressed
print(f"Compression ratio: {ratio:.2f}x smaller")

Compression ratio: 1.06x smaller


Load compressed (same way)

In [ ]:
data = np.load("large_compressed.npz")
loaded = data['data']
print("Loaded shape:", loaded.shape)
print("Data match:", np.array_equal(large_data, loaded))

Loaded shape: (1000, 1000)
Data match: True


#Binary Files! ⚡

In [ ]:
data = np.array([1.5, 2.7, 3.9, 4.1, 5.3])
print("Original data:", data)
print(f"dtype: {data.dtype}, shape: {data.shape}")

Original data: [1.5 2.7 3.9 4.1 5.3]
dtype: float64, shape: (5,)


In [ ]:
data.tofile('data.bin')
print("Saved ti 'data.bin' (binary)")

Saved ti 'data.bin' (binary)


LOAD from binary

IMPORTANT: Must specify dtype and shape!

In [ ]:
loaded = np.fromfile('data.bin', dtype=np.float64)
print("Loaded data: ", loaded)
print(f"dtype: {loaded.dtype}, shape: {loaded.shape}")

Loaded data:  [1.5 2.7 3.9 4.1 5.3]
dtype: float64, shape: (5,)


Verify

In [ ]:
print("Data match:", np.array_equal(data, loaded))

Data match: True


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]], dtype=np.int32)

print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]]


In [ ]:
matrix.tofile('matrix.bin')

In [ ]:
loaded_flat = np.fromfile('matrix.bin', dtype=np.int32)
loaded_matrix = loaded_flat.reshape(2, 3)
print("Loaded flat array:", loaded_flat)
print("Loaded matrix:")
print(loaded_matrix)

Loaded flat array: [1 2 3 4 5 6]
Loaded matrix:
[[1 2 3]
 [4 5 6]]


#Default Names in savez! 📝

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)

Array 1: [1 2 3]
Array 2: [4 5 6]
Array 3: [7 8 9]


Save without keywords (uses arr_0, arr_1, ...)

In [ ]:
np.savez("default_namez.npz", arr1, arr2, arr3)
print("Saved to 'default_namez.npz'")

Saved to 'default_namez.npz'


Load

In [ ]:
data = np.load("default_namez.npz")
print("Available keys:", list(data.keys()))

Available keys: ['arr_0', 'arr_1', 'arr_2']


Access by default names

In [ ]:
print("arr_0:", data['arr_0'])
print("arr_1:", data['arr_1'])
print("arr_2:", data['arr_2'])

arr_0: [1 2 3]
arr_1: [4 5 6]
arr_2: [7 8 9]


#Project Data Archive

In [ ]:
project_name = np.array('WebApp')
team_members = np.array(['Alice', 'Bob', 'Charlie', 'Diana'], dtype='U10')
sprint_scores = np.array([[85, 90, 88], [92, 87, 91], [78, 82, 85], [95, 93, 96]])
sprint_dates = np.array(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64')

print("Project Name:", project_name)
print("Team Members:", team_members)
print("Sprint Scores:")
print(sprint_scores)

Project Name: WebApp
Team Members: ['Alice' 'Bob' 'Charlie' 'Diana']
Sprint Scores:
[[85 90 88]
 [92 87 91]
 [78 82 85]
 [95 93 96]]


In [ ]:
np.savez("project.npz",
         name = project_name,
         members = team_members,
         scores = sprint_scores,
         dates = sprint_dates)
print("Saved to 'project.npz'")

Saved to 'project.npz'


In [ ]:
data = np.load("project.npz")
print("Available keys:", list(data.keys()))

Available keys: ['name', 'members', 'scores', 'dates']


In [ ]:
print("Project name:", data['name'])
print("Team members:", data['members'])
print("Sprint scores:")
print(data['scores'])
print("Total sprints:", data['dates'])

Project name: WebApp
Team members: ['Alice' 'Bob' 'Charlie' 'Diana']
Sprint scores:
[[85 90 88]
 [92 87 91]
 [78 82 85]
 [95 93 96]]
Total sprints: ['2024-01-01' '2024-02-01' '2024-03-01']


Calculate average score per sprint

In [ ]:
avg_sprint = data['scores'].mean(axis=0)
for sprint, avg_scores in zip(data['dates'], avg_sprint):
    print(f"Average scores for sprint {sprint}: {avg_scores}")

Average scores for sprint 2024-01-01: 87.5
Average scores for sprint 2024-02-01: 88.0
Average scores for sprint 2024-03-01: 90.0


#Compression Test

In [ ]:
array = np.random.rand(500, 500)
print("Array shape:", array.shape)

Array shape: (500, 500)


In [ ]:
np.savez("uncompressed.npz", data=array)
load_uncompressed = np.load("uncompressed.npz")
size_uncompressed = os.path.getsize("uncompressed.npz")

print(f"Size of uncompressed file: {size_uncompressed / 1024:.2f} KB")

Size of uncompressed file: 1953.38 KB


In [ ]:
np.savez_compressed("compressed.npz", data=array)
load_compressed = np.load("compressed.npz")
size_compressed = os.path.getsize("compressed.npz")

print(f"Size of compressed file: {size_compressed / 1024:.2f} KB")

Size of compressed file: 1842.13 KB


In [ ]:
radio = size_uncompressed / size_compressed
print(f"Compression ratio: {radio:.2f}x smaller")

Compression ratio: 1.06x smaller


#Binary Format Speed

In [ ]:
response_times = np.array([120, 135, 145, 150, 155, 160, 165, 170], dtype=np.int32)
timestamps = np.array([0, 5, 10, 15, 20, 25, 30, 35], dtype=np.int32)

print("Response times:", response_times)
print("Timestamps:", timestamps)

Response times: [120 135 145 150 155 160 165 170]
Timestamps: [ 0  5 10 15 20 25 30 35]


In [ ]:
response_times.tofile("times.bin")
timestamps.tofile("stamps.bin")

In [ ]:
times = np.fromfile("times.bin", dtype=np.int32)
stamps = np.fromfile("stamps.bin", dtype=np.int32)

print("Loaded response times:", times)
print("Loaded timestamps:", stamps)

Loaded response times: [120 135 145 150 155 160 165 170]
Loaded timestamps: [ 0  5 10 15 20 25 30 35]


Verify data integrity

In [ ]:
print("Verify data integrity times:", np.array_equal(response_times, times))
print("Verify data integrity stamps:", np.array_equal(timestamps, stamps))

Verify data integrity times: True
Verify data integrity stamps: True


In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.int8)
arr2 = np.array([1, 2, 3], dtype=np.int16)
arr3 = np.array([1, 2, 3], dtype=np.int32)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)
print("Equal:", np.array_equal(arr1, arr2),np.array_equal(arr1, arr3),np.array_equal(arr2, arr3))

Array 1: [1 2 3]
Array 2: [1 2 3]
Array 3: [1 2 3]
Equal: True True True
