<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/LINEAR_ALGEBRA_BASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Matrix multiplication - np.dot() yoki @
Transpose - .T
Determinant - np.linalg.det()
Inverse - np.linalg.inv()
Eigenvalues - np.linalg.eig()

In [ ]:
import numpy as np

#Matrix Multiplication! ✖️

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])  # 3x2

print("Matrix A (2x3):")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B (3x2):")
print(B)
print(f"Shape: {B.shape}")

Matrix A (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Matrix B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]
Shape: (3, 2)


Matrix multiplication using @

In [ ]:
C = A @ B
print("Matrix C (2x2):")
print(C)
print(f"Shape: {C.shape}")

Matrix C (2x2):
[[ 58  64]
 [139 154]]
Shape: (2, 2)


Using np.dot()

In [ ]:
C2 =np.dot(A, B)
print("Matrix C (2x2):")
print(C2)
print(f"Shape: {C2.shape}")

Matrix C (2x2):
[[ 58  64]
 [139 154]]
Shape: (2, 2)


Element-wise (different!)

In [ ]:
elem_wise = A[:2, :2] * B[:2, :2]
print("Element-wise multiplication:")
print(elem_wise)
print(f"Shape: {elem_wise.shape}")

Element-wise multiplication:
[[ 7 16]
 [36 50]]
Shape: (2, 2)


#Transpose! 🔄

In [ ]:
data = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Original (3x4):")
print(data)
print(f"Shape: {data.shape}")

Original (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


TRANSPOSE

In [ ]:
transposed = data.T
print("Transposed (4x3):")
print(transposed)
print(f"Shape: {transposed.shape}")

Transposed (4x3):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Shape: (4, 3)


Real example: students/subjects → subjects/students

In [ ]:
students_subjects = np.array([[85, 90, 78],  # Student 1
                               [88, 92, 84],  # Student 2
                               [79, 88, 90]]) # Student 3
# Columns: Math, Physics, English

print("Students (rows) × Subjects (cols):")
print(students_subjects)

Students (rows) × Subjects (cols):
[[85 90 78]
 [88 92 84]
 [79 88 90]]


In [ ]:
subjects_students = students_subjects.T
print("Subjects (rows) × Students (cols):")
print(subjects_students)
print("Row 0 (Math): all students' Math scores")

Subjects (rows) × Students (cols):
[[85 88 79]
 [90 92 88]
 [78 84 90]]
Row 0 (Math): all students' Math scores


#Determinant & Inverse! 🔢

In [ ]:
A = np.array([[4, 7],
              [2, 6]])

print("Matrix A:")
print(A)

Matrix A:
[[4 7]
 [2 6]]


DETERMINANT

In [ ]:
det = np.linalg.det(A)
print(f"Determinant: {det}")

Determinant: 10.000000000000002


INVERSE (if det ≠ 0)

In [ ]:
if det != 0:
  A_inv = np.linalg.inv(A)
  print("Inverse:")
  print(A_inv)
  print()

  identity = A @ A_inv
  print("Identity matrix:")
  print(identity)

Inverse:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Identity matrix:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


#Eigenvalues! 🎯

In [ ]:
A = np.array([[2, 1],
              [1, 2]])

print("Matrix A:")
print(A)

Matrix A:
[[2 1]
 [1 2]]


EIGENVALUES and EIGENVECTORS

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[3. 1.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Each column is an eigenvector

In [ ]:
print("First eigenvector (for λ=3):")
print(eigenvectors[:, 0])

First eigenvector (for λ=3):
[0.70710678 0.70710678]


Verify: A @ v = λ @ v

In [ ]:
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]
left = A @ v1
right = lambda1 * v1
print(f"Verification for λ={lambda1:.2f}")
print("Left:")
print(left)
print("Right:")
print(right)
print(f"Are they equal? {np.allclose(left, right)}")

Verification for λ=3.00
Left:
[2.12132034 2.12132034]
Right:
[2.12132034 2.12132034]
Are they equal? True


# Matrix Operations

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A (2x2):")
print(A)
print(f"Shape: {A.shape}")
print()

print("Matrix B (2x2):")
print(B)
print(f"Shape: {B.shape}")

Matrix A (2x2):
[[1 2]
 [3 4]]
Shape: (2, 2)

Matrix B (2x2):
[[5 6]
 [7 8]]
Shape: (2, 2)


In [ ]:
C =  A @ B
print("Matrix C (2x2):")
print(C)
print(f"Shape: {C.shape}")

Matrix C (2x2):
[[19 22]
 [43 50]]
Shape: (2, 2)


In [ ]:
D = B @ A
print("Matrix D (2x2):")
print(D)
print(f"Shape: {D.shape}")

Matrix D (2x2):
[[23 34]
 [31 46]]
Shape: (2, 2)


In [ ]:
equal = np.array_equal(C, D)
print("Equal:", equal)

Equal: False


In [ ]:
transposed = A.T
print("Transposed (2x2):")
print(transposed)
print(f"Shape: {transposed.shape}")

Transposed (2x2):
[[1 3]
 [2 4]]
Shape: (2, 2)


#Determinant & Inverse

In [ ]:
matrix = np.array([[3, 8],
                   [4, 6]])

print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")

Matrix:
[[3 8]
 [4 6]]
Shape: (2, 2)


In [ ]:
det = np.linalg.det(matrix)
print(f"Determinant: {det}")
print(f"Shape: {det.shape}")

Determinant: -14.000000000000004
Shape: ()


In [ ]:
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)
print(f"Shape: {inverse.shape}")

Inverse:
[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]
Shape: (2, 2)


In [ ]:
identity = matrix @ inverse
print("Identity matrix:")
print(identity)
print(f"Shape: {identity.shape}")

Identity matrix:
[[1. 0.]
 [0. 1.]]
Shape: (2, 2)


# Practical Example

In [ ]:
prices = np.array([[10, 20, 30],
                   [15, 25, 35]])

print("Prices (2x3):")
print(prices)
print(f"Shape: {prices.shape}")

Prices (2x3):
[[10 20 30]
 [15 25 35]]
Shape: (2, 3)


In [ ]:
costs = np.array([[2],
                 [3],
                 [1]])
print("Costs (3x1):")
print(costs)
print(f"Shape: {costs.shape}")

Cost (3x1):
[[2]
 [3]
 [1]]
Shape: (3, 1)


In [ ]:
total = prices @ costs

print("Total (2x1):")
print(total)
print(f"Shape: {total.shape}")

Total (2x1):
[[110]
 [140]]
Shape: (2, 1)


In [ ]:
print("Total cost for each product:")
product = np.array(["Product A", "Product B"], dtype=str)
for i, cost in enumerate(total):
  print(f"{product[i]} cost: {cost[0]:.2f}")

Total cost for each product:
Product A cost: 110.00
Product B cost: 140.00
