<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MEMORY_MANAGEMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Views vs Copies - xotira ko'rinishi vs nusxa
.copy() - aniq nusxa yaratish
Memory sharing - xotira ulashish
.base - asosiy array tekshirish
Memory info - xotira ma'lumotlari

```
VIEW:

  References original data
  Changes affect original
  No extra memory
  Fast to create

COPY:

  New independent data
  Changes don't affect original
  Uses extra memory
  Slower to create

In [ ]:
import numpy as np

#Views vs Copies! 👁️

In [ ]:
original = np.array([10, 20, 30, 40, 50])
print("Original:", original)

Original: [10 20 30 40 50]


SLICE creates a VIEW

In [ ]:
view = original[1:4]
print("View (slice [1:4])", view)
print(f"View shares memory: {view.base is original}")

View (slice [1:4]) [20 30 40]
View shares memory: True


Modify view

In [ ]:
view[0] = 999
print("After view[0] = 999:")
print("View:", view)
print("Original:", original)

After view[0] = 999:
View: [999  30  40]
Original: [ 10 999  30  40  50]


COPY creates independent array

In [ ]:
copy = original.copy()
print("Copy:", copy)
print(f"Copy shares memory: {copy.base is original}")

Copy: [ 10 999  30  40  50]
Copy shares memory: False


Modify copy

In [ ]:
copy[0] = 777
print("After copy[0] = 777:")
print("Copy:", copy)
print("Original:", original)

After copy[0] = 777:
Copy: [777 999  30  40  50]
Original: [ 10 999  30  40  50]


#Checking Memory Sharing! 🔍

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr)
print(f"Original ID: {id(arr)}")

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Original ID: 138931887656560


Different operations

In [ ]:
slice_view = arr[0:2]
print(f"Slice [0:2] - is view: {slice_view.base is arr}")
print(f"Base: {slice_view.base is not None}")

Slice [0:2] - is view: True
Base: True


In [ ]:
reshape_view = arr.reshape(1, 9)
print(f"Reshape - is view: {reshape_view.base is arr}")

Reshape - is view: True


In [ ]:
transpose_view = arr.T
print(f"Transpose - is view: {transpose_view.base is arr}")

Transpose - is view: True


In [ ]:
flatten_copy = arr.flatten()
print(f"Flatten - is view: {flatten_copy.base is arr}")

Flatten - is view: False


In [ ]:
raval_view = arr.ravel()
print(f"Ravel - is view: {raval_view.base is arr}")

Ravel - is view: True


In [ ]:
print("Operations that create VIEWS:")
print("- Slicing: arr[1:3]")
print("- Reshape: arr.reshape()")
print("- Transpose: arr.T")
print("- Ravel: arr.ravel() (when possible)")
print()

print("Operations that create COPIES:")
print("- Flatten: arr.flatten()")
print("- Copy: arr.copy()")
print("- Some fancy indexing")

Operations that create VIEWS:
- Slicing: arr[1:3]
- Reshape: arr.reshape()
- Transpose: arr.T
- Ravel: arr.ravel() (when possible)

Operations that create COPIES:
- Flatten: arr.flatten()
- Copy: arr.copy()
- Some fancy indexing


#Memory Information! 📊

In [ ]:
int8_arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
int32_arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
int64_arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)
float64_arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)

print("Same values, different dtypes:")

Same values, different dtypes:


Memory usage

In [ ]:
print(f"int8: {int8_arr.nbytes} bytes ({int8_arr.itemsize} per element)")
print(f"int32: {int32_arr.nbytes} bytes ({int32_arr.itemsize} per element)")
print(f"int64: {int64_arr.nbytes} bytes ({int64_arr.itemsize} per element)")
print(f"float64: {float64_arr.nbytes} bytes ({float64_arr.itemsize} per element)")

int8: 5 bytes (1 per element)
int32: 20 bytes (4 per element)
int64: 40 bytes (8 per element)
float64: 40 bytes (8 per element)


Large array example

In [ ]:
large = np.random.rand(1000, 1000)
print(f"Large array (1000x1000):")
print(f"Shape: {large.shape}")
print(f"Size: {large.size} elements")
print(f"dtype: {large.dtype}")
print(f"Total memory: {large.nbytes/ (1024**2):.2f} MB")
print(f"Per element: {large.itemsize} bytes")

Large array (1000x1000):
Shape: (1000, 1000)
Size: 1000000 elements
dtype: float64
Total memory: 7.63 MB
Per element: 8 bytes


Memory flags

In [ ]:
print(f"C-contiguous: {large.flags['C_CONTIGUOUS']}")
print(f"F-contiguous: {large.flags['F_CONTIGUOUS']}")
print(f"Writeable: {large.flags['WRITEABLE']}")
print(f"Owndata: {large.flags['OWNDATA']}")

C-contiguous: True
F-contiguous: False
Writeable: True
Owndata: True


#Practical Memory Optimization! 💡

In [ ]:
data = np.random.rand(5000, 1000)
print(f"Dataset shape: {data.shape}")
print(f"Dataset memory: {data.nbytes / (1024**2):.2f} MB")

Dataset shape: (5000, 1000)
Dataset memory: 38.15 MB


Creating unnecessary copies

In [ ]:
print("❌ BAD - Multiple copies:")
normalized_copy = data.copy()
normalized_copy = (normalized_copy - normalized_copy.mean()) / normalized_copy.std()
print(f"Created extra {normalized_copy.nbytes / (1024**2):.2f} MB copy")

❌ BAD - Multiple copies:
Created extra 38.15 MB copy


GOOD: In-place operations (when safe)

In [ ]:
print("✅ GOOD - In-place operations:")
data2 = np.random.rand(5000, 1000)
mean = data2.mean()
std = data2.std(0)
data2 -= mean
data2 /= std
print("No extra memory used!")

✅ GOOD - In-place operations:
No extra memory used!


GOOD: Views for read-only operations

In [ ]:
print("✅ GOOD - Using views:")
subset = data[1000:2000]  # View, not copy
result = subset.mean()
print(f"View memory: 0 MB extra (shares original)")

✅ GOOD - Using views:
View memory: 0 MB extra (shares original)


In [ ]:
print("When to COPY:")
print("- Need independent modification")
print("- Preventing unintended changes")
print("- Long-term storage of subset")
print()

print("When to use VIEW:")
print("- Read-only operations")
print("- Temporary computations")
print("- Memory constrained")

When to COPY:
- Need independent modification
- Preventing unintended changes
- Long-term storage of subset

When to use VIEW:
- Read-only operations
- Temporary computations
- Memory constrained


#View vs Copy Behavior

In [ ]:
data = np.array([100, 200, 300, 400, 500])
print("Original data:")
print(data)

Original data:
[100 200 300 400 500]


In [ ]:
view = data[1:4]
print("View:")
print(view)

View:
[200 300 400]


In [ ]:
view[0] = 999

print("View:", view)
print("Original data:", data)
print(f"Base:{view.base is not None}")

View: [999 300 400]
Original data: [100 999 300 400 500]
Base:True


In [ ]:
copy = data.copy()

print("Original data:", data)
print("Copy:", copy)

Original data: [100 999 300 400 500]
Copy: [100 999 300 400 500]


In [ ]:
print(f"Base: {copy.base is not None}")

Base: False


#Memory Usage Analysis

In [ ]:
arr_int8 = np.array([10, 20, 30, 40, 50], dtype=np.int8)
arr_int32 = np.array([10, 20, 30, 40, 50], dtype=np.int32)
arr_float64 = np.array([10, 20, 30, 40, 50], dtype=np.float64)

In [ ]:
print(f"Int8 memory: {arr_int8.nbytes} bytes, per element: {arr_int8.itemsize}")
print(f"Int32 memory: {arr_int32.nbytes} bytes, per element: {arr_int32.itemsize}")
print(f"Float64 memory: {arr_float64.nbytes} bytes, per element: {arr_float64.itemsize}")

Int8 memory: 5 bytes, per element: 1
Int32 memory: 20 bytes, per element: 4
Float64 memory: 40 bytes, per element: 8


In [ ]:
memory_difference32to8 = arr_int32.nbytes - arr_int8.nbytes
memory_difference64to32 = arr_float64.nbytes - arr_int32.nbytes
memory_difference64to8 = memory_difference32to8 + memory_difference64to32

print(f"Memory difference int32 to int8: {memory_difference32to8} bytes")
print(f"Memory difference float64 to int32: {memory_difference64to32} bytes")
print(f"Memory difference float64 to int8: {memory_difference64to8} bytes")

Memory difference int32 to int8: 15 bytes
Memory difference float64 to int32: 20 bytes
Memory difference float64 to int8: 35


In [ ]:
memory_array = np.array([arr_int8.nbytes, arr_int8.nbytes, arr_float64.nbytes])
memory_name = np.array(["int8", "int32", "float64"])
useful_memory = memory_array.argmin()
print(f"Best usefull memury {memory_name[useful_memory]}: {memory_array[useful_memory]} bytes")

Best usefull memury int8: 5


In [ ]:
arr_1000 = np.random.rand(1000)
memory = arr_1000.nbytes

print(f"Memory for 1000 elements: {memory / 1024:.2f} KB")

Memory for 1000 elements: 7.81 KB


#Optimization Challenge

In [ ]:
matrix = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

print("Original matrix:")
print(matrix)
print(f"Memory usage: {matrix.nbytes} bytes")

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Memory usage: 96 bytes


(Bad): Copy + modify

In [ ]:
copy = matrix.copy()
row_0 = np.array([[10], [1], [1]])

mult = copy * row_0

print("Multiplied matrix:")
print(mult)
print(f"Memory usage: {mult.nbytes} bytes")
print("Original:")
print(matrix)
print(f"Memory usage: {matrix.nbytes} bytes")

Multiplied matrix:
[[10 20 30 40]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Memory usage: 96 bytes
Original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Memory usage: 96 bytes


(Good): View + modify

In [ ]:
view = matrix[1:3]
print(f"View:{view}")
row_0 = np.array([[10], [1]])
view *= row_0
print("Multiplied view:")
print(view)
print(f"Memory usage: {view.nbytes} bytes")
print("Original:")
print(matrix)
print(f"Memory usage: {matrix.nbytes} bytes")

View:[[50 60 70 80]
 [ 9 10 11 12]]
Multiplied view:
[[500 600 700 800]
 [  9  10  11  12]]
Memory usage: 64 bytes
Original:
[[  1   2   3   4]
 [500 600 700 800]
 [  9  10  11  12]]
Memory usage: 96 bytes


Memory saving

In [ ]:
saving = matrix.nbytes - view.nbytes
print(f"Memory saving: {saving} bytes ({saving / matrix.nbytes * 100:.2f}%)")

Memory saving: 32 bytes (33.33%)
