<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MINI_TEST_WEEK_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Fancy Indexing + Sorting

In [ ]:
employee_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108])
performance = np.array([78, 92, 85, 95, 88, 76, 90, 82])

print("IDs:", employee_ids)
print("Performance:", performance)

IDs: [101 102 103 104 105 106 107 108]
Performance: [78 92 85 95 88 76 90 82]


In [ ]:
top_per = np.argsort(performance)[::-1]
print("Top 3 performance:", top_per[:3])

Top 3 performance: [3 1 6]


In [ ]:
high_per_ids = np.where(performance >= 90)
print(high_per_ids[0])

[1 3 6]


In [ ]:
print("Top 3 employees performanse: ")
for idx in top_per[:3]:
  print(f"IDs:{employee_ids[idx]}  , performance: {performance[idx]}")

Top 3 employees performanse: 
IDs:104  , performance: 95
IDs:102  , performance: 92
IDs:107  , performance: 90


In [ ]:
count_high_per = high_per_ids[0].size
print("High performers (>=90) count:", count_high_per)

High performers (>=90) count: 3


#Boolean + Ufuncs

In [ ]:
data = np.array([25, 100, 64, 144, 81, 49, 121, 36])

print("Data:", data)

Data: [ 25 100  64 144  81  49 121  36]


In [ ]:
root = np.sqrt(data)
print("Square root:", root)

Square root: [ 5. 10.  8. 12.  9.  7. 11.  6.]


Boolean mask

In [ ]:
boolen_mask = root < 10
print("Boolean mask:", boolen_mask)

Boolean mask: [ True False  True False  True  True False  True]


In [ ]:
small_values = data[boolen_mask]
print("Small values:", small_values)

Small values: [25 64 81 49 36]


In [ ]:
mean = small_values.mean()
print("Mean:", mean)

Mean: 51.0


#Broadcasting + Normalization

In [ ]:
scores = np.array([[85, 90, 78, 92],
                  [88, 85, 82, 95],
                  [79, 88, 90, 87]])

print("Scores:")
print(scores)

Scores:
[[85 90 78 92]
 [88 85 82 95]
 [79 88 90 87]]


In [ ]:
mean = scores.mean(axis=0)
print("Mean:", mean)

Mean: [84.         87.66666667 83.33333333 91.33333333]


In [ ]:
std = scores.std(axis=0)
print("Standard deviation:", std)

Standard deviation: [3.74165739 2.05480467 4.98887652 3.29983165]


In [ ]:
z_scores = (scores - mean) / std
print("Z-scores:")
print(z_scores)

Z-scores:
[[ 0.26726124  1.13554995 -1.06904497  0.20203051]
 [ 1.06904497 -1.29777137 -0.26726124  1.1111678 ]
 [-1.33630621  0.16222142  1.33630621 -1.31319831]]


In [ ]:
verify_mean = z_scores.mean(axis=0)
print("Verify mean:", verify_mean)

Verify mean: [ 0.00000000e+00 -2.29446092e-15  9.62193288e-16  1.40628250e-15]


In [ ]:
verify_std = z_scores.std(axis=0)
print("Verify standard deviation:", verify_std)

Verify standard deviation: [1. 1. 1. 1.]


#2D Sorting + Argmax

In [22]:
sales = np.array([[120, 150, 130],
                  [200, 180, 190],
                  [80, 95, 85],
                  [150, 140, 160]])

print("Sales:")
print(sales)

Sales:
[[120 150 130]
 [200 180 190]
 [ 80  95  85]
 [150 140 160]]


In [23]:
sort_month = np.sort(sales, axis=1)
print("Sort month:")
print(sort_month)

Sort month:
[[120 130 150]
 [180 190 200]
 [ 80  85  95]
 [140 150 160]]


In [24]:
best_month_each_product = np.argmax(sales, axis=1)
print("Best month product:")
print(best_month_each_product)

Best month product:
[1 0 1 2]


In [25]:
product_each_month = np.argmax(sales, axis=0)
print("Product each month:")
print(product_each_month)

Product each month:
[1 1 1]


In [26]:
overal_best_month = np.argmax(sales)
print("Overal best month:", overal_best_month)

Overal best month: 3


In [28]:
values = sales.max()
print("Values:", values)

Values: 200


#Combined Challenge

In [29]:
temperature = np.array([[22, 18, 25],
                        [25, 20, 28],
                        [28, 22, 30],
                        [24, 19, 26],
                        [26, 21, 29],
                        [23, 17, 27],
                        [27, 23, 31]])

print("Temperature:")
print(temperature)

Temperature:
[[22 18 25]
 [25 20 28]
 [28 22 30]
 [24 19 26]
 [26 21 29]
 [23 17 27]
 [27 23 31]]


In [30]:
avg_temperature_city = temperature.mean(axis=0)
print("Average temperature city:")
print(avg_temperature_city)

Average temperature city:
[25. 20. 28.]


In [36]:
comfortable_range = (avg_temperature_city >= 20) & (avg_temperature_city <= 25)
print("Boolean: comfortable range 20-27°C")
print(comfortable_range)

Boolean: comfortable range 20-27°C
[ True  True False]


In [37]:
comfortable_range = (temperature >= 20) & (temperature <= 25)
print("Boolean: comfortable range 20-27°C")
print(comfortable_range)

Boolean: comfortable range 20-27°C
[[ True False  True]
 [ True  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]]


In [35]:
valid_range_clip = np.clip(temperature, 15, 35)
print("Valid range clip:")
print(valid_range_clip)

Valid range clip:
[[22 18 25]
 [25 20 28]
 [28 22 30]
 [24 19 26]
 [26 21 29]
 [23 17 27]
 [27 23 31]]


In [39]:
col_to_hot = np.argsort(avg_temperature_city)
print("Column to hot:")
print(col_to_hot)

Column to hot:
[1 0 2]
