<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MINI_TEST_WEEK_5_PART_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Fancy Indexing

In [3]:
student_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
scores = np.array([75, 88, 92, 68, 95, 82, 90, 78, 85, 91])

print("Student IDs:", student_ids)
print("Student scores:", scores)

Student IDs: [101 102 103 104 105 106 107 108 109 110]
Student scores: [75 88 92 68 95 82 90 78 85 91]


In [4]:
indices = np.where(scores >= 90)
print("Indices:", indices)

Indices: (array([2, 4, 6, 9]),)


In [5]:
high_scores = student_ids[indices]
print("Students with scores >= 90:", high_scores)

Students with scores >= 90: [103 105 107 110]


In [10]:
count_high_scores = indices[0].size
print("High scorer count:", count_high_scores)

High scorer count: 4


#Boolean Masking

In [11]:
temperatures = np.array([15, 22, 28, 18, 25, 32, 19, 24, 30, 17])
print("Temperatures:", temperatures)

Temperatures: [15 22 28 18 25 32 19 24 30 17]


In [17]:
comfortable = (temperatures >= 20) & (temperatures < 28)
comfortable_days = temperatures[comfortable]
print("Comfortable days:", comfortable_days)
count_comfortable_days = comfortable_days.size
print("Comfortable day count:", count_comfortable_days)
avg_comfortable = comfortable_days.mean()
print(f"Average temperature in comfortable days: {avg_comfortable:.2f}")

Comfortable days: [22 25 24]
Comfortable day count: 3
Average temperature in comfortable days: 23.666666666666668


In [18]:
extreme = (temperatures < 18) | (temperatures > 29)
extreme_days = temperatures[extreme]
print("Extreme days:", extreme_days)
count_extreme_days = extreme_days.size
print("Extreme day count:", count_extreme_days)
avg_extreme = extreme_days.mean()
print("Average extreme days:", avg_extreme)

Extreme days: [15 32 30 17]
Extreme day count: 4
Average extreme days: 23.5


#Universal Functions

In [20]:
data = np.array([100, 400, 900, 1600, 2500])
print("Data:", data)

Data: [ 100  400  900 1600 2500]


Square root qiling


In [21]:
root = np.sqrt(data)
print("Square root:", root)

Square root: [10. 20. 30. 40. 50.]


In [22]:
round = np.round(root)
print("Round:", round)

Round: [10. 20. 30. 40. 50.]


In [24]:
square = np.square(round)
print("Square:", square)

Square: [ 100.  400.  900. 1600. 2500.]


In [25]:
match_case = np.equal(data, square)
print("Match case:", match_case)

Match case: [ True  True  True  True  True]


#Broadcasting

In [26]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("A matrix:")
print(A)

A matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
row = np.array([10, 20, 30])
print("Row:")
print(row)

Row:
[10 20 30]


In [28]:
add_row = A +  row
print("Add row:")
print(add_row)

Add row:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [29]:
col = np.array([[100], [200], [300]])
print("Col:")
print(col)

Col:
[[100]
 [200]
 [300]]


In [30]:
add_col = A + col
print("Add col:")
print(add_col)

Add col:
[[101 102 103]
 [204 205 206]
 [307 308 309]]


In [31]:
print("Shape A:", A.shape)
print("Shape row:", row.shape)
print("Shape col:", col.shape)
print("Shape add_row:", add_row.shape)
print("Shape add_col:", add_col.shape)

Shape A: (3, 3)
Shape row: (3,)
Shape col: (3, 1)
Shape add_row: (3, 3)
Shape add_col: (3, 3)


#Combined Challenge

In [32]:
prices = np.array([[100, 120, 110],
                  [200, 180, 190],
                  [50, 60, 55],
                  [150, 140, 160],
                  [80, 90, 85]])
print("Prices:")
print(prices)

Prices:
[[100 120 110]
 [200 180 190]
 [ 50  60  55]
 [150 140 160]
 [ 80  90  85]]


In [33]:
discount = np.array([0.9, 0.85, 0.95])
print("Discount:")
print(discount)

Discount:
[0.9  0.85 0.95]


In [34]:
broadcast = prices * discount
print("Broadcast:")
print(broadcast)

Broadcast:
[[ 90.   102.   104.5 ]
 [180.   153.   180.5 ]
 [ 45.    51.    52.25]
 [135.   119.   152.  ]
 [ 72.    76.5   80.75]]


In [35]:
discounted_price = broadcast[broadcast < 100]
print("Discounted price:")
print(discounted_price)

Discounted price:
[90.   45.   51.   52.25 72.   76.5  80.75]


In [36]:
cheap_items = np.where(broadcast < 100)
print("Cheap items:")
print(cheap_items)

Cheap items:
(array([0, 2, 2, 2, 4, 4, 4]), array([0, 0, 1, 2, 0, 1, 2]))


In [37]:
cheap_items_count = cheap_items[0].size
print("Count cheap items:", cheap_items_count)

Count cheap items: 7


In [39]:
avg_cheap_items = discounted_price.mean()
print(f"Average cheap items: {avg_cheap_items:.2f}")

Average cheap items: 66.79
