<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MINI_TEST_WEEK_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Set Operations

In [ ]:
math = np.array([1, 2, 3, 4, 5, 6, 7, 8])
physics = np.array([3, 4, 5, 6, 7, 8, 9, 10])
chemistry = np.array([5, 6, 7, 8, 9, 10, 11, 12])

print("Math:", math)
print("Hysics:", physics)
print("Hemistry:", chemistry)

Math: [1 2 3 4 5 6 7 8]
Hysics: [ 3  4  5  6  7  8  9 10]
Hemistry: [ 5  6  7  8  9 10 11 12]


In [ ]:
tipple_intersect = np.intersect1d(np.intersect1d(math,chemistry), physics)
print("Tipple Intersect:", tipple_intersect)
print("Count:", len(tipple_intersect))

Tipple Intersect: [5 6 7 8]
Count: 4


In [ ]:
union = np.union1d(np.union1d(math,chemistry), physics)
print("Union:", union)
print("Count:", len(union))

Union: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Count: 12


In [ ]:
only_math = np.setdiff1d(math, physics)
print("Only Math:", only_math)
print("Count:", len(only_math))

Only Math: [1 2]
Count: 2


#Linear Algebra

In [ ]:
A = np.array([[2, 3],
     [1, 4]])
B = np.array([[5, 6],
     [7, 8]])

print("A:", A)
print("B:", B)

A: [[2 3]
 [1 4]]
B: [[5 6]
 [7 8]]


In [ ]:
C = A @ B
print("C (A @ B):", C)

C (A @ B): [[31 36]
 [33 38]]


In [ ]:
D = A.T
print("D (A.T):", D)

D (A.T): [[2 1]
 [3 4]]


In [ ]:
det = np.linalg.det(A)
print(f"det(A): {det:.0f}")

det(A): 5


In [ ]:
if det != 0:
  inverse = np.linalg.inv(A)
  I = A @ inverse
  print("inverse:")
  print(inverse)
  print("I (A @ inverse):")
  print(I)
else:
  print("A is not invertible")

inverse:
[[ 0.8 -0.6]
 [-0.2  0.4]]
I (A @ inverse):
[[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]


#Statistics + Outliers

In [ ]:
test_scores = np.array([45, 52, 58, 65, 68, 72, 75, 78, 82, 85, 88, 95, 150])
print("Test Scores:", test_scores)

Test Scores: [ 45  52  58  65  68  72  75  78  82  85  88  95 150]


In [ ]:
q1 = np.percentile(test_scores, 25)
median = np.median(test_scores)
q3 = np.percentile(test_scores, 75)

print("Q1:", q1)
print("Median:", median)
print("Q3:", q3)

Q1: 65.0
Median: 75.0
Q3: 85.0


In [ ]:
iqr = q3 - q1
print("IQR:", iqr)

IQR: 20.0


In [ ]:
outlier = (test_scores < (q1 - 1.5 * iqr)) | (test_scores > (q3 + 1.5 * iqr))
print("Outliers:", test_scores[outlier])

Outliers: [150]


In [ ]:
filtering = test_scores[~outlier]
print("Filtering Outliers:", filtering)

Filtering Outliers: [45 52 58 65 68 72 75 78 82 85 88 95]


#Correlation + Histogram

In [ ]:
hours_studied = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
exam_scores = np.array([45, 50, 60, 65, 70, 75, 80, 85, 90, 95])

print("Hours Studied:", hours_studied)
print("Exam Scores:", exam_scores)

Hours Studied: [ 1  2  3  4  5  6  7  8  9 10]
Exam Scores: [45 50 60 65 70 75 80 85 90 95]


In [ ]:
correlation = np.corrcoef(hours_studied, exam_scores)[0, 1]
print("Correlation:", correlation)

Correlation: 0.9958743946641203


In [ ]:
print("Interpretation ")
if correlation > 0.7:
  print("Strong Positive Correlation")
elif correlation > 0.3:
  print("Moderate Positive Correlation")
else:
  print("Weak Positive Correlation")

Interpretation 
Strong Positive Correlation


In [ ]:
histogram = np.histogram(exam_scores, bins=5)
print("Histogram:", histogram)

Histogram: (array([2, 1, 2, 2, 3]), array([45., 55., 65., 75., 85., 95.]))


In [ ]:
counts, bins = histogram
print("Counts:", counts)
print("Bins:", bins)

Counts: [2 1 2 2 3]
Bins: [45. 55. 65. 75. 85. 95.]


#Combined Challenge

In [ ]:
sales = np.array([[100, 120, 110, 130],
         [200, 180, 190, 210],
         [150, 140, 160, 170]])

growth = np.array([[1.1],
          [1.05],
          [1.08],
          [1.12]])

print("Sales:")
print(sales)
print("Growth:")
print(growth)

Sales:
[[100 120 110 130]
 [200 180 190 210]
 [150 140 160 170]]
Growth:
[[1.1 ]
 [1.05]
 [1.08]
 [1.12]]


In [ ]:
matrix_mult = sales @ growth
print("Matrix Multiplication:")
print(matrix_mult)

Matrix Multiplication:
[[500.4]
 [849.4]
 [675.2]]


In [ ]:
unique_sales = np.unique(matrix_mult)
print("Unique Sales:")
print(unique_sales)

Unique Sales:
[500.4 675.2 849.4]


In [ ]:
median_sales = np.median(unique_sales)
print("Median Sales:", median_sales)

Median Sales: 675.2
