<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MINI_TEST_RANDOM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Basic rand()

Generate 8 random floats

In [ ]:
numbers = np.random.rand(8)
print("Generate 8 random floats:")
print(numbers)

Generate 8 random floats:
[0.41895095 0.99369767 0.08362443 0.19665838 0.93139455 0.50984953
 0.6030359  0.41573797]


find and print the maximum value

In [ ]:
max_number = numbers.max()
print("Max number:")
print(max_number)

Max number:
0.9936976715562327


#Seed Reproducibility

In [ ]:
np.random.seed(100)
numbers1 = np.random.rand(4)
print("Generate 4 random floats:")
print(numbers1)

Generate 4 random floats:
[0.54340494 0.27836939 0.42451759 0.84477613]


In [ ]:
np.random.seed(100)
numbers2 = np.random.rand(4)
print("Generate 4 random floats:")
print(numbers2)

Generate 4 random floats:
[0.54340494 0.27836939 0.42451759 0.84477613]


Verify they are the same


In [ ]:
print("Same:", numbers1 == numbers2)

Same: [ True  True  True  True]


#randint() Application

Simulate rolling 2 dice 20 times

In [ ]:
dice = np.random.randint(1, 7, size=(20, 2))
print("Simulate rolling 2 dice 20 times:")
print(dice)

Simulate rolling 2 dice 20 times:
[[5 2]
 [6 6]
 [4 5]
 [5 4]
 [4 4]
 [2 2]
 [6 4]
 [1 3]
 [2 2]
 [4 3]
 [6 4]
 [1 2]
 [1 6]
 [5 3]
 [1 1]
 [3 6]
 [3 2]
 [1 6]
 [3 2]
 [6 5]]


Calculate the sum for each pair

In [ ]:
sum_dice = dice.sum(axis=1)
print("Calculate the sum for each pair:")
print(sum_dice)

Calculate the sum for each pair:
[ 7 12  9  9  8  4 10  4  4  7 10  3  7  8  2  9  5  7  5 11]


Print how many times you got 7 (lucky number!)

In [ ]:
lucky_number = (sum_dice==7).sum()
print("Print how many times you got 7 (lucky number!):")
print(lucky_number)

Print how many times you got 7 (lucky number!):
4


#choice() Basic

Select 3 friends randomly

In [ ]:
friends = ['Ali', 'Vali', 'Guli', 'Diyor', 'Zebo']
print("Friends:", friends)

Friends: ['Ali', 'Vali', 'Guli', 'Diyor', 'Zebo']


In [ ]:
choice_friends = np.random.choice(friends, 3)
print("going to movie:", choice_friends)

going to movie: ['Guli' 'Ali' 'Diyor']


#choice() Unique

Shuffle all 6 people (unique selection)

In [ ]:
people = ['Ali', 'Vali', 'Guli', 'Diyor', 'Zebo', 'Kamol']
shuffle_people = np.random.choice(people, 6, replace=False)
print("Shuffle all 6 people (unique selection):")
print(shuffle_people)

Shuffle all 6 people (unique selection):
['Zebo' 'Ali' 'Guli' 'Vali' 'Kamol' 'Diyor']


Create pairs: person[0] gives to person[1],
   person[1] gives to person[2], ... person[5] gives to person[0]

In [ ]:
for i in range(len(shuffle_people)):
  print(f"{shuffle_people[i]} gives to {shuffle_people[(i+1)%len(shuffle_people)]}")

Zebo gives to Ali
Ali gives to Guli
Guli gives to Vali
Vali gives to Kamol
Kamol gives to Diyor
Diyor gives to Zebo
