<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MINI_TEST_WEEK_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np

#Set + String Operations

In [64]:
email_list_a = np.array(['alice@gmail.com', 'bob@yahoo.com', 'charlie@gmail.com'], dtype="U30")
email_list_b = np.array(['bob@yahoo.com', 'diana@gmail.com', 'alice@gmail.com'], dtype="U30")

print("Email list A:", email_list_a)
print("Email list B:", email_list_b)

Email list A: ['alice@gmail.com' 'bob@yahoo.com' 'charlie@gmail.com']
Email list B: ['bob@yahoo.com' 'diana@gmail.com' 'alice@gmail.com']


In [65]:
both_intersected = np.intersect1d(email_list_a, email_list_b)
print("Both lists (intersect)")
print(both_intersected)

Both lists (intersect)
['alice@gmail.com' 'bob@yahoo.com']


In [66]:
users_union = np.union1d(email_list_a, email_list_b)
print("Users (union)")
print(users_union)

Users (union)
['alice@gmail.com' 'bob@yahoo.com' 'charlie@gmail.com' 'diana@gmail.com']


In [67]:
only_list_a = np.setdiff1d(email_list_a, email_list_b)
print("Only list A")
print(only_list_a)

Only list A
['charlie@gmail.com']


In [68]:
uppercase_all_emails = np.char.upper(users_union)
print("Uppercase all emails")
print(uppercase_all_emails)

Uppercase all emails
['ALICE@GMAIL.COM' 'BOB@YAHOO.COM' 'CHARLIE@GMAIL.COM' 'DIANA@GMAIL.COM']


#Linear Algebra + Statistics

In [69]:
sales_matrix = np.array([[100, 120, 130, 140],
                         [200, 180, 190, 210],
                         [150, 160, 155, 165]])
print("Sales matrix:")
print(sales_matrix)

Sales matrix:
[[100 120 130 140]
 [200 180 190 210]
 [150 160 155 165]]


In [70]:
weights = np.array([[0.2], [0.3], [0.3], [0.2]])
print("Weights:", weights)

Weights: [[0.2]
 [0.3]
 [0.3]
 [0.2]]


In [71]:
matrix_mult = sales_matrix @ weights
print("Matrix multiplication:")
print(matrix_mult)

Matrix multiplication:
[[123. ]
 [193. ]
 [157.5]]


In [72]:
q1 = np.percentile(matrix_mult, 25)
q3 = np.percentile(matrix_mult, 75)
print("Q1:", q1)
print("Q2:", q3)

Q1: 140.25
Q2: 175.25


In [73]:
correlation_matrix = np.corrcoef(sales_matrix)
print("Correlation matrix:")
print(correlation_matrix)

Correlation matrix:
[[1.         0.22677868 0.83152184]
 [0.22677868 1.         0.2       ]
 [0.83152184 0.2        1.        ]]


In [74]:
correlation_product1_product2 = correlation_matrix[0, 1]
print(f"Correlation between Product 1 and Product 2: {correlation_product1_product2:.4f}")

Correlation between Product 1 and Product 2: 0.2268


#String + Date Combined

In [75]:
events = np.array(['Conference', 'Workshop', 'Seminar', 'Meeting'])
dates = np.array(['2024-03-15', '2024-02-20', '2024-04-10', '2024-03-01'], dtype='datetime64')

print("Events:", events)
print("Dates:", dates)

Events: ['Conference' 'Workshop' 'Seminar' 'Meeting']
Dates: ['2024-03-15' '2024-02-20' '2024-04-10' '2024-03-01']


In [76]:
find_events_with_e = np.char.find(events, 'e')
print("Events with 'e':", find_events_with_e)
find_0 = find_events_with_e >= 0
print("Events with 'e' in their name:", events[find_0])

Events with 'e': [ 4 -1  1  1]
Events with 'e' in their name: ['Conference' 'Seminar' 'Meeting']


In [77]:
sort_dates = np.sort(dates)
print("Sorted dates:", sort_dates)

Sorted dates: ['2024-02-20' '2024-03-01' '2024-03-15' '2024-04-10']


In [78]:
event_in_march = sort_dates.astype('datetime64[M]') == np.datetime64('2024-03')
print("Events in March:", events[event_in_march])

Events in March: ['Workshop' 'Seminar']


In [79]:
events_sufix = np.char.add(events, " 2024")
print("Events 2024:", events_sufix)

Events 2024: ['Conference 2024' 'Workshop 2024' 'Seminar 2024' 'Meeting 2024']


#Statistics + Outliers

In [80]:
respons_time = np.array([120, 135, 145, 150, 155, 160, 165,
                      170, 180, 500, 140, 148, 152])

print("Response time (ms):", respons_time)

Response time (ms): [120 135 145 150 155 160 165 170 180 500 140 148 152]


In [81]:
q1 = np.percentile(respons_time, 25)
q3 = np.percentile(respons_time, 75)
median = np.median(respons_time)
print("Q1:", q1)
print("Q3:", q3)
print("Median:", median)

Q1: 145.0
Q3: 165.0
Median: 152.0


In [82]:
iqr = q3 - q1
print("IQR:", iqr)

IQR: 20.0


In [83]:
outlier = (respons_time > (q3 + 1.5 * iqr)) | (respons_time < (q1 - 1.5 * iqr))
outlier_tukeys = respons_time[outlier]
print("Outliers (Tukey's method):", outlier_tukeys)

Outliers (Tukey's method): [500]


In [84]:
clean_data = respons_time[~outlier]
print("Clean data:", clean_data)

Clean data: [120 135 145 150 155 160 165 170 180 140 148 152]


#Complete Integration

In [89]:
names = np.array(['Alice Smith', 'Bob Johnson', 'Charlie Brown'])
join_dates = np.array(['2020-01-15', '2019-06-20', '2021-03-10'], dtype='datetime64')
salaries = np.array([[3000, 3200, 3400, 3600],
            [4000, 4200, 4400, 4600],
            [2800, 3000, 3100, 3300]])

print("Names:", names)
print("Join dates:", join_dates)
print("Salaries:")
print(salaries)

Names: ['Alice Smith' 'Bob Johnson' 'Charlie Brown']
Join dates: ['2020-01-15' '2019-06-20' '2021-03-10']
Salaries:
[[3000 3200 3400 3600]
 [4000 4200 4400 4600]
 [2800 3000 3100 3300]]


In [90]:
today = np.datetime64('2024-02-22')
print("Today:", today)

Today: 2024-02-22


In [91]:
years_of_service = (today - join_dates) / 365
print("Years of service:", years_of_service)

Years of service: [4 4 2]


In [92]:
total = salaries.sum(axis=1)
print("Total salaries:", total)

Total salaries: [13200 17200 12200]


In [94]:
seniaor_employees = years_of_service > 3
print("Senior employees:", names[seniaor_employees])

Senior employees: ['Alice Smith' 'Bob Johnson']


In [95]:
print("Create summary:")
for name, service, total_salary in zip(names, years_of_service, total):
    print(f"Name:{name}, sevice: {service}, total:${total_salary}")

Create summary:
Name:Alice Smith, sevice: 4 days, total:$13200
Name:Bob Johnson, sevice: 4 days, total:$17200
Name:Charlie Brown, sevice: 2 days, total:$12200
