<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/MINI_TEST_WEEK_4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

#Stack Operations

In [21]:
month_1 = np.array([100, 120, 110, 130])
month_2 = np.array([105, 125, 115, 135])
month_3 = np.array([110, 130, 120, 140])

month = np.vstack((month_1, month_2, month_3))
id = np.array([1, 2, 3]).reshape(-1, 1)
print(month)
month_id = np.hstack((id, month))

print("3 months of sales:")
print(month_id)

[[100 120 110 130]
 [105 125 115 135]
 [110 130 120 140]]
3 months of sales:
[[  1 100 120 110 130]
 [  2 105 125 115 135]
 [  3 110 130 120 140]]


#Split and Analyze

In [23]:
revenue = np.array([1000, 1100, 1200, 1150, 1250, 1300,
           1350, 1400, 1450, 1500, 1550, 1600])

quarter = np.array(['Q1', 'Q2', 'Q3', 'Q4'])

quarter_revenue = np.split(revenue, 4)
quarter_revenue = np.array(quarter_revenue)
print(quarter_revenue)
avg_quarter = quarter_revenue.mean(axis=1)
print(f'quarter sum: {quarter_revenue.sum(axis=1)}')
print(f'quarter mean: {avg_quarter}')

print(f'Best {quarter[avg_quarter.argmax()]} quarter {avg_quarter[avg_quarter.argmax()]}')

[[1000 1100 1200]
 [1150 1250 1300]
 [1350 1400 1450]
 [1500 1550 1600]]
quarter sum: [3300 3700 4200 4650]
quarter mean: [1100.         1233.33333333 1400.         1550.        ]
Best Q4 quarter 1550.0


#Reshape Challenge

In [28]:
arr = np.arange(1, 25)
print('Original array:')
print(arr)

print('Reshape 2D array:')

r1 = arr.reshape(4, 6)
print("Array 4 rows, 6 columns")
print(r1)

r2 = arr.reshape(6, -1)
print("Array 6 rows, 3 columns")
print(r2)

r3 = arr.reshape(-1, 3)
print("Array 3 rows, 8 columns")
print(r3)

flattened = r1.flatten()
print("Flattened array:")
print(flattened)
print("Equal:", np.array_equal(arr, flattened))

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reshape 2D array:
Array 4 rows, 6 columns
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Array 6 rows, 3 columns
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Array 3 rows, 8 columns
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Equal: True


#Flatten and Stats

In [29]:
np.random.seed(42)
data = np.random.randint(50, 100, (5, 6))

flattened = data.flatten()
print("Flattened array:")
print(flattened)

Flattened array:
[88 78 64 92 57 70 88 68 72 60 60 73 85 89 73 52 71 51 73 93 79 87 51 70
 82 61 71 93 74 98]


In [31]:
overall_min = flattened.min()
print("Min", overall_min)
overall_max = flattened.max()
print("Max", overall_max)
overall_mean = flattened.mean()
print("Mean", overall_mean)
overall_std = flattened.std()
print(f"Std: {overall_std:.2f}")

Min 51
Max 98
Mean 74.1
Std: 13.19


In [33]:
each_student_avg = data.mean(axis=1)
print("Average of each student:")
print(each_student_avg)

each_subject_avg = data.mean(axis=0)
print("Average of each subject:")
print(each_subject_avg)

Average of each student:
[74.83333333 70.16666667 70.16666667 75.5        79.83333333]
Average of each subject:
[83.2 77.8 71.8 76.8 62.6 72.4]


#Save and Load

In [34]:
products = np.array(['Laptop', 'Phone', 'Tablet'], dtype=str)
prices = np.array([1200, 800, 500])
stock = np.array([50, 100, 75])

In [35]:
saved = np.savez("inventory.npz", products=products, prices=prices, stock=stock)
print("Successful data")

Successful data


In [36]:
load = np.load("inventory.npz")
print(load.files)

['products', 'prices', 'stock']


In [37]:
total = load['prices'] * load['stock']
print("Total:", total)

Total: [60000 80000 37500]


In [38]:
summa = total.sum()
print("Sum:", summa)

Sum: 177500


In [41]:
avg_price = total.mean()
print(f"Average price: {avg_price:.2f}")

Average price: 59166.67
