<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/NP_ARANGE().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NP.ARANGE()

Python range

In [1]:
for i in range(5):
  print(i)

0
1
2
3
4


NumPy arange

In [2]:
import numpy as np
arr=np.arange(5)
print(arr)

[0 1 2 3 4]


**Farqi:**
- `range()` = iterator (bir-bir)
- `np.arange()` = array (hammasi bir vaqtda)

**Real-world:**

Pixel koordinatalari:

In [4]:
pixel_coords=np.arange(0,256)
print(pixel_coords)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Frame numbers:

In [7]:
frame_numbers=np.arange(0,1000)
print(frame_numbers)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

Index array:

In [8]:
index_array=np.arange(100)
print(index_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


0 to 10 (10 is not included!)

In [9]:
arr0to10=np.arange(10)
print(arr1to10)

[0 1 2 3 4 5 6 7 8 9]


1 to 10

In [10]:
arr1to10=np.arange(1,10)
print(arr1to10)

[1 2 3 4 5 6 7 8 9]


From 5 to 15

In [12]:
arr5to15=np.arange(5,15)
print(arr5to15)

[ 5  6  7  8  9 10 11 12 13 14]


0 to 10, 2 steps

In [14]:
arr0to10step2=np.arange(0,10,2)
print(arr0to10step2)

[0 2 4 6 8]


0 to 20, 5 steps

In [15]:
arr0to20step5=np.arange(0,20,5)
print(arr0to20step5)

[ 0  5 10 15]


From 10 to 0, -1 step (reverse!)

In [16]:
arr10to0step1=np.arange(10,0,-1)
print(arr10to0step1)

[10  9  8  7  6  5  4  3  2  1]


0 to 1, 0.1 step

In [17]:
arr0to1step01=np.arange(0,1,0.1)
print(arr0to1step01)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


0 to 5, 0.5 step


In [19]:
arr0to5step05=np.arange(0,5,0.5)
print(arr0to5step05)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


10 to 5, 1.1 step

In [21]:
arr10to5step11=np.arange(10,5,-1.1)
print(arr10to5step11)

[10.   8.9  7.8  6.7  5.6]


From 0 to 15

In [22]:
arr0to15=np.arange(15)
print(arr0to15)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


From 10 to 20

In [23]:
arr10to20=np.arange(10,20)
print(arr10to20)

[10 11 12 13 14 15 16 17 18 19]


From 0 to 100, 10 steps

In [24]:
arr0to100step10=np.arange(0,100,10)
print(arr0to100step10)

[ 0 10 20 30 40 50 60 70 80 90]


20 to 0 (reverse)

In [25]:
arr20to0=np.arange(20,0,-1)
print(arr20to0)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


0 to 2, 0.2 steps

In [27]:
arroto2step02=np.arange(0,2,0.2)
print(arroto2step02)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


Create a 2D array
0 to 11, then reshape to 3x4

In [28]:
arr2D=np.arange(12).reshape(3,4)
print(arr2D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
