<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/NP_LINSPACE()_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

ARANGE - You take a STEP

In [ ]:
arr_arange=np.arange(0,10,2)
print(arr_arange)

[0 2 4 6 8]


LINSPACE - HOW MANY NUMBERS do you need

In [ ]:
arr_linspace=np.linspace(0,10,5)
print(arr_linspace)

[ 0.   2.5  5.   7.5 10. ]


#Why do you need linspace()?

1. Graphic drawing: 100 points from 0 to 2π (smooth sin graph)

In [ ]:
x=np.linspace(0,2*np.pi,100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

2. Image size: Resize image from 256x256 to 512x512
 Requires exactly 512 coordinates

In [ ]:
coords=np.linspace(0,255,512)
print(coords)

[  0.           0.49902153   0.99804305   1.49706458   1.99608611
   2.49510763   2.99412916   3.49315068   3.99217221   4.49119374
   4.99021526   5.48923679   5.98825832   6.48727984   6.98630137
   7.4853229    7.98434442   8.48336595   8.98238748   9.481409
   9.98043053  10.47945205  10.97847358  11.47749511  11.97651663
  12.47553816  12.97455969  13.47358121  13.97260274  14.47162427
  14.97064579  15.46966732  15.96868885  16.46771037  16.9667319
  17.46575342  17.96477495  18.46379648  18.962818    19.46183953
  19.96086106  20.45988258  20.95890411  21.45792564  21.95694716
  22.45596869  22.95499022  23.45401174  23.95303327  24.45205479
  24.95107632  25.45009785  25.94911937  26.4481409   26.94716243
  27.44618395  27.94520548  28.44422701  28.94324853  29.44227006
  29.94129159  30.44031311  30.93933464  31.43835616  31.93737769
  32.43639922  32.93542074  33.43444227  33.9334638   34.43248532
  34.93150685  35.43052838  35.9295499   36.42857143  36.92759295
  37.42661448

3. Time series: 0 to 10 seconds, 50 FPS video

In [ ]:
time=np.linspace(0,10,500)
print(time)

[ 0.          0.02004008  0.04008016  0.06012024  0.08016032  0.1002004
  0.12024048  0.14028056  0.16032064  0.18036072  0.2004008   0.22044088
  0.24048096  0.26052104  0.28056112  0.3006012   0.32064128  0.34068136
  0.36072144  0.38076152  0.4008016   0.42084168  0.44088176  0.46092184
  0.48096192  0.501002    0.52104208  0.54108216  0.56112224  0.58116232
  0.6012024   0.62124248  0.64128257  0.66132265  0.68136273  0.70140281
  0.72144289  0.74148297  0.76152305  0.78156313  0.80160321  0.82164329
  0.84168337  0.86172345  0.88176353  0.90180361  0.92184369  0.94188377
  0.96192385  0.98196393  1.00200401  1.02204409  1.04208417  1.06212425
  1.08216433  1.10220441  1.12224449  1.14228457  1.16232465  1.18236473
  1.20240481  1.22244489  1.24248497  1.26252505  1.28256513  1.30260521
  1.32264529  1.34268537  1.36272545  1.38276553  1.40280561  1.42284569
  1.44288577  1.46292585  1.48296593  1.50300601  1.52304609  1.54308617
  1.56312625  1.58316633  1.60320641  1.62324649  1.

5 numbers from 0 to 1

In [ ]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


0 dan 10 gacha, 11 ta son

In [ ]:
arr=np.linspace(0,10,11)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


-5 to 5, 5 numbers

In [ ]:
arr=np.linspace(-5,5,5)
print(arr)

[-5.  -2.5  0.   2.5  5. ]


3 parameters: start, stop, num
The last number is ALSO included!

In [ ]:
print("="*50)
print("ARANGE- you step")
print("="*50)

# 0 to 1, 0.1 step
arr_arange=np.arange(0,1,0.1)
print("arange(0,1,0.1): ")
print(arr_arange)

print("\n" + "="*50)
print("LINSPACE- how many numbers do you need")
print("="*50)

# 10 numbers from 0 to 1
arr_linspace=np.linspace(0,1,10)
print("linspace(0,1,10): ")
print(arr_linspace)
print(f"Sonlar: {len(arr_linspace)} ta")

ARANGE- you step
arange(0,1,0.1): 
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

LINSPACE- how many numbers do you need
linspace(0,1,10): 
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Sonlar: 10 ta


# endpoint Parameter

Default: endpoint=True (takes the last number)

In [ ]:
arr1=np.linspace(0,10,5)
print("endpoint=True (default):")
print(arr1)

endpoint=True (default):
[ 0.   2.5  5.   7.5 10. ]


endpoint=False (does not get the last number)

In [ ]:
arr2=np.linspace(0,10,5,endpoint=False)
print("endpoint=False:")
print(arr2)

endpoint=False:
[0. 2. 4. 6. 8.]


#Retstep - Know the step

When you need an interval in mathematical calculations!

In [ ]:
arr, step=np.linspace(0,10,5,retstep=True)

print("Array: ")
print(arr)

print(f"\n Qadam (step): {step}")

Array: 
[ 0.   2.5  5.   7.5 10. ]

 Qadam (step): 2.5


#For the graph (Preview)

Smooth x coordinates for the sin function

In [ ]:
x=np.linspace(0,10,100)

print(f"X koordinatalari: {len(x)} ta")
print(f"first 5 elements: {x[:5]}")
print(f"last 5 elements: {x[-5:]}")

X koordinatalari: 100 ta
first 5 elements: [0.        0.1010101 0.2020202 0.3030303 0.4040404]
last 5 elements: [ 9.5959596  9.6969697  9.7979798  9.8989899 10.       ]


6 numbers from 0 to 5

In [ ]:
arr=np.linspace(0,5,6)
print(arr)

[0. 1. 2. 3. 4. 5.]


11 numbers from 0 to 100

In [ ]:
arr=np.linspace(0,100,11)
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


-10 to 10, 21 numbers

In [ ]:
arr=np.linspace(-10,10,21)
print(arr)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]


0 to 1, 50 numbers (smooth!)

In [ ]:
arr=np.linspace(0,1,50)
print(arr)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


100 numbers from 0 to 2π

In [ ]:
arr=np.linspace(0,np.pi*2,100)
print(arr)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

0 to 10, 10 with endpoint=False

In [ ]:
arr=np.linspace(0,10,10,endpoint=False)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Finding steps with retstep=True
5 numbers from 0 to 100

In [ ]:
arr,step=np.linspace(0,100,5,retstep=True)

print(f"Array: {arr}")
print(f"Step {step}")

Array: [  0.  25.  50.  75. 100.]
Step 25.0


Equal interval calculation

In [ ]:
arr,step=np.linspace(0,100,5,retstep=True)
print(f"Step: {step}")

Step: 25.0


Mathematical functions

In [ ]:
x=np.linspace(0,2*np.pi,100)
y=np.sin(x) #Smooth sin curve
print(x)
print(y)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

Image resize coordinates

In [ ]:
old_coords=np.arange(256)
new_coords=np.linspace(0,255,512)

print(f"Old coords: {len(old_coords)}")
print(f"New coords: {len(new_coords)}")

Old coords: 256
New coords: 512
