<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/Numpy_special_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY SPECIAL ARRAYS

In [1]:
import numpy as np

5 zeros

In [4]:
zeros_1d=np.zeros(5)
print(zeros_1d)

[0. 0. 0. 0. 0.]


3x3 zeros (2D matrix)

In [5]:
zeros_2d=np.zeros((3,3))
print(zeros_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2x4 zeros (2 rows, 4 columns)

In [7]:
zeros_2x4=np.zeros((2,4))
print(zeros_2x4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


4 units (1D)

In [8]:
ones_1d=np.ones(4)
print(ones_1d)

[1. 1. 1. 1.]


2x2 units (2D)

In [10]:
ones_2d=np.ones((2,2))
print(ones_2d)

[[1. 1.]
 [1. 1.]]


3x5 units

In [11]:
ones_3x5=np.ones((3,5))
print(ones_3x5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Simulate an image**

"Image" = matrix 10x10 black image (pixels = 0)

In [13]:
black_image=np.zeros((10,10))
print(f"Black image:\n {black_image}")

Black image:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


10x10 white image (pixels = 1)

In [14]:
white_image=np.ones((10,10))
print(f"White image: \n {white_image}")

White image: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Shape check

In [16]:
print(f"Black image shape: {black_image.shape}")
print(f"White image shape: {white_image.shape}")

Black image shape: (10, 10)
White image shape: (10, 10)


7 zeros (1D)

In [17]:
zero_1d=np.zeros(7)
print(zero_1d)

[0. 0. 0. 0. 0. 0. 0.]


4x4 matrix of zeros

In [18]:
zeros_4x4=np.zeros((4,4))
print(zeros_4x4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


5x2 units (5 rows, 2 columns)

In [19]:
ones_5x2=np.ones((5,2))
print(ones_5x2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


100x100 "black picture"

In [20]:
black_100x100=np.zeros((100,100))
print(black_100x100)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


50x50 "white painting"

In [21]:
white_50x50=np.ones((50,50))
print(white_50x50)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


Print 3x3 zeros and 3x3 ones side by side

In [22]:
zeros_3x3=np.zeros((3,3))
ones_3x3=np.ones((3,3))
print(zeros_3x3,ones_3x3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
