<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4 ,5])
b = np.zeros(5)
c = np.ones((2, 3))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)
f = np.random.rand(3, 3)

In [ ]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.49641721 0.13679026 0.67538582]
 [0.0235427  0.34032755 0.21365215]
 [0.8579679  0.56898418 0.10194902]]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120],
    [130, 140, 150]
])

ages = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[1, 2]                    # row 1, col 2              # fancy indexing

np.int64(60)

In [ ]:
arr[:, 0]                    # first column

array([ 10,  40,  70, 100, 130])

In [ ]:
arr[ages >= 18]              # boolean mask

array([[ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120],
       [130, 140, 150]])

In [ ]:
arr[[0, 2, 4]]

array([[ 10,  20,  30],
       [ 70,  80,  90],
       [130, 140, 150]])

In [ ]:
print(a + b)      # element-wise

[1. 2. 3. 4. 5.]


In [ ]:
a * b

array([0., 0., 0., 0., 0.])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
preds = np.array([1, 2, 3, 4, 5])
targets = np.array([1.1, 2.2, 2.9, 4.3, 5.1])

In [ ]:
(preds - targets) ** 2      # MSE in one line

array([0.01, 0.04, 0.01, 0.09, 0.01])

In [ ]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1], [2], [3],[4]])
print(arr1.shape)
print(arr2.shape)

(1, 4)
(4, 1)


In [ ]:
arr2 * arr1

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])