<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/Numpy_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy = Numerical Python

In [1]:
!pip install numpy

arrayda outputda vergul yo'q

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Lisda numpydan farqi vergul bor

In [5]:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [7]:
my_arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
fav_numbers=np.array([9,7,2,1,5])
print(fav_numbers)

[9 7 2 1 5]


In [10]:
numbers=np.array([34,56,123,56,23,97,132,68,23,67])
print(numbers)

[ 34  56 123  56  23  97 132  68  23  67]
