<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/RANDOM_DISTRIBUTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

RANDINT

```
np.random.randint(low, high, size)

 low: minimum (included)
 high: maximum (EXCLUDED!)
 size: number of choices

CHOICE

```
np.random.choice(array, size)

 array: list to choose from
 size: number of choices (optional)

In [ ]:
import numpy as np

#RANDINT - Dice & Cards 🎲

1 stone (1-6)

In [ ]:
single_die = np.random.randint(1, 7)
print("1 stone (1-6):")
print(single_die)

1 stone (1-6):
3


10 stone (1-6)

In [ ]:
dice = np.random.randint(1, 7, 10)
print("10 stone (1-6):")
print(dice)

10 stone (1-6):
[4 2 3 4 2 3 6 5 2 5]


Playing card (1-13: A,2,3...K)

In [ ]:
card = np.random.randint(1, 14, 5)
print("5 Playing card (1-13: A,2,3...K):")
print(card)

5 Playing card (1-13: A,2,3...K):
[ 6  6  2  1 10]


Random ages (18-65)

In [ ]:
ages = np.random.randint(18, 66, 8)
print("8 random ages (18-65):")
print(ages)

8 random ages (18-65):
[21 52 53 58 39 38 30 32]


# CHOICE - Simple Selection 🎯

In [ ]:
colors = ['red', 'blue', 'green', 'yellow', 'orange', 'purple']
print("Clors:", colors)

Clors: ['red', 'blue', 'green', 'yellow', 'orange', 'purple']


1 color

In [ ]:
color = np.random.choice(colors)
print("1 color:")
print(color)

1 color:
green


5 colors

In [ ]:
pics = np.random.choice(colors, 5)
print("5 colors:")
print(pics)

5 colors:
['orange' 'orange' 'red' 'blue' 'purple']


Food selection

In [ ]:
foods = ["palav", "samsa", "lagman", "pizza", "manti"]
print("Foods:", foods)

Foods: ['palav', 'samsa', 'lagman', 'pizza', 'manti']


In [ ]:
lunch = np.random.choice(foods)
print("Lunch:")
print(lunch)

Lunch:
palav


Transport

In [ ]:
transports = ["car", "bus", "train", "airplane", "walk"]
print("Transports:", transports)

Transports: ['car', 'bus', 'train', 'airplane', 'walk']


In [ ]:
today = np.random.choice(transports)
print("Today:")
print(today)

Today:
train


#CHOICE - replace=False (Unique!) 🎴

Card game - each card only 1 time

In [ ]:
cards = ['A♠', 'K♠', 'Q♠', 'J♠', '10♠', '9♠', '8♠', '7♠']
print("Cards:", cards)

Cards: ['A♠', 'K♠', 'Q♠', 'J♠', '10♠', '9♠', '8♠', '7♠']


WITH replacement (default)

In [ ]:
hand1 = np.random.choice(cards, 5)
print("Hand1:")
print(hand1)

Hand1:
['Q♠' 'A♠' 'J♠' '8♠' 'J♠']


WITHOUT replacement

In [ ]:
hand2 = np.random.choice(cards, 5, replace=False)
print("Hand2:")
print(hand2)

Hand2:
['J♠' 'Q♠' '9♠' 'A♠' '7♠']


Lottery - 6  unique numbers (1-49)

In [ ]:
lottery = np.random.choice(range(1, 50), 6, replace=False)
print("Lottery:")
print(lottery)

Lottery:
[22 15  8  1 26 37]


#Real Game - Rock Paper Scissors ✊✋✌️

In [ ]:
choices = ['🪨 rock', '📄 paper', '✂️ scissors']
print("Choices:", choices)

Choices: ['🪨 rock', '📄 paper', '✂️ scissors']


In [ ]:
print("10 games:")
for i in range(10):
  player = np.random.choice(choices)
  computer = np.random.choice(choices)
  print(f"Game {i+1} : Player {player} - Computer {computer}")

10 games:
Game 1 : Player 📄 paper - Computer 🪨 rock
Game 2 : Player 📄 paper - Computer 📄 paper
Game 3 : Player ✂️ scissors - Computer ✂️ scissors
Game 4 : Player 🪨 rock - Computer 📄 paper
Game 5 : Player 📄 paper - Computer 📄 paper
Game 6 : Player 📄 paper - Computer ✂️ scissors
Game 7 : Player ✂️ scissors - Computer 🪨 rock
Game 8 : Player ✂️ scissors - Computer 🪨 rock
Game 9 : Player 🪨 rock - Computer 📄 paper
Game 10 : Player ✂️ scissors - Computer 📄 paper


#Dice Statistics

100 rocks

In [ ]:
dice = np.random.randint(1, 7, 100)
print("Dice:", dice)

Dice: [3 2 6 2 2 3 2 1 5 2 4 4 4 3 3 6 6 3 1 6 6 5 2 3 2 1 6 5 6 6 6 2 2 5 3 6 4
 4 3 3 5 2 1 3 5 2 4 2 4 4 4 2 6 4 6 6 4 5 3 6 4 1 6 3 4 2 1 4 6 2 4 6 2 4
 2 4 1 1 6 3 6 4 2 4 5 3 1 5 3 2 4 5 1 2 6 1 6 5 3 6]


Count how many times each number appears

In [ ]:
one = np.count_nonzero(dice == 1)
two = np.count_nonzero(dice == 2)
three = np.count_nonzero(dice == 3)
four = np.count_nonzero(dice == 4)
five = np.count_nonzero(dice == 5)
six = np.count_nonzero(dice == 6)
print(f"1: {one}, 2: {two}, 3: {three}, 4: {four}, 5: {five}, 6: {six}")

1: 11, 2: 20, 3: 16, 4: 20, 5: 11, 6: 22


In [ ]:
one = (dice == 1).sum()
two = (dice == 2).sum()
three = (dice == 3).sum()
four = (dice == 4).sum()
five = (dice == 5).sum()
six = (dice == 6).sum()
print(f"1: {one}, 2: {two}, 3: {three}, 4: {four}, 5: {five}, 6: {six}")

1: 11, 2: 20, 3: 16, 4: 20, 5: 11, 6: 22


#Restaurant Choice

In [ ]:
restaurants = ["Somsa House", 'Manti Palace', "Palav Centre", 'Lag\'mon Cafe', 'Shashlik Garden']
week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
print("Restaurants:", restaurants)
print("Week:", week)

Restaurants: ['Somsa House', 'Manti Palace', 'Palav Centre', "Lag'mon Cafe", 'Shashlik Garden']
Week: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


1 restaurant per day

In [ ]:
for day in week:
  restaurant = np.random.choice(restaurants)
  print(f"{day}: {restaurant}")

Monday: Manti Palace
Tuesday: Somsa House
Wednesday: Manti Palace
Thursday: Palav Centre
Friday: Manti Palace
Saturday: Lag'mon Cafe
Sunday: Shashlik Garden


#Team Selector

In [ ]:
people = ['Ali', 'Vali', 'Guli', 'Diyor', 'Zebo','Kamol', 'Nodira', 'Sardor', 'Malika', 'Jahongir']
print("People:", people)

People: ['Ali', 'Vali', 'Guli', 'Diyor', 'Zebo', 'Kamol', 'Nodira', 'Sardor', 'Malika', 'Jahongir']


Randomly shuffle 10 people

In [ ]:
team = np.random.choice(people, 10, replace=False)
team_a = team[:5]
team_b = team[5:]
print("Team A:", team_a)
print("Team B:", team_b)

Team A: ['Zebo' 'Ali' 'Malika' 'Jahongir' 'Sardor']
Team B: ['Nodira' 'Diyor' 'Kamol' 'Guli' 'Vali']
