<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/RANDOM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Random - data generation, distributions, reproducibility

Matplotlib Basics - plotting, visualization, image display

#RANDOM

Random data generation - for simulations, testing, ML data augmentation!

Main functions:

```
np.random.rand()      # Uniform [0, 1)
np.random.randn()     # Normal (Gaussian)
np.random.randint()   # Random integers
np.random.choice()    # Random selection
np.random.shuffle()   # Shuffle in-place

Distributions:
```
Uniform: Each value has the same probability (lottery)
Normal: Bell curve, natural phenomena (heights, test scores)
Integers: Discrete random values ​​(dice, cards)

Reproducibility:
```
np.random.seed(42)  # Set seed
arr = np.random.rand(5)  # Always same result!

In [ ]:
import numpy as np

##Basic Random Functions

RAND - Uniform distribution [0, 1)

In [ ]:
arr = np.random.rand(5)
print("np.random.rand(5) - Uniform distribution [0, 1):")
print(arr)

np.random.rand(5) - Uniform distribution [0, 1):
[0.68417721 0.24977866 0.56988588 0.90002165 0.47531133]


2D random array

In [ ]:
arr = np.random.rand(3, 4)
print("np.random.rand(3, 4):")
print(arr)

np.random.rand(3, 4):
[[0.38289693 0.26713954 0.73141286 0.25095378]
 [0.75307351 0.83251403 0.43295625 0.7217548 ]
 [0.52865152 0.64384852 0.6266849  0.43058276]]


RANDN - Normal distribution (mean=0, std=1)

In [ ]:
arr = np.random.randn(5)
print("np.random.randn(5) -Normal(0, 1):")
print(arr)

np.random.randn(5) -Normal(0, 1):
[-0.82904787  0.96050738  0.92165649 -0.16232731  0.301286  ]


RANDINT - Random integers

In [ ]:
arr = np.random.randint(0, 100, 10)
print("np.random.randint(0, 100, 10) - Random integers[0, 100):")
print(arr)

np.random.randint(0, 100, 10) - Random integers[0, 100):
[54 80 43 82  2 23 12 65 31 80]


UNIFORM - Specify range

```
np.random.uniform(low, high, size)
                  ↑    ↑     ↑
                  |    |     └─ Nechta son
                  |    └─────── Eng katta qiymat
                  └──────────── Eng kichik qiymat

In [ ]:
arr = np.random.uniform(10, 20, 5)
print("np.random.uniform(10, 20, 5) - Uniform distribution [10, 20):")
print(arr)

np.random.uniform(10, 20, 5) - Uniform distribution [10, 20):
[11.51553014 16.81436863 10.4640213  12.87427239 10.91138524]


##Reproducibility with Seed

WITHOUT SEED - different each time

In [ ]:
print("Without seed (run twice):")
print("Run 1:", np.random.rand(3))
print("Run 2:", np.random.rand(3))

Without seed (run twice):
Run 1: [0.37834813 0.21779835 0.3447389 ]
Run 2: [0.85298758 0.63102778 0.32766246]


WITH SEED - same each time

In [ ]:
print("With seed (run twice):")
np.random.seed(42)
print("Run 1:", np.random.rand(3))

np.random.seed(42)
print("Run 2:", np.random.rand(3))

With seed (run twice):
Run 1: [0.37454012 0.95071431 0.73199394]
Run 2: [0.37454012 0.95071431 0.73199394]


IMPORTANT: Seed affects all subsequent calls

In [ ]:
np.random.seed(42)
arr1 = np.random.rand(3)
arr2 = np.random.rand(3) # Different from arr1

np.random.seed(42)
arr3 = np.random.rand(3)
arr4 = np.random.rand(3)

print("arr1:", arr1)
print("arr2:", arr2)
print("arr3:", arr3)
print("arr4:", arr4)

arr1: [0.37454012 0.95071431 0.73199394]
arr2: [0.59865848 0.15601864 0.15599452]
arr3: [0.37454012 0.95071431 0.73199394]
arr4: [0.59865848 0.15601864 0.15599452]


##Random Choice and Shuffle

CHOICE - random selection

In [ ]:
colors = np.array(["red", "green", "blue", "yellow", "purple"])

Single choice

In [ ]:
choice = np.random.choice(colors)
print("Random color:", choice)

Random color: green


Multiple choices (with replacement)

In [ ]:
choices = np.random.choice(colors, 5)
print("5 random colors:", choices)

5 random colors: ['yellow' 'green' 'yellow' 'purple' 'red']


Without replacement

In [ ]:
choisec = np.random.choice(colors, 3, replace=False)
print("5 random colors without replacement:", choisec)

5 random colors without replacement: ['green' 'yellow' 'purple']


SHUFFLE - in-place shuffling

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)
np.random.shuffle(arr)
print("Shuffled:", arr)

Original: [1 2 3 4 5]
Shuffled: [3 1 5 4 2]


PERMUTATION - returns shuffled copy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
shuffled = np.random.permutation(arr)
print("Original:", arr)
print("Permutation Shuffled:", shuffled)

Original: [1 2 3 4 5]
Permutation Shuffled: [3 2 1 4 5]


##Different Distributions

NORMAL - mean and std specified

In [ ]:
mean, std = 100, 15
arr = np.random.normal(mean, std, 1000)
print(f"Normal distribution (mean={mean}, std={std}):")

print(f"Mean: {arr.mean():.2f} (expected: {mean})")
print(f"Std: {arr.std():.2f} (expected: {std}")

Normal distribution (mean=100, std=15):
Mean: 100.15 (expected: 100)
Std: 15.67 (expected: 15


BINOMIAL - coin flips

In [ ]:
n_trials = 10
p_success = 0.5
arr = np.random.binomial(n_trials, p_success, 1000)
print(f"Binomial distribution (n={n_trials}, p={p_success}):")
print(f"Mean: {arr.mean():.2f} (expected: {n_trials * p_success})")

Binomial distribution (n=10, p=0.5):
Mean: 5.10 (expected: 5.0)


✅ Poisson - hodisalar SONI (diskret)

✅ Exponential - hodisalar orasidagi VAQT (uzluksiz)

POISSON - events per interval

In [ ]:
lambda_rate = 5
arr = np.random.poisson(lambda_rate, 1000)
print(f"Poisson distribution (lambda={lambda_rate}):")
print(f"Mean: {arr.mean():.2f} (expected: {lambda_rate})")

Poisson distribution (lambda=5):
Mean: 5.07 (expected: 5)


EXPONENTIAL - time between events

In [ ]:
scale = 2
arr = np.random.exponential(scale, 1000)
print(f"Exponential distribution (scale={scale}):")
print(f"Mean: {arr.mean():.2f} (expected: {scale})")

Exponential distribution (scale=2):
Mean: 1.86 (expected: 2)
