<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/RANDOM_BASICS_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Basic Random 🎲

1 random number

In [2]:
number = np.random.rand()
print("1 random number:", number)

1 random number: 0.7612798965988667


5 random number

In [3]:
numbers = np.random.rand(5)
print("5 random numbers:", numbers)

5 random numbers: [0.85486447 0.64356417 0.55346732 0.38575114 0.65299577]


2D array - 3x4

In [4]:
arr = np.random.rand(3, 4)
print("2D array - 3x4:")
print(arr)

2D array - 3x4:
[[0.61666656 0.31760317 0.53994495 0.85654695]
 [0.23663691 0.57248169 0.8480238  0.92065147]
 [0.73531464 0.07996724 0.9707267  0.59409327]]


#Seed Magic! 🌱

Seedless - different every time

In [5]:
print("Run 1:", np.random.rand(3))
print("Run 2:", np.random.rand(3))
print("Run 3:", np.random.rand(3))

Run 1: [0.60801116 0.96201636 0.820668  ]
Run 2: [0.22911993 0.59151953 0.17913574]
Run 3: [0.73491    0.36278291 0.76475343]


With Seed - the same every time!

In [6]:
np.random.seed(32)
print("Run 1:", np.random.rand(3))

Run 1: [0.85888927 0.37271115 0.55512878]


In [7]:
np.random.seed(32)
print("Run 2:", np.random.rand(3))

Run 2: [0.85888927 0.37271115 0.55512878]


In [9]:
np.random.seed(32)
print("Run 3:", np.random.rand(3))

Run 3: [0.85888927 0.37271115 0.55512878]


#Lottery - Try your luck! 🎰

Choose 6 numbers from 1-49

 Different result every time

In [10]:
print("Your luck:")
for i in range(3):
  random_floats = np.random.rand(6)
  lottery_numbers = (random_floats * 49 + 1).astype(int)
  print(f"Attempt {i+1}: {lottery_numbers}")

Your luck:
Attempt 1: [47 37 40  5 46 30]
Attempt 2: [30  5 17 33 22 28]
Attempt 3: [35 29  3 28 38 45]


#Exam Simulator 📝

In [11]:
np.random.seed(100)
random_scores = np.random.rand(10)
scores = (random_scores * 100).astype(int)
print("Exam Scores:")
print(scores)

Exam Scores:
[54 27 42 84  0 12 67 82 13 57]


Statistics

In [12]:
print(f"Average Score: {scores.mean():.1f}")
print(f"Highest Score: {scores.max()}")
print(f"Lowest Score: {scores.min()}")

Average Score: 43.8
Highest Score: 84
Lowest Score: 0


#Practice


##Basic Random

Generate 1 random number

In [13]:
number = np.random.rand()
print("1 random number:", number)

1 random number: 0.891321954312264


Generate 7 random number

In [14]:
numbers = np.random.rand(7)
print("7 random numbers:", numbers)

7 random numbers: [0.20920212 0.18532822 0.10837689 0.21969749 0.97862378 0.81168315
 0.17194101]


Generate a 2x3 random matrix

In [15]:
arr = np.random.rand(2, 3)
print("2x3 random matrix:")
print(arr)

2x3 random matrix:
[[0.81622475 0.27407375 0.43170418]
 [0.94002982 0.81764938 0.33611195]]


##Seed Test

In [17]:
np.random.seed(42)
arr1 = np.random.rand(5)
print("Random numbers with seed 42:")
print(arr1)

Random numbers with seed 42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [18]:
np.random.seed(42)
arr2 = np.random.rand(5)
print("Random numbers with seed 42:")
print(arr2)

Random numbers with seed 42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


##Dice Simulator

In [21]:
dice_roll = np.random.rand(10)
dice_number = (dice_roll * 6 + 1).astype(int)
print(f"Attempt {i+1}: {dice_number}")


Attempt 1: [2 4 3 2 4 1 2 3 3 5]
