<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/SET_OPERATIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

```
np.unique() - noyob elementlar
np.intersect1d() - kesishma (umumiy)
np.union1d() - birlashma (hammasi)
np.setdiff1d() - farq (birinchida bor, ikkinchida yo'q)
np.in1d() - a'zolik tekshirish

#np.unique() - Noyob elementlar! 🔍

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
print("Original array:")
print(arr)

Original array:
[3 1 4 1 5 9 2 6 5 3 5]


UNIQUE values

In [ ]:
unique = np.unique(arr)
print("Unique values of the said array:")
print(unique)

Unique values of the said array:
[1 2 3 4 5 6 9]


UNIQUE with counts

In [ ]:
unique_vals, counts = np.unique(arr, return_counts=True)
print("Unique values and counts:")
for val, count in zip(unique_vals, counts):
  print(f"Value {val}: appears {count} time(s)")

Unique values and counts:
Value 1: appears 2 time(s)
Value 2: appears 1 time(s)
Value 3: appears 2 time(s)
Value 4: appears 1 time(s)
Value 5: appears 3 time(s)
Value 6: appears 1 time(s)
Value 9: appears 1 time(s)


UNIQUE with indices

In [ ]:
unique_vals, indices = np.unique(arr, return_index=True)
print("Unique values and first indices:")
for val, idx in zip(unique_vals, indices):
  print(f"Value {val}: first index {idx}")

Unique values and first indices:
Value 1: first index 1
Value 2: first index 6
Value 3: first index 0
Value 4: first index 2
Value 5: first index 4
Value 6: first index 7
Value 9: first index 5


#Intersection & Union! 🔗

In [ ]:
store_a = np.array([101, 102, 103, 104, 105])
store_b = np.array([103, 104, 105, 106, 107])

print("Store A customers:", store_a)
print("Store B customers:", store_b)

Store A customers: [101 102 103 104 105]
Store B customers: [103 104 105 106 107]


INTERSECTION - shops at both

In [ ]:
both_stores = np.intersect1d(store_a, store_b)
print("Customers at BOTH stores:")
print(both_stores)
print(f"Count: {both_stores.size}")

Customers at BOTH stores:
[103 104 105]
Count: 3


UNION - all unique customers

In [ ]:
all_customers = np.union1d(store_a, store_b)
print("Customers at ALL stores:")
print(all_customers)
print(f"Count: {all_customers.size}")

Customers at ALL stores:
[101 102 103 104 105 106 107]
Count: 7


DIFFERENCE - only in A (not in B)

In [ ]:
only_a = np.setdiff1d(store_a, store_b)
print("Customers only at Store A:")
print(only_a)
print(f"Count: {only_a.size}")

Customers only at Store A:
[101 102]
Count: 2


DIFFERENCE - only in B (not in A)

In [ ]:
only_b = np.setdiff1d(store_b, store_a)
print("Customers only at Store B:")
print(only_b)
print(f"Count: {only_b.size}")

Customers only at Store B:
[106 107]
Count: 2


#np.in1d() - Membership! ✅

In [ ]:
all_customers = np.array([101, 102, 103, 104, 105, 106, 107, 108])
vip_customers = np.array([102, 104, 106, 108])

print("All customers:", all_customers)
print("VIP customers:", vip_customers)

All customers: [101 102 103 104 105 106 107 108]
VIP customers: [102 104 106 108]


Check who is VIP

In [ ]:
is_vip = np.isin(all_customers, vip_customers)
print("Is VIP mask:")
print(is_vip)

Is VIP mask:
[False  True False  True False  True False  True]


Select VIP customers

In [ ]:
vip_ids = all_customers[is_vip]
print("VIP customers:")
print(vip_ids)
print(f"Count: {vip_ids.size}")

VIP customers:
[102 104 106 108]
Count: 4


Select non-VIP

In [ ]:
non_vip_ids = all_customers[~is_vip]
print("Non-VIP IDs:", non_vip_ids)
print(f"Count: {non_vip_ids.size}")

Non-VIP IDs: [101 103 105 107]
Count: 4


#Real Example - Student Analysis! 🎓

In [ ]:
passed_math = np.array([1, 2, 3, 5, 6, 8, 9, 10])
passed_physics = np.array([2, 3, 4, 6, 7, 9, 10])
passed_english = np.array([1, 3, 5, 7, 8, 9, 10])

print("Passed Math:", passed_math)
print("Passed Physics:", passed_physics)
print("Passed English:", passed_english)

Passed Math: [ 1  2  3  5  6  8  9 10]
Passed Physics: [ 2  3  4  6  7  9 10]
Passed English: [ 1  3  5  7  8  9 10]


In [ ]:
all_three = np.intersect1d(np.intersect1d(passed_math, passed_physics), passed_english)
print("Students who passed all subjects:")
print(all_three)
print(f"Count: {all_three.size}")

Students who passed all subjects:
[ 3  9 10]
Count: 3


Failed Math only

In [ ]:
failed_math = np.setdiff1d(passed_physics, passed_math)
print("Students who failed Math only:")
print(failed_math)

Students who failed Math only:
[4 7]


Total unique students

In [ ]:
all_student = np.union1d(np.union1d(passed_math, passed_physics), passed_english)
print("Total unique students:")
print(all_student)
print(f"Count: {all_student.size}")

Total unique students:
[ 1  2  3  4  5  6  7  8  9 10]
Count: 10


#Product Analysis

In [ ]:
store_a = np.array([10, 20, 30, 40, 50, 60])
store_b = np.array([30, 40, 50, 60, 70, 80])

print("Store A:", store_a)
print("Store B:", store_b)

Store A: [10 20 30 40 50 60]
Store B: [30 40 50 60 70 80]


In [ ]:
two_there_store = np.intersect1d(store_a, store_b)
print("Products both stores have:")
print(two_there_store)
print(f"Count: {two_there_store.size}")

Products both stores have:
[30 40 50 60]
Count: 4


In [ ]:
union_product = np.union1d(store_a, store_b)
print("All products:")
print(union_product)
print(f"Count: {union_product.size}")

All products:
[10 20 30 40 50 60 70 80]
Count: 8


In [ ]:
only_a = np.setdiff1d(store_a, store_b)
print("Products only in Store A:")
print(only_a)
print(f"Count: {only_a.size}")

Products only in Store A:
[10 20]
Count: 2


In [ ]:
only_b = np.setdiff1d(store_b, store_a)
print("Products only in Store B:")
print(only_b)
print(f"Count: {only_b.size}")

Products only in Store B:
[70 80]
Count: 2


#Unique Values Analysis

In [ ]:
sales_data = np.array([5, 3, 5, 7, 3, 2, 7, 7, 5, 1, 2, 3])

print("Sales data:", sales_data)

Sales data: [5 3 5 7 3 2 7 7 5 1 2 3]


In [ ]:
unique = np.unique(sales_data)
print("Unique values:")
print(unique)

Unique values:
[1 2 3 5 7]


In [ ]:
sales, counts = np.unique(sales_data, return_counts=True)
print("Sales and counts:")
for sale, count in zip(sales, counts):
  print(f"Sale {sale}: {count} times")

Sales and counts:
Sale 1: 1 times
Sale 2: 2 times
Sale 3: 3 times
Sale 5: 3 times
Sale 7: 3 times


In [ ]:
print(counts)

[1 2 3 3 3]


In [ ]:
lot_product = np.argmax(counts)
print("Most sold product:")
for sale, count in zip(sales, counts):
  if count == counts[lot_product]:
   print(f"Sale {sale}: {count} times")

Most sold product:
Sale 3: 3 times
Sale 5: 3 times
Sale 7: 3 times


#Student Membership

In [ ]:
all_students = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
exam_1 = np.array([1, 2, 4, 6, 7, 9, 10])
exam_2 = np.array([2, 3, 5, 6, 8, 9, 10])

print("All students:", all_students)
print("Exam 1:", exam_1)
print("Exam 2:", exam_2)

All students: [ 1  2  3  4  5  6  7  8  9 10]
Exam 1: [ 1  2  4  6  7  9 10]
Exam 2: [ 2  3  5  6  8  9 10]


In [ ]:
is_exam_1 = np.in1d(all_students, exam_1)
print("Exam 1 mask:")
print(is_exam_1)

Exam 1 mask:
[ True  True False  True False  True  True False  True  True]


/tmp/ipython-input-2542585240.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  is_exam_1 = np.in1d(all_students, exam_1)


In [ ]:
all_exam = np.intersect1d(exam_1, exam_2)
print("All exam mask:")
print(all_exam)

All exam mask:
[ 2  6  9 10]


In [ ]:
one_or_two = np.union1d(exam_1, exam_2)
print("One or two exam mask:")
print(one_or_two)

One or two exam mask:
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
not_exam = np.setdiff1d(all_students, one_or_two)
print("Not exam students:")
print(not_exam)

Not exam students:
[]


In [ ]:
one_exam = np.setdiff1d(one_or_two, all_exam)
print("Only one exam students:")
print(one_exam)

Only one exam students:
[1 3 4 5 7 8]
