<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/SLICING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indexing = Single element

Slicing = Multiple elements (part)

In [90]:
import numpy as np

#1D Slicing

arr[:n]    # Boshidan n ta

arr[n:]    # n dan oxirigacha

arr[:]     # Hammasi

arr[-n:]   # Oxirgi n ta

arr[:-n]   # Oxirgi n tasiz

## Basic

In [91]:
arr=np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Array:", arr)
print("Index:  0  1  2  3  4  5  6  7")
print("Index: -8 -7 -6 -5 -4 -3 -2 -1")

Array: [10 20 30 40 50 60 70 80]
Index:  0  1  2  3  4  5  6  7
Index: -8 -7 -6 -5 -4 -3 -2 -1


Basic slicing [start:stop]

In [92]:
print("arr[2:5] = ",arr[2:5])
print("arr[0:3] = ",arr[0:3])
print("arr[4:8] = ",arr[4:8])

arr[2:5] =  [30 40 50]
arr[0:3] =  [10 20 30]
arr[4:8] =  [50 60 70 80]


## Shortcuts

From the beginning

In [93]:
print("arr[:4] = ",arr[:4])
print("arr[:3] = ",arr[:3])

arr[:4] =  [10 20 30 40]
arr[:3] =  [10 20 30]


Until the end

In [94]:
print("arr[5:] = ",arr[5:])
print("arr[3:] = ",arr[3:])

arr[5:] =  [60 70 80]
arr[3:] =  [40 50 60 70 80]


All

In [95]:
print("arr[:] = ",arr[:])

arr[:] =  [10 20 30 40 50 60 70 80]


From the end

In [96]:
print("arr[-3:] = ",arr[-3:])
print("arr[:-2] = ",arr[:-2])

arr[-3:] =  [60 70 80]
arr[:-2] =  [10 20 30 40 50 60]


##Step

Step parameter

In [97]:
print("arr[::2] = ",arr[::2])
print("arr[::3] = ",arr[::3])
print("arr[1::2] = ",arr[1::2])

arr[::2] =  [10 30 50 70]
arr[::3] =  [10 40 70]
arr[1::2] =  [20 40 60 80]


Reverse

In [98]:
print("arr[::-1] = ",arr[::-1])
print("arr[::-2] = ",arr[::-2])

arr[::-1] =  [80 70 60 50 40 30 20 10]
arr[::-2] =  [80 60 40 20]


#2D Slicing

arr[row_start:row_stop, col_start:col_stop]

**Vizual:**
```
       0   1   2   3   4  ← ustunlar
    ┌──────────────────────
  0 │ 1   2   3   4   5
  1 │ 6   7   8   9  10    ← arr[1:3, 2:5]
  2 │11  12  13  14  15    ← Bu qism!
  3 │16  17  18  19  20
  ↑
qatorlar

arr[1:3, 2:5]:
        [ 8,  9, 10]
        [13, 14, 15]

## Rows va Columns

In [99]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])
print("Array shape:", arr.shape)
print("Array:")
print(arr)

Array shape: (4, 5)
Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


ROW SLICING

In [100]:
print("arr[1:3] - Row 1-2:")
print(arr[1:3])

arr[1:3] - Row 1-2:
[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [101]:
print("arr[:2] - first two rows:")
print(arr[:2])

arr[:2] - first two rows:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


COLUMN SLICING

In [102]:
print("arr[:, 1:4] -all rows,columns 1-3:")
print(arr[:, 1:4])

arr[:, 1:4] -all rows,columns 1-3:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [103]:
print("arr[1:3, 2:5] Rows 1-2, Columns 2-4:")
print(arr[1:3, 2:5])

arr[1:3, 2:5] Rows 1-2, Columns 2-4:
[[ 8  9 10]
 [13 14 15]]


#  3D Slicing

Image Cropping!

10x10 RGB rasm

In [104]:
img = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)
print("Image shape:", img.shape)

Image shape: (10, 10, 3)


CENTER CROP

In [105]:
center_crop = img[2:7, 2:7, :]
print("Center 5x5 crop shape:", center_crop.shape)

Center 5x5 crop shape: (5, 5, 3)


TOP-LEFT CORNER (3x3)

In [106]:
top_left=img[:3, :3, :]
print("Top-left 3x3 shape:", top_left.shape)

Top-left 3x3 shape: (3, 3, 3)


 BOTTOM-RIGHT CORNER

In [107]:
bottom_right=img[-4:, -4:, :]
print("Bottom-right 4x4 shape:",bottom_right.shape)

Bottom-right 4x4 shape: (4, 4, 3)


FAQAT RED CHANNEL, MARKAZIY QISM

In [108]:
red_channel=img[2:8, 2:8, 0]
print("Red center shape:", red_channel.shape)

Red center shape: (6, 6)


# SLICING OPERATION

## 1D SLICING


In [109]:
arr_1d = np.arange(0, 100, 5)

Index 2 dan 6 gacha

In [110]:
print(arr_1d[2:6])

[10 15 20 25]


Birinchi 5 ta element

In [111]:
print(arr_1d[:5])

[ 0  5 10 15 20]


Oxirgi 3 ta element

In [112]:
print(arr_1d[-3:])

[85 90 95]


In [113]:
print(arr_1d[::3])

[ 0 15 30 45 60 75 90]


In [114]:
print(arr_1d[::-1])

[95 90 85 80 75 70 65 60 55 50 45 40 35 30 25 20 15 10  5  0]


## 2D SLICING

In [115]:
arr_2d = np.arange(1, 26).reshape(5,5)

First 3 rows

In [116]:
print(arr_2d[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Oxirgi 2 ustun (barcha qator)

In [117]:
print(arr_2d[:, -2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


3x3 markaziy qism


In [118]:
print(arr_2d[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


2x2 top-right burchak\\\\\\\

In [119]:
print(arr_2d[:2, -2:])

[[ 4  5]
 [ 9 10]]


## 3D IMAGE SLICING

In [120]:
img=np.random.randint(0, 256, size=(20, 20, 3), dtype=np.uint8)

10x10 center crop


In [121]:
center_crop=img[5:15, 5:15, :]
print(center_crop.shape)

(10, 10, 3)


Top-left 5x5, faqat red channel

In [122]:
top_left=img[:5, :5, 0]
print(top_left.shape)

(5, 5)


Bottom half (pastki yarmi)

In [123]:
bottom_half=img[10:, :, :]
print(bottom_half.shape)

(10, 20, 3)


#Test

In [124]:
test1=np.arange(0,100).reshape(10,10)
print(test1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [125]:
print("Shape: ", test1.shape)
print("Size:", test1.size)
print("Dimensions: ", test1.dtype)

Shape:  (10, 10)
Size: 100
Dimensions:  int64


In [126]:
print(test1[5,5])

55


In [127]:
print(test1[5])

[50 51 52 53 54 55 56 57 58 59]


In [128]:
print(test1[:, 2])

[ 2 12 22 32 42 52 62 72 82 92]


In [129]:
print(test1[3:7, 3:7])

[[33 34 35 36]
 [43 44 45 46]
 [53 54 55 56]
 [63 64 65 66]]


In [130]:
print(test1[::2, ::2])

[[ 0  2  4  6  8]
 [20 22 24 26 28]
 [40 42 44 46 48]
 [60 62 64 66 68]
 [80 82 84 86 88]]


In [131]:
print(np.diag(test1))

[ 0 11 22 33 44 55 66 77 88 99]


In [132]:
rgb=np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)
print(f"Memory: {rgb.nbytes/(1024*1024):.3f}MB")

Memory: 0.029MB


In [133]:
arr=np.arange(20)
print(arr[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
