<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/SORTING_%26_SEARCHING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.sort() - sort array (copy qaytaradi)
np.argsort() - sort indices
np.argmax() / np.argmin() - max/min indices
np.searchsorted() - binary search
Sorting 2D arrays - axis parameter

```
Key concepts:
SORT:

  Returns sorted copy
  Original unchanged
  Can sort ascending/descending

ARGSORT:

  Returns indices that would sort array
  Keep track of original positions
  Very useful for related arrays



In [ ]:
import numpy as np

#Basic Sorting! 🔍

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
print("Original array:")
print(arr)

Original array:
[3 1 4 1 5 9 2 6 5 3]


SORT (ascending)

In [ ]:
sorted_arr = np.sort(arr)
print("Sorted array:")
print(sorted_arr)

Sorted array:
[1 1 2 3 3 4 5 5 6 9]


SORT (descending)

In [ ]:
sorted_desc = np.sort(arr)[::1]
print("Sorted array (descending):")
print(sorted_desc)

Sorted array (descending):
[1 1 2 3 3 4 5 5 6 9]


Original unchanged

In [ ]:
print("Original (unchanged):")
print(arr)

Original (unchanged):
[3 1 4 1 5 9 2 6 5 3]


#Argsort - Track Positions! 📍

In [ ]:
students = np.array(['Ali', 'Vali', 'Guli', 'Diyor', 'Aziza'])
scores = np.array([85, 92, 78, 95, 88])

print("Students:", students)
print("Scores:", scores)

Students: ['Ali' 'Vali' 'Guli' 'Diyor' 'Aziza']
Scores: [85 92 78 95 88]


Get indices that would sort scores

In [ ]:
sorted_indices = np.argsort(scores)
print("Indices that would sort scores:")
print(sorted_indices)

Indices that would sort scores:
[2 0 4 1 3]


Sort by score (ascending)

In [ ]:
print("Students by score (low to high):")
for idx in sorted_indices:
  print(f"{students[idx]}: {scores[idx]}")

Students by score (low to high):
Guli: 78
Ali: 85
Aziza: 88
Vali: 92
Diyor: 95


Sort by score (descending) - top performers

In [ ]:
sorted_indices_desc = np.argsort(scores)[::-1]
print("Top performers by score (high to low):")
for idx in sorted_indices_desc:
  print(f"{students[idx]}: {scores[idx]}")

Top performers by score (high to low):
Diyor: 95
Vali: 92
Aziza: 88
Ali: 85
Guli: 78


#Argmax & Argmin! 🏆

In [ ]:
products = np.array(['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'])
sales = np.array([45, 120, 80, 35, 95])

print("Products:", products)
print("Sales:", sales)

Products: ['Laptop' 'Phone' 'Tablet' 'Monitor' 'Keyboard']
Sales: [ 45 120  80  35  95]


Find best seller (max)

In [ ]:
max_idx = np.argmax(sales)
print(f"Best seller: {products[max_idx]} ({sales[max_idx]} uints)" )

Best seller: Phone (120 uints)


Find worst seller (min)

In [ ]:
min_idx = np.argmin(sales)
print(f"Worst seller: {products[min_idx]} ({sales[min_idx]} uints)" )

Worst seller: Monitor (35 uints)


Find top 3 sellers

In [ ]:
top3_indices = np.argsort(sales)[3:][::-1]
print("Top 3 sales:")
for i, idx in enumerate(top3_indices, 1):
  print(f"{i}, {products[idx]}: ({sales[idx]} uints)")

Top 3 sales:
1, Phone: (120 uints)
2, Keyboard: (95 uints)


#Sorting 2D Arrays! 📐

In [ ]:
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 82],
                   [95, 92, 90]])

print("Original scores:")
print(scores)

Original scores:
[[85 90 78]
 [92 88 95]
 [78 85 82]
 [95 92 90]]


Sort each row (axis=1)

In [ ]:
sorted_scores = np.sort(scores, axis=1)
print("Sorted scores (each row):")
print(sorted_scores)

Sorted scores (each row):
[[78 85 90]
 [88 92 95]
 [78 82 85]
 [90 92 95]]


Sort each column (axis=0)

In [ ]:
sorted_cols = np.sort(scores, axis=0)
print("Scored (each column):")
print(sorted_cols)

Scored (each column):
[[78 85 78]
 [85 88 82]
 [92 90 90]
 [95 92 95]]


Sort by total score

In [ ]:
total_scores = scores.sum(axis=1)
print("Total scores:")
print(total_scores)

Total scores:
[253 275 245 277]


In [ ]:
sorted_by_total = np.argsort(total_scores)[::-1]
print("Students ranked by total:")
for rank, idx in enumerate(sorted_by_total, 1):
  print(f"Rank {rank}: Student {idx+1} - Total: {total_scores[idx]}")

Students ranked by total:
Rank 1: Student 4 - Total: 277
Rank 2: Student 2 - Total: 275
Rank 3: Student 1 - Total: 253
Rank 4: Student 3 - Total: 245


#Sales Ranking

In [ ]:
products = np.array(['A', 'B', 'C', 'D', 'E'])
sales = np.array([120, 85, 200, 95, 150])

print("Products:", products)
print("Sales:", sales)

Products: ['A' 'B' 'C' 'D' 'E']
Sales: [120  85 200  95 150]


In [ ]:
sorted = np.argsort(sales)[::-1]
print("Products id :", sorted)

Products id : [2 4 0 3 1]


In [ ]:
top3_product = sorted[:3]
print("Top 3 products:")
for idx in top3_product:
  print(f"{products[idx]} : {sales[idx]}")

Top 3 products:
C : 200
E : 150
A : 120


In [ ]:
worst2 = np.argsort(sales)[::1]
print("Worst 2 products:")
for idx in worst2[:2]:
  print(f"{products[idx]} : {sales[idx]}")

Worst 2 products:
B : 85
D : 95


In [ ]:
median_sales = np.median(sales)
print("Median sales:", median_sales)

Median sales: 120.0


#Grade Analysis

In [ ]:
grades = np.array([85, 92, 78, 95, 88, 76, 90, 82, 87, 93])

print("Original grades:", grades)

Original grades: [85 92 78 95 88 76 90 82 87 93]


In [ ]:
sort = np.sort(grades)
print("Sorted grades:", sort)

Sorted grades: [76 78 82 85 87 88 90 92 93 95]


In [ ]:
indices_top = np.argsort(grades)[::-1]
print("Indices of sorted grades:", indices_top)

Indices of sorted grades: [3 9 1 6 4 8 0 7 2 5]


In [ ]:
print("Top 3 students:")
for idx in indices_top[:3]:
  print(f"Student {idx+1}: {grades[idx]}")

Top 3 students:
Student 4: 95
Student 10: 93
Student 2: 92


In [ ]:
indices_bottom = np.argsort(grades)
print("Indices of sorted grades:", indices_bottom)

Indices of sorted grades: [5 2 7 0 8 4 6 1 9 3]


In [ ]:
print("Bottom 3 students:")
for idx in indices_bottom[:3]:
  print(f"Student {idx+1}: {grades[idx]}")

Bottom 3 students:
Student 6: 76
Student 3: 78
Student 8: 82


In [ ]:
middle_grade = np.median(grades)
print("Middle grade:", middle_grade)

Middle grade: 87.5


#2D Performance Matrix

In [ ]:
performance = np.array([[85, 90, 88, 92],
                        [78, 82, 85, 88],
                        [92, 95, 93, 96]])
print("Original performance matrix:")
print(performance)

Original performance matrix:
[[85 90 88 92]
 [78 82 85 88]
 [92 95 93 96]]


In [ ]:
sort_each_employee = np.sort(performance, axis=1)
print("Sorted performance (each employee):")
print(sort_each_employee)

Sorted performance (each employee):
[[85 88 90 92]
 [78 82 85 88]
 [92 93 95 96]]


In [ ]:
sort_row_ids = np.argsort(performance, axis=1)
print("Sorted row indices:")
print(sort_row_ids)

Sorted row indices:
[[0 2 1 3]
 [0 1 2 3]
 [0 2 1 3]]


In [ ]:
sort_col_idx = np.argsort(performance, axis=0)
print("Sorted column indices:")
print(sort_col_idx)

Sorted column indices:
[[1 1 1 1]
 [0 0 0 0]
 [2 2 2 2]]


In [ ]:
overal_best = np.argmax(performance)
print("Overall best performer:", overal_best)

Overall best performer: 11
