<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/STATISTICS_FUNCTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.percentile() - foizlik qiymatlar
np.quantile() - kvantillar
np.corrcoef() - korrelyatsiya
np.cov() - kovariatsiya
np.histogram() - histogram

```
PERCENTILE:

  50th percentile = median
  25th percentile = Q1 (first quartile)
  75th percentile = Q3 (third quartile)

CORRELATION:

  Measures relationship between variables
  Range: -1 to 1
  1 = perfect positive, -1 = perfect negative, 0 = no correlation

In [ ]:
import numpy as np

#Percentiles & Quantiles! 📈

In [ ]:
scores = np.array([65, 70, 75, 78, 82, 85, 88, 90, 92, 95, 98])
print("Student scores:")
print(scores)

Student scores:
[65 70 75 78 82 85 88 90 92 95 98]


MEDIAN (50th percentile)

In [ ]:
median = np.median(scores)
print(f"Median (50th percentile): {median}")

Median (50th percentile): 85.0


PERCENTILES

In [ ]:
p25 = np.percentile(scores, 25)
p50 = np.percentile(scores, 50)
p75 = np.percentile(scores, 75)

print("Percentiles:")
print(f"25th percentile: {p25}")
print(f"50th percentile: {p50}")
print(f"75th percentile: {p75}")

Percentiles:
25th percentile: 76.5
50th percentile: 85.0
75th percentile: 91.0


IQR (Interquartile Range)

In [ ]:
iqr = p75 - p25
print(f"IQR (Q3 - Q1): {iqr}")

IQR (Q3 - Q1): 14.5


In [ ]:
q_25 = np.quantile(scores, 0.25)
q_50 = np.quantile(scores, 0.50)
q_75 = np.quantile(scores, 0.75)

print("Quantiles (same as percentiles):")
print(f"0.25th quantile: {q_25}")
print(f"0.50th quantile: {q_50}")
print(f"0.75th quantile: {q_75}")

Quantiles (same as percentiles):
0.25th quantile: 76.5
0.50th quantile: 85.0
0.75th quantile: 91.0


#Correlation! 🔗

In [ ]:
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
exam_scores = np.array([50, 55, 65, 70, 75, 80, 85, 90, 92, 95])

print("Study hours:", study_hours)
print("Exam scores:", exam_scores)

Study hours: [ 1  2  3  4  5  6  7  8  9 10]
Exam scores: [50 55 65 70 75 80 85 90 92 95]


CORRELATION COEFFICIENT

In [ ]:
correlation_matrix = np.corrcoef(study_hours, exam_scores)
print("Correlation matrix:")
print(correlation_matrix)

Correlation matrix:
[[1.         0.98825434]
 [0.98825434 1.        ]]


Extract correlation value

In [ ]:
correlation = correlation_matrix[0, 1]
print(f"Correlation coefficient: {correlation:.4f}")

Correlation coefficient: 0.9883


Interpret

In [ ]:
if correlation > 0.8:
  print("Strong positive correlation")
elif correlation > 0.5:
  print("Moderate positive correlation")
elif correlation > 0:
  print("Weak positive correlation")
elif correlation == 0:
  print("No correlation")
else:
  print("Negative correlation")

Strong positive correlation


#Covariance! 📉

In [ ]:
temperature = np.array([20, 22, 25, 28, 30, 32, 35])
ice_cream_sales = np.array([50, 60, 75, 90, 100, 120, 140])

print("Temperature (°C):", temperature)
print("Ice cream sales:", ice_cream_sales)

Temperature (°C): [20 22 25 28 30 32 35]
Ice cream sales: [ 50  60  75  90 100 120 140]


COVARIANCE MATRIX

In [ ]:
cov_matrix = np.cov(temperature, ice_cream_sales)
print("Covariance matrix:")
print(cov_matrix)

Covariance matrix:
[[  29.28571429  172.97619048]
 [ 172.97619048 1036.9047619 ]]


Extract covariance

In [ ]:
covariance = cov_matrix[0, 1]
print(f"Covariance: {covariance:.2f}")

Covariance: 172.98


Positive covariance = move together

In [ ]:
if covariance > 0:
  print("Positive covariance")
elif covariance < 0:
  print("Negative covariance")
else:
  print("No covariance")

Positive covariance


#Histogram! 📊

In [ ]:
scores = np.array([45, 52, 58, 62, 65, 68, 72, 75, 78, 82,
                   85, 88, 90, 92, 95, 98])
print("Test scores:")
print(scores)

Test scores:
[45 52 58 62 65 68 72 75 78 82 85 88 90 92 95 98]


HISTOGRAM (count in bins)

In [ ]:
counts, bins = np.histogram(scores, bins=5)

print("Histogram (5 bins):")
print(f"Counts: {counts}")
print(f"Bins: {bins}")

Histogram (5 bins):
Counts: [2 3 3 3 5]
Bins: [45.  55.6 66.2 76.8 87.4 98. ]


Display histogram

In [ ]:
print("Distribution:")
for i in range(len(counts)):
  print(f"Range {bins[i]:.1f} - {bins[i+1]:.1f}: {counts[i]} students {'█' * counts[i] }")

Distribution:
Range 45.0 - 55.6: 2 students ██
Range 55.6 - 66.2: 3 students ███
Range 66.2 - 76.8: 3 students ███
Range 76.8 - 87.4: 3 students ███
Range 87.4 - 98.0: 5 students █████


Custom bins

In [ ]:
custom_bins = [0, 60, 70, 80, 90, 100]
counts, bins = np.histogram(scores, bins=custom_bins)

In [ ]:
print("Grade distribution:")
grades = ['F', 'D', 'C', 'B', 'A']
for i, grade in enumerate(grades):
  print(f"Grade {grade} ({bins[i]:.0f}-{bins[i+1]:.0f}): {counts[i]} students")

Grade distribution:
Grade F (0-60): 3 students
Grade D (60-70): 3 students
Grade C (70-80): 3 students
Grade B (80-90): 3 students
Grade A (90-100): 4 students


#Salary Analysis

In [ ]:
monthly_salaries = np.array([3000, 3500, 4000, 4500, 5000, 5500,
                    6000, 7000, 8000, 10000, 15000])

print("Monthly salaries:")
print(monthly_salaries)

Monthly salaries:
[ 3000  3500  4000  4500  5000  5500  6000  7000  8000 10000 15000]


In [ ]:
median = np.median(monthly_salaries)
print(f"Median (50th percentile): {median}")

Median (50th percentile): 5500.0


In [ ]:
p25 = np.percentile(monthly_salaries, 25)
p50 = np.percentile(monthly_salaries, 50)
p75 = np.percentile(monthly_salaries, 75)

print("Percentiles:")
print(f"25th percentile: {p25}")
print(f"50th percentile: {p50}")
print(f"75th percentile: {p75}")

Percentiles:
25th percentile: 4250.0
50th percentile: 5500.0
75th percentile: 7500.0


In [ ]:
iqr = p75 - p25
print(f"IQR (Q3 - Q1): {iqr}")

IQR (Q3 - Q1): 3250.0


In [ ]:
outliers = monthly_salaries[(monthly_salaries > p75 + 1.5 * iqr) | (monthly_salaries < p25 - 1.5 * iqr)]
print("Outliers:")
print(outliers)

Outliers:
[15000]


#Correlation Analysis

In [ ]:
age = np.array([25, 30, 35, 40, 45, 50, 55, 60])
income = np.array([30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000])

print("Age:", age)
print("Income:", income)

Age: [25 30 35 40 45 50 55 60]
Income: [ 30000  40000  50000  60000  70000  80000  90000 100000]


In [ ]:
correlation_matrix = np.corrcoef(age, income)
print("Correlation matrix:")
print(correlation_matrix)

Correlation matrix:
[[1. 1.]
 [1. 1.]]


Correlation matrixdan value extract

In [ ]:
value_correlation = correlation_matrix[0, 1]
print(f"Correlation coefficient: {value_correlation:.4f}")

Correlation coefficient: 1.0000


In [ ]:
print("Interpretation")
if value_correlation > 0.8:
  print("Strong positive correlation")
elif value_correlation > 0.5:
  print("Moderate positive correlation")
elif value_correlation > 0:
  print("Weak positive correlation")
elif value_correlation == 0:
  print("No correlation")

Interpretation
Strong positive correlation


#Grade Distribution

In [ ]:
test_scores = np.array([45, 55, 62, 68, 72, 75, 78, 82, 85, 88,
                        90, 92, 95, 58, 65, 70, 80, 87, 93, 98])

print("Test scores:")
print(test_scores)

Test scores:
[45 55 62 68 72 75 78 82 85 88 90 92 95 58 65 70 80 87 93 98]


In [ ]:
counts, bins = np.histogram(test_scores, bins=[0, 60, 70, 80, 90, 100])
grade = np.array(['F', 'D', 'C', 'B', 'A'], dtype=str)

total_students = len(test_scores)
print("Grade distribution:")

Grade distribution:


In [ ]:
percentage = (counts / total_students) * 100
for i in range(len(counts)):
  print(f"Grade {grade[i]} ({bins[i]:.0f}-{bins[i+1]:.0f})")

Grade F (0-60)
Grade D (60-70)
Grade C (70-80)
Grade B (80-90)
Grade A (90-100)
