<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/STRING_OPERATIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
np.char.upper() / lower() - katta/kichik harf
np.char.str_len() - uzunlik
np.char.add() - qo'shish
np.char.find() / startswith() - qidirish
np.char.replace() - almashtirish

DTYPE for strings:

  dtype='U10' - Unicode string, max 10 chars
  dtype='S10' - Byte string, max 10 bytes

VECTORIZED:

  Operations apply to all elements at once
  Much faster than Python loops
  Clean, readable code

In [ ]:
import numpy as np

#Case Operations! 🔤

In [ ]:
names = np.array(['Alice', 'BOB', 'Charlie', 'DIANA'], dtype='U20')
print("Original names:")
print(names)

Original names:
['Alice' 'BOB' 'Charlie' 'DIANA']


UPPERCASE

In [ ]:
upper = np.char.upper(names)
print("Uppercase names:")
print(upper)

Uppercase names:
['ALICE' 'BOB' 'CHARLIE' 'DIANA']


 LOWERCASE

In [ ]:
lower = np.char.lower(names)
print("Lowercase names:")
print(lower)

Lowercase names:
['alice' 'bob' 'charlie' 'diana']


CAPITALIZE (first letter upper)

In [ ]:
capitalized = np.char.capitalize(names)
print("Capitalized names:")
print(capitalized)

Capitalized names:
['Alice' 'Bob' 'Charlie' 'Diana']


TITLE CASE

In [ ]:
text = np.array(['hello world', 'python numpy'], dtype='U20')
title = np.char.title(text)
print("Title case:")
print(title)

Title case:
['Hello World' 'Python Numpy']


#String Info & Search! 🔍

In [ ]:
emails = np.array(['alice@gmail.com', 'bob@yahoo.com',
                   'charlie@gmail.com', 'diana@outlook.com'], dtype='U30')
print("Emails:")
print(emails)

Emails:
['alice@gmail.com' 'bob@yahoo.com' 'charlie@gmail.com' 'diana@outlook.com']


STRING LENGTH

In [ ]:
lengths = np.char.str_len(emails)
print("Email lengths:")
print(lengths)

Email lengths:
[15 13 17 17]


FIND substring (returns index, -1 if not found)

In [ ]:
gmail_indices = np.char.find(emails, 'gmail')
print("Find 'gmail' (index):")
print(gmail_indices)

Find 'gmail' (index):
[ 6 -1  8 -1]


Boolean mask: contains 'gmail'

In [ ]:
is_gmail = gmail_indices >= 0
print("Boolean mask for 'gmail':")
print(is_gmail)

Boolean mask for 'gmail':
[ True False  True False]


Filter Gmail users

In [ ]:
gmail_users = emails[is_gmail]
print("Gmail users:")
print(gmail_users)

Gmail users:
['alice@gmail.com' 'charlie@gmail.com']


STARTSWITH

In [ ]:
starts_with_a = np.char.startswith(emails, 'a')
print("Starts with 'a':")
print(starts_with_a)

Starts with 'a':
[ True False False False]


ENDSWITH

In [ ]:
ends_with_com = np.char.endswith(emails, '.com')
print("Ends with '.com':")
print(ends_with_com)

Ends with '.com':
[ True  True  True  True]


#String Manipulation! ✂️

In [ ]:
codes = np.array(['ABC-001', 'ABC-002', 'XYZ-003', 'XYZ-004'], dtype='U10')
print("Original codes:")
print(codes)

Original codes:
['ABC-001' 'ABC-002' 'XYZ-003' 'XYZ-004']


REPLACE

In [ ]:
new_codes = np.char.replace(codes, 'ABC', 'DEF')
print("Replaced codes:")
print(new_codes)

Replaced codes:
['DEF-001' 'DEF-002' 'XYZ-003' 'XYZ-004']


ADD (concatenate)

In [ ]:
names = np.array(['Alice', 'Bob', 'Charlie'], dtype='U20')
last_name = ' Smith'
full_names = np.char.add(names, last_name)
print("Full names:")
print(full_names)

Full names:
['Alice Smith' 'Bob Smith' 'Charlie Smith']


STRIP (remove whitespace)

In [ ]:
messy = np.array(['  hello  ', 'world  ', '  numpy'], dtype='U20')
cleaned = np.char.strip(messy)
print("Strip whitespace:")
print(f"Before: {messy}")
print(f"After: {cleaned}")

Strip whitespace:
Before: ['  hello  ' 'world  ' '  numpy']
After: ['hello' 'world' 'numpy']


MULTIPLY (repeat)

In [ ]:
symbols = np.array(['*', '-', '+'], dtype="U5")
repeated = np.char.multiply(symbols, 5)
print("Repeated symbols:")
print(repeated)

Repeated symbols:
['*****' '-----' '+++++']


#Real Example - Name Processing! 👤

In [ ]:
raw_names = np.array(['  ALICE JOHNSON  ', 'bob SMITH',
                      'Charlie  BROWN', '  diana DAVIS  '], dtype='U30')
print("Raw names:")
for i, name in enumerate(raw_names):
    print(f"{i+1}. {name}")

Raw names:
1.   ALICE JOHNSON  
2. bob SMITH
3. Charlie  BROWN
4.   diana DAVIS  


Strip whitespace

In [ ]:
step1 = np.char.strip(raw_names)
print("Step 1 - Strip:")
print(step1)

Step 1 - Strip:
['ALICE JOHNSON' 'bob SMITH' 'Charlie  BROWN' 'diana DAVIS']


Title case

In [ ]:
step2 = np.char.title(step1)
print("Step 2 - Title case:")
print(step2)

Step 2 - Title case:
['Alice Johnson' 'Bob Smith' 'Charlie  Brown' 'Diana Davis']


Get first names

In [ ]:
first_names = np.array([name.split()[0] for name in step2])
print("Step 3 First names:")
print(first_names)

Step 3 First names:
['Alice' 'Bob' 'Charlie' 'Diana']


Get initials (first letter)

In [ ]:
initials = np.char.upper(np.char.array([name[0] for name in first_names]))
print("Step 4 - Initials:")
print(initials)

Step 4 - Initials:
['A' 'B' 'C' 'D']


Final summary

In [ ]:
print("Summary:")
for raw, clean, first, initial in zip(raw_names, step2, first_names, initials):
  print(f"'{raw.strip()}' →  {clean} → {first} ({initial})")

Summary:
'ALICE JOHNSON' →  Alice Johnson → Alice (A)
'bob SMITH' →  Bob Smith → Bob (B)
'Charlie  BROWN' →  Charlie  Brown → Charlie (C)
'diana DAVIS' →  Diana Davis → Diana (D)


#Email Validation

In [ ]:
emails = np.array(['user1@gmail.com', 'invalid.email',
                   'user2@yahoo.com', 'user3@gmail.com', 'badformat'], dtype='U20')

print("Emails:")
print(emails)

Emails:
['user1@gmail.com' 'invalid.email' 'user2@yahoo.com' 'user3@gmail.com'
 'badformat']


In [ ]:
find = np.char.find(emails, "@")
print("Find '@' index:")
print(find)

Find '@' index:
[ 5 -1  5  5 -1]


In [ ]:
endswith = np.char.endswith(emails, ".com")
print("Ends with '.com':")
print(endswith)

Ends with '.com':
[ True False  True  True False]


In [ ]:
valid_emails = emails[(find != -1) & endswith]
print("Valid emails:")
print(valid_emails)
print(f"Count: {len(valid_emails)}")

Valid emails:
['user1@gmail.com' 'invalid.email' 'user2@yahoo.com' 'user3@gmail.com'
 'badformat']
Count: 5


#Product Code Formatting

In [ ]:
codes = np.array(['abc-001', 'ABC-002', 'xyz-003', 'XYZ-004'], dtype='U10')
print("Original codes:")
print(codes)

Original codes:
['abc-001' 'ABC-002' 'xyz-003' 'XYZ-004']


In [ ]:
uppercase = np.char.upper(codes)
print("Uppercase codes:")
print(uppercase)

Uppercase codes:
['ABC-001' 'ABC-002' 'XYZ-003' 'XYZ-004']


In [ ]:
replace = np.char.replace(uppercase, 'ABC', 'PRD')
print("Replaced codes:")
print(replace)

Replaced codes:
['PRD-001' 'PRD-002' 'XYZ-003' 'XYZ-004']


In [ ]:
strart_add = np.char.add('2024-', replace)
print("Start with '2024-':")
print(strart_add)

Start with '2024-':
['2024-PRD-001' '2024-PRD-002' '2024-XYZ-003' '2024-XYZ-004']


#Name Analysis

In [ ]:
names = np.array(['Alice Smith', 'Bob Johnson', 'Charlie Brown',
        'Diana Wilson', 'Eve Davis'], dtype='U20')

print("Names:")
print(names)

Names:
['Alice Smith' 'Bob Johnson' 'Charlie Brown' 'Diana Wilson' 'Eve Davis']


In [ ]:
each_name_leng = np.char.str_len(names)
print("Length of each name:")
print(each_name_leng)

Length of each name:
[11 11 13 12  9]


In [ ]:
best_name =np.argmax(each_name_leng)
print(f"Best name:{names[best_name]}")

Best name:Charlie Brown


In [ ]:
find_o = np.char.find(names, 'o')
print("Find 'o' index:")
print(find_o)

Find 'o' index:
[-1  1 10 10 -1]


In [ ]:
lower = np.char.lower(names)
print("Lowercase names:")
print(lower)

Lowercase names:
['alice smith' 'bob johnson' 'charlie brown' 'diana wilson' 'eve davis']


In [ ]:
add_jr = np.char.add(lower, ' Jr.')
print("Jr names:")
print(add_jr)

Jr names:
['alice smith Jr.' 'bob johnson Jr.' 'charlie brown Jr.'
 'diana wilson Jr.' 'eve davis Jr.']
