<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/UNIVERSAL_FUNCTIONS_(UFUNCS).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Mathematical - sqrt, square, exp, log
Trigonometric - sin, cos, tan, deg2rad
Comparison - maximum, minimum
Rounding - round, floor, ceil
Other - absolute, sign, clip

```
UFUNCS:

Mathematical operations
Trigonometry
Element-wise functions
Large arrays

Benefits:

✅ Tez (C implementation)
✅ Vectorized (no loops)
✅ Clean code

In [ ]:
import numpy as np

#Mathematical Ufuncs! 🔢

In [ ]:
arr = np.array([1, 4, 9, 16, 25])
print("Original array:")
print(arr)

Original array:
[ 1  4  9 16 25]


SQUARE ROOT

In [ ]:
sqrt = np.sqrt(arr)
print("Square root of the array(sqrt):")
print(sqrt)

Square root of the array(sqrt):
[1. 2. 3. 4. 5.]


SQUARE

In [ ]:
square = np.square(arr)
print("Square of the array(square):")
print(square)

Square of the array(square):
[  1  16  81 256 625]


EXPONENTIAL

In [ ]:
small_arr = np.array([1, 2, 3])
exp = np.exp(small_arr)
print("Exponential of the array(exp):")
print(exp)

Exponential of the array(exp):
[ 2.71828183  7.3890561  20.08553692]


LOGARITHM (natural log)

In [ ]:
log_arr = np.array([1, 10, 100, 1000])
log = np.log(log_arr)
print("Natural log of the array(log):")
print(log)

Natural log of the array(log):
[0.         2.30258509 4.60517019 6.90775528]


LOG10

In [ ]:
log10 = np.log10(log_arr)
print("Log base 10(log10):")
print(log10)

Log base 10(log10):
[0. 1. 2. 3.]


POWER

In [ ]:
base = np.array([2, 3, 4])
power = np.power(base, 3)
print("Power (base^3):")
print(power)

Power (base^3):
[ 8 27 64]


#Trigonometric Ufuncs! 📐

In [ ]:
angles_deg = np.array([0, 30, 45, 60, 90])
print("Angles (degrees):")
print(angles_deg)

Angles (degrees):
[ 0 30 45 60 90]


Convert to radian

In [ ]:
angles_rad = np.deg2rad(angles_deg)
print("Angles (radians):")
print(angles_rad)

Angles (radians):
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


SINE

In [ ]:
sines = np.sin(angles_rad)
print("Sine values:")
for deg, sine in zip(angles_deg, sines):
  print(f"sin({deg}°) = {sine:.4f}")

Sine values:
sin(0°) = 0.0000
sin(30°) = 0.5000
sin(45°) = 0.7071
sin(60°) = 0.8660
sin(90°) = 1.0000


COSINE

In [ ]:
cosines = np.cos(angles_rad)
print("Cosine values:")
for deg, cosine in zip(angles_deg, cosines):
  print(f"cos({deg}°) = {cosine:.4f}")

Cosine values:
cos(0°) = 1.0000
cos(30°) = 0.8660
cos(45°) = 0.7071
cos(60°) = 0.5000
cos(90°) = 0.0000


TANGENT

In [ ]:
tangents = np.tan(angles_rad)
print("Tangent values:")
for deg, tangent in zip(angles_deg, tangents):
  print(f"tan({deg}°) = {tangent}")

Tangent values:
tan(0°) = 0.0
tan(30°) = 0.5773502691896257
tan(45°) = 0.9999999999999999
tan(60°) = 1.7320508075688767
tan(90°) = 1.633123935319537e+16


#Comparison & Rounding! 🔄

In [ ]:
a = np.array([1, 5, 3, 8, 2])
b = np.array([2, 4, 6, 7, 9])

print("Array a:", a)
print("Array b:", b)

Array a: [1 5 3 8 2]
Array b: [2 4 6 7 9]


MAXIMUM (element-wise max)

In [ ]:
maximum = np.maximum(a, b)
print("Maximum (element-wise):")
print(maximum)

Maximum (element-wise):
[2 5 6 8 9]


MINIMUM (element-wise min)

In [ ]:
minimum = np.minimum(a, b)
print("Minimum (element-wise):")
print(minimum)

Minimum (element-wise):
[1 4 3 7 2]


Values with decimals

In [ ]:
values = np.array([1.2, 2.5, 3.7, 4.1, -2.3, -1.8])
print("Original values:")
print(values)

Original values:
[ 1.2  2.5  3.7  4.1 -2.3 -1.8]


ROUND (to nearest)

In [ ]:
rounted = np.round(values)
print("Rounded values:")
print(rounted)

Rounded values:
[ 1.  2.  4.  4. -2. -2.]


FLOOR (round down)

In [ ]:
floor = np.floor(values)
print("Floor (round down):")
print(floor)

Floor (round down):
[ 1.  2.  3.  4. -3. -2.]


CEIL (round up)

In [ ]:
ceil = np.ceil(values)
print("Ceil (round up):")
print(ceil)

Ceil (round up):
[ 2.  3.  4.  5. -2. -1.]


TRUNC (remove decimals)

In [ ]:
trunc = np.trunc(values)
print("Trunc (remove decimals):")
print(trunc)

Trunc (remove decimals):
[ 1.  2.  3.  4. -2. -1.]


Absolute & Clip! 📊

In [ ]:
arr = np.array([-5, -2, 0, 3, 7, -10, 15])
print("Original array:")
print(arr)

Original array:
[ -5  -2   0   3   7 -10  15]


ABSOLUTE VALUE

In [ ]:
abs_arr = np.abs(arr)
print("Absolute values:")
print(abs_arr)

Absolute values:
[ 5  2  0  3  7 10 15]


SIGN (-1, 0, or 1)

In [ ]:
signs = np.sign(arr)
print("Sign of each element:")
print(signs)

Sign of each element:
[-1 -1  0  1  1 -1  1]


CLIP (limit to range)

In [ ]:
print("Clip to range [0, 10]:")

clipped = np.clip(arr, 0, 10)
print(clipped)

Clip to range [0, 10]:
[ 0  0  0  3  7  0 10]


temperature clipping

In [ ]:
temperatures = np.array([18, 25, 32, 15, 28, 35, 10])
print("Temperatures:", temperatures)
print("Clip to comfortable range [20, 30]:")
comfortable = np.clip(temperatures, 20, 30)
print(comfortable)

Temperatures: [18 25 32 15 28 35 10]
Clip to comfortable range [20, 30]:
[20 25 30 20 28 30 20]


#Data Normalization

In [ ]:
data = np.array([100, 150, 200, 250, 300])
print("Data:")
print(data)

Data:
[100 150 200 250 300]


Square root normalization

In [ ]:
sqrt_normalization = np.sqrt(data)
print("Sqrt normalization:")
print(sqrt_normalization)

Sqrt normalization:
[10.         12.24744871 14.14213562 15.8113883  17.32050808]


Log normalization

In [ ]:
log_normalization = np.log10(data)
print("Log normalization:")
print(log_normalization)

Log normalization:
[2.         2.17609126 2.30103    2.39794001 2.47712125]


Min-max normalization

In [ ]:
min = data.min()
max = data.max()
min_max_normalization = (data - min) / (max - min)
print("Min-max normalization to [0, 1]:")
print(min_max_normalization)

Min-max normalization to [0, 1]:
[0.   0.25 0.5  0.75 1.  ]


#Circle Calculations

In [ ]:
radii = np.array([1, 2, 3, 4, 5])
print("Circle radii:")
print(radii)

Circle radii:
[1 2 3 4 5]


Calculate area

In [ ]:
area = np.pi * np.square(radii)
print("Area:")
for r, s in zip(radii, area):
  print(f"raius: {r}, area: {s}")

Area:
raius: 1, area: 3.141592653589793
raius: 2, area: 12.566370614359172
raius: 3, area: 28.274333882308138
raius: 4, area: 50.26548245743669
raius: 5, area: 78.53981633974483


Calculate circumference

In [ ]:
circumference = 2 * np.pi * radii
print(circumference)
print("Circumference:")
for r, c in zip(radii, circumference):
  print(f"raius: {r}, circumference: {c}")

[ 6.28318531 12.56637061 18.84955592 25.13274123 31.41592654]
Circumference:
raius: 1, circumference: 6.283185307179586
raius: 2, circumference: 12.566370614359172
raius: 3, circumference: 18.84955592153876
raius: 4, circumference: 25.132741228718345
raius: 5, circumference: 31.41592653589793


Grade Processing

In [ ]:
decimals = np.array([85.7, 92.3, 78.9, 88.1, 95.6, 73.2])
print("Decimals:")
print(decimals)

Decimals:
[85.7 92.3 78.9 88.1 95.6 73.2]


Round to nearest integer

In [ ]:
rounded = np.round(decimals)
print("Rounded to nearest integer:")
print(rounded)

Rounded to nearest integer:
[86. 92. 79. 88. 96. 73.]


Clip to valid range [0, 100]

In [ ]:
clip = np.clip(decimals, 0, 100)
print("Clipped to [0, 100]:")
print(clip)

Clipped to [0, 100]:
[85.7 92.3 78.9 88.1 95.6 73.2]


Calculate absolute difference from 85 (target)

In [ ]:
absolute = np.abs(decimals - 85)
print("Absolute difference from 85:")
print(absolute)

Absolute difference from 85:
[ 0.7  7.3  6.1  3.1 10.6 11.8]


Find sign: above(+1) or below(-1) target

In [ ]:
sign = np.sign(decimals - 85)
print("Sign: above(+1) or below(-1) target:")
print(sign)

Sign: above(+1) or below(-1) target:
[ 1.  1. -1.  1.  1. -1.]
