<a href="https://colab.research.google.com/github/Davron030901/Numpy/blob/main/WEEK_1_REVIEW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1D SLICING
arr[start:stop]       # start dan stop gacha

arr[start:stop:step]  # qadam bilan

arr[:n]               # Birinchi n ta

arr[n:]               # n dan oxirigacha

arr[-n:]              # Oxirgi n ta

arr[::step]           # Har step-chi

arr[::-1]             # TESKARI! ✨

# 2D SLICING
arr[r1:r2, c1:c2]     # Rows r1-r2, cols c1-c2

arr[:, c1:c2]         # Barcha qator, cols c1-c2

arr[r1:r2, :]         # Rows r1-r2, barcha ustun

# 3D SLICING (RGB)
img[y1:y2, x1:x2, :]  # Region crop

img[:, :, channel]    # Bitta channel

img[y1:y2, x1:x2, c]  # Region + channel

In [ ]:
import numpy as np
print("="*60)
print("HAFTA 1 - COMPLETE REVIEW")
print("="*60)

HAFTA 1 - COMPLETE REVIEW


#CREATING AN ARRAY

np.array()

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print("np.array():", arr1)

np.array(): [1 2 3 4 5]


np.zeros()

In [ ]:
arr2 = np.zeros((3, 3))
print("np.zeros((3, 3)):\n", arr2)

np.zeros((3, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


np.ones()

In [ ]:
arr3 = np.ones((2, 4))
print("np.ones((2, 4)):\n", arr3)

np.ones((2, 4)):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.arange()

In [ ]:
arr4 = np.arange(0, 10, 2)
print("np.arange(0, 10, 2):",arr4)

np.arange(0, 10, 2): [0 2 4 6 8]


np.linspace()

In [ ]:
arr5 = np.linspace(0, 1, 5)
print("np.linspace(0, 1, 5):",arr5)

np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


#ARRAY PROPERTIES

In [ ]:
test_arr = np.arange(12).reshape(3, 4)
print("Array:\n",test_arr)
print("Shape:",test_arr.shape)
print("Size:",test_arr.size)
print("Ndim:",test_arr.ndim)
print("Dtype:",test_arr.dtype)
print("Itemsize:",test_arr.itemsize)
print("Nbytes:",test_arr.nbytes)

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Size: 12
Ndim: 2
Dtype: int64
Itemsize: 8
Nbytes: 96


#INDEXING

1D

In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D arr[0] = ", arr_1d[0])
print("1D arr[-1] = ", arr_1d[-1])

1D arr[0] =  10
1D arr[-1] =  50


2D

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D arr[0, 1] = ", arr_2d[0, 1])
print("2D arr[1] = ", arr_2d[1])
print("2d arr[:, 0] = ", arr_2d[:, 0])

2D arr[0, 1] =  2
2D arr[1] =  [4 5 6]
2d arr[:, 0] =  [1 4]


3D (RGB)

In [ ]:
img = np.zeros((5, 5, 3), dtype=np.uint8)
print("3D img[2, 2]:", img[2, 2])
print("3D img[:,:,0] shape:", img[:,:,0].shape)

3D img[2, 2]: [0 0 0]
3D img[:,:,0] shape: (5, 5)


#SLICING

1D slicing

In [ ]:
arr=np.arange(10)
print("Array:", arr)
print("arr[2:5]:", arr[2:5])
print("arr[:3]:", arr[:3])
print("arr[5:]:", arr[5:])
print("arr[::2]:", arr[::2])
print("arr[::-1]:", arr[::-1])

Array: [0 1 2 3 4 5 6 7 8 9]
arr[2:5]: [2 3 4]
arr[:3]: [0 1 2]
arr[5:]: [5 6 7 8 9]
arr[::2]: [0 2 4 6 8]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]


2D slicing

In [ ]:
arr_2d = np.arange(1, 13).reshape(3, 4)
print("Array:\n", arr_2d)
print("arr_2d[1:3, 1:3]:\n", arr_2d[1:3, 1:3])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr_2d[1:3, 1:3]:
 [[ 6  7]
 [10 11]]


3D slicing

In [ ]:
img = np.ones((5, 5, 3), dtype=np.uint8)
print("3D img:\n",img)
print("3D img[2:4, 2:4]:\n", img[2:4, 2:4])

3D img:
 [[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
3D img[2:4, 2:4]:
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
